import test from 'node:test';
import assert from 'node:assert/strict';
import {OrderBook,Footprint,matchToTrade} from '../src/orderflow.js';
import {RulesEngine,condition,validateAlert} from '../src/alerts-v2.js';
import {DRAWING_TOOLS,validateDrawing,drawingGeometry,LEGACY_DRAWINGS} from '../src/drawings.js';
const snapshot={type:'snapshot',product_id:'BTC-USD',bids:[['100','2'],['99','3']],asks:[['101','4'],['102','1']]};
test('L2 waits for snapshot and replaces absolute quantity rather than adding deltas',()=>{const b=new OrderBook('BTC-USD');assert.equal(b.apply({type:'l2update',product_id:'BTC-USD',changes:[['buy','100','9']]}),false);b.apply(snapshot,100);b.apply({type:'l2update',product_id:'BTC-USD',changes:[['buy','100','1'],['sell','102','0']]},101);const s=b.snapshot();assert.equal(s.bids[0].size,1);assert.equal(s.bids[1].cumulative,4);assert.equal(s.asks.length,1);assert.equal(s.spread,1);});
test('invalid L2 batch is atomic and reconnect discards stale book',()=>{const b=new OrderBook('BTC-USD');b.apply(snapshot);assert.throws(()=>b.apply({type:'l2update',product_id:'BTC-USD',changes:[['buy','100','9'],['bad','101','2']]}));assert.equal(b.bids.get(100),2);b.reset();assert.equal(b.ready,false);assert.equal(b.bids.size,0);});
test('book ignores other products and malformed snapshot preserves current state',()=>{const b=new OrderBook('BTC-USD');b.apply(snapshot);assert.equal(b.apply({...snapshot,product_id:'ETH-USD'}),false);assert.throws(()=>b.apply({...snapshot,bids:[['bad','1']]}));assert.equal(b.bids.get(100),2);});
test('Coinbase maker side is inverted for aggressor-side delta',()=>{const t=matchToTrade({type:'match',trade_id:1,side:'sell',price:'100',size:'2',time:'2026-01-01T00:00:00Z',product_id:'BTC-USD'});assert.equal(t.side,'buy');assert.equal(t.price,100);assert.equal(matchToTrade({type:'ticker',side:'buy'}),null);});
test('footprint aggregates actual trades, deduplicates IDs and caps retained bars',()=>{const f=new Footprint(60,1,2);assert.equal(f.push({id:1,time:1,price:100,size:2,side:'buy'}),true);assert.equal(f.push({id:1,time:2,price:100,size:2,side:'buy'}),false);f.push({id:2,time:3,price:100,size:3,side:'sell'});assert.equal(f.rows()[0].delta,-1);f.push({id:3,time:61,price:101,size:4,side:'buy'});f.push({id:4,time:121,price:101,size:1,side:'sell'});assert.equal(f.rows().length,2);assert.equal(f.rows().at(-1).cvd,3);assert.equal(f.push({id:5,time:1,price:100,size:1,side:'buy'}),false);});
const rule=(x={})=>({symbol:'BTC-USD',conditions:[{source:'price',op:'crossAbove',target:100}],...x});
test('crossing alerts establish baseline and once disables after actual crossing',()=>{const r=new RulesEngine(),a=r.add(rule());assert.equal(r.update('BTC-USD',{price:101}).length,0);r.update('BTC-USD',{price:99});const e=r.update('BTC-USD',{price:101});assert.equal(e.length,1);assert.equal(a.active,false);assert.equal(r.update('BTC-USD',{price:102}).length,0);});
test('all conditions, dynamic series targets and escaped placeholder replacement are computed',()=>{const r=new RulesEngine();r.add(rule({frequency:'every',conditions:[{source:'price',op:'above',target:'ema'},{source:'rsi',op:'below',target:70}],message:'{{symbol}} {{price}} / {{rsi}}'}));assert.equal(r.update('BTC-USD',{price:105,ema:100,rsi:80}).length,0);assert.equal(r.update('BTC-USD',{price:105,ema:100,rsi:60})[0].message,'BTC-USD 105 / 60');});
test('close, once-per-bar, cooldown and market/replay gating remain independent',()=>{const r=new RulesEngine();r.add(rule({frequency:'close',cooldown:60,mode:'market',conditions:[{source:'price',op:'above',target:1}]}));assert.equal(r.update('BTC-USD',{price:2},{time:100,barTime:60,confirmed:false}).length,0);assert.equal(r.update('BTC-USD',{price:2},{time:101,barTime:60,confirmed:true,mode:'replay'}).length,0);assert.equal(r.update('BTC-USD',{price:2},{time:120,barTime:60,confirmed:true}).length,1);assert.equal(r.update('BTC-USD',{price:2},{time:200,barTime:60,confirmed:true}).length,0);assert.equal(r.update('BTC-USD',{price:2},{time:201,barTime:180,confirmed:true}).length,1);});
test('expired and nonfinite condition inputs never trigger',()=>{const r=new RulesEngine(),a=r.add(rule({expires:100}));r.update('BTC-USD',{price:99},{time:99});assert.equal(r.update('BTC-USD',{price:101},{time:100}).length,0);assert.equal(a.status,'expired');assert.equal(condition({source:'x',op:'above',target:1},{x:NaN}),false);assert.throws(()=>validateAlert(rule({conditions:[{source:'x',op:'eval',target:1}]})));});

const chart={toX:x=>x,timeIndex:t=>t/60,toY:p=>400-p,plotWidth:800,price:{y:0,h:500},rawBars:Array.from({length:10},(_,i)=>({t:i*60,c:100+i}))};
for(const [type,def] of Object.entries(DRAWING_TOOLS))test('drawing schema and finite geometry: '+type,()=>{const d={id:type,type,points:Array.from({length:def.points||5},(_,i)=>({t:i*60,p:100+i*3})),width:2,color:'#123abc'};validateDrawing(d);if(!LEGACY_DRAWINGS.has(type)){const g=drawingGeometry(d,chart);assert.ok(g.segments.length+g.labels.length+g.rects.length>0);for(const l of g.segments)for(const point of [l.a,l.b])assert.ok(Number.isFinite(point.x)&&Number.isFinite(point.y));}assert.throws(()=>validateDrawing({...d,points:[]}));});
