import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import http from 'node:http';
import {createAureonServer} from '../server/app.mjs';
import {Store} from '../server/store.mjs';
import {AlertMonitor} from '../server/monitor.mjs';
import {Providers,validatePaperOrder,ALPACA_PAPER,ALPACA_DATA} from '../server/providers.mjs';
import {defaultExtensions,validateExtensions} from '../src/workspace-v2.js';
const payload=()=>({application:'Aureon Terminal',version:2,workspace:{version:1,symbol:'BTC-USD',interval:3600,drawings:{},indicators:['ema'],watchlist:['BTC-USD'],style:'candles'},extensions:defaultExtensions()});
const response=data=>new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});
test('native HTTP server authentication, isolation, revision conflicts, services and disk persistence',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'aureon-server-'));const requests=[];
 const fetcher=async(url,opts)=>{requests.push({url,opts});if(url.startsWith(ALPACA_DATA)){return response({bars:{AAPL:[{t:'2025-01-02T00:00:00Z',o:100,h:110,l:90,c:105,v:1000}]}});}if(opts.method==='DELETE')return new Response(null,{status:204});if(opts.method==='POST')return response({id:randomUUID(),...JSON.parse(opts.body),status:'accepted'});if(url.includes('/orders'))return response([]);return response({id:'paper-account',status:'ACTIVE',equity:'100000',buying_power:'100000'});};
 let app=await createAureonServer({root:resolve('.'),dataDir:directory,monitor:false,key:'TEST_SECRET_KEY_ID',secret:'TEST_SECRET_VALUE',brokerUser:'alice',fetcher});
 const listen=async()=>{await new Promise(r=>app.server.listen(0,'127.0.0.1',r));return 'http://127.0.0.1:'+app.server.address().port;};let base=await listen();
 const client=()=>({cookie:'',csrf:'',async call(path,{method='GET',body,headers={},origin=base,csrf=true}={}){const r=await fetch(base+path,{method,headers:{Origin:origin,...(this.cookie?{Cookie:this.cookie}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...(csrf&&this.csrf?{'X-CSRF-Token':this.csrf}:{}),...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});const cookie=r.headers.get('set-cookie');if(cookie)this.cookie=cookie.split(';')[0];let data;try{data=await r.json();}catch{}return{status:r.status,data,headers:r.headers};},async register(name,password='very-safe-password-123'){const r=await this.call('/v2/register',{method:'POST',body:{username:name,password}});assert.equal(r.status,200,JSON.stringify(r.data));this.csrf=(await this.call('/v2/session')).data.csrf;return r;}});
 const alice=client(),bob=client(),anon=client();let wid=randomUUID(),ideaId;
 try{
 await t.test('anonymous private endpoints require authentication; static modules remain available',async()=>{assert.equal((await anon.call('/v2/workspaces')).status,401);assert.equal((await fetch(base+'/src/script.js')).status,200);assert.equal((await anon.call('/v2/session')).data.capabilities.monitor,false);});
 await t.test('register two accounts with HttpOnly SameSite cookies and hashed credentials',async()=>{const a=await alice.register('alice');await bob.register('bob');assert.match(a.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);const disk=await readFile(join(directory,'state.json'),'utf8');assert.ok(!disk.includes('very-safe-password-123'));assert.ok(!disk.includes(alice.cookie.split('=')[1]));assert.equal((await stat(join(directory,'state.json'))).mode&0o777,0o600);});
 await t.test('mutation requires both correct Origin and CSRF',async()=>{assert.equal((await alice.call('/v2/workspaces/'+wid,{method:'PUT',body:{name:'A',payload:payload()},headers:{'If-Match':'0'},csrf:false})).status,403);assert.equal((await alice.call('/v2/workspaces/'+wid,{method:'PUT',body:{name:'A',payload:payload()},headers:{'If-Match':'0'},origin:'https://evil.invalid'})).status,403);});
 await t.test('workspace creates revision one and cannot be read or overwritten by another user',async()=>{const r=await alice.call('/v2/workspaces/'+wid,{method:'PUT',body:{name:'Alpha',payload:payload()},headers:{'If-Match':'0'}});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.revision,1);assert.equal((await bob.call('/v2/workspaces/'+wid)).status,404);assert.equal((await bob.call('/v2/workspaces')).data.items.length,0);assert.equal((await bob.call('/v2/workspaces/'+wid,{method:'PUT',body:{name:'Attack',payload:payload()},headers:{'If-Match':'1'}})).status,404);});
 await t.test('stale and missing revisions never overwrite newer state',async()=>{assert.equal((await alice.call('/v2/workspaces/'+wid,{method:'PUT',body:{name:'No revision',payload:payload()}})).status,428);assert.equal((await alice.call('/v2/workspaces/'+wid,{method:'PUT',body:{name:'Stale',payload:payload()},headers:{'If-Match':'0'}})).status,409);assert.equal((await alice.call('/v2/workspaces/'+wid)).data.name,'Alpha');});
 await t.test('concurrent writes serialize and exactly one succeeds at the same revision',async()=>{const r=await Promise.all(['One','Two'].map(name=>alice.call('/v2/workspaces/'+wid,{method:'PUT',body:{name,payload:payload()},headers:{'If-Match':'1'}})));assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);assert.equal((await alice.call('/v2/workspaces/'+wid)).data.revision,2);});
 await t.test('Host rebinding, private state and traversal are blocked',async()=>{const hostile=await new Promise((resolve,reject)=>{const q=http.request(base+'/v2/session',{headers:{Host:'evil.invalid'}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});q.on('error',reject);q.end();});assert.equal(hostile,421);for(const path of ['/.env','/.aureon-data/state.json','/server/app.mjs','/package.json','/%2e%2e/server/app.mjs'])assert.equal((await fetch(base+path)).status,404,path);});
 await t.test('server alert ownership, capabilities, pause/resume and deletion',async()=>{const r=await alice.call('/v2/alerts',{method:'POST',body:{symbol:'BTC-USD',interval:3600,conditions:[{source:'price',op:'above',target:100}]}});assert.equal(r.status,201);assert.equal((await bob.call('/v2/alerts')).data.items.length,0);assert.equal((await bob.call('/v2/alerts/'+r.data.id,{method:'DELETE'})).status,404);assert.equal((await alice.call('/v2/alerts/'+r.data.id,{method:'PATCH',body:{active:false}})).status,200);assert.equal((await alice.call('/v2/alerts')).data.items[0].active,false);assert.equal((await alice.call('/v2/alerts',{method:'POST',body:{symbol:'BTC-USD',interval:3600,conditions:[{source:'custom',op:'above',target:100}]}})).status,400);assert.equal((await alice.call('/v2/alerts/'+r.data.id,{method:'DELETE'})).status,200);});
 await t.test('ideas explicitly share chart snapshots, likes and comments but enforce delete ownership',async()=>{const r=await alice.call('/v2/ideas',{method:'POST',body:{title:'My study',text:'<script>not executed by UI</script>',symbol:'BTC-USD',workspace:payload()}});assert.equal(r.status,201);ideaId=r.data.id;const list=(await bob.call('/v2/ideas')).data.items;assert.equal(list[0].workspace,undefined);assert.equal((await bob.call('/v2/ideas/'+ideaId)).data.workspace.application,'Aureon Terminal');assert.equal((await bob.call('/v2/ideas/'+ideaId+'/like',{method:'POST',body:{}})).status,200);assert.equal((await bob.call('/v2/ideas/'+ideaId+'/comments',{method:'POST',body:{text:'Independent comment'}})).status,200);const idea=(await alice.call('/v2/ideas/'+ideaId)).data;assert.equal(idea.likes.length,1);assert.equal(idea.comments[0].username,'bob');assert.equal((await bob.call('/v2/ideas/'+ideaId,{method:'DELETE'})).status,404);});
 await t.test('SSE routes private events only to intended user',async()=>{const ca=new AbortController(),cb=new AbortController();const [a,b]=await Promise.all([fetch(base+'/v2/events',{headers:{Cookie:alice.cookie},signal:ca.signal}),fetch(base+'/v2/events',{headers:{Cookie:bob.cookie},signal:cb.signal})]);const ar=a.body.getReader(),br=b.body.getReader();await ar.read();await br.read();const uid=(await alice.call('/v2/session')).data.user.id;app.emit(uid,{type:'test-private',value:7});const text=new TextDecoder().decode((await ar.read()).value);assert.match(text,/test-private/);const pending=br.read();const received=await Promise.race([pending.then(()=>true),new Promise(r=>setTimeout(()=>r(false),50))]);assert.equal(received,false);ca.abort();cb.abort();pending.catch(()=>{});});
 await t.test('paper brokerage is restricted to configured owner and fixed paper endpoint',async()=>{assert.equal((await alice.call('/v2/session')).data.capabilities.broker,false);await app.close();app=await createAureonServer({root:resolve('.'),dataDir:directory,monitor:false,key:'TEST_SECRET_KEY_ID',secret:'TEST_SECRET_VALUE',brokerUser:'alice',fetcher});base=await listen();assert.equal((await bob.call('/v2/broker/account')).status,403);assert.equal((await alice.call('/v2/broker/account')).data.status,'ACTIVE');const r=await alice.call('/v2/broker/orders',{method:'POST',body:{symbol:'AAPL',side:'buy',type:'limit',qty:1,limit_price:100,time_in_force:'day',client_order_id:'test-unique-id',url:'https://api.alpaca.markets',secret:'clientinjection'}});assert.equal(r.status,201);assert.ok(!JSON.stringify(r.data).includes('TEST_SECRET'));const call=requests.at(-1);assert.equal(new URL(call.url).origin,ALPACA_PAPER);assert.equal(call.opts.headers['APCA-API-SECRET-KEY'],'TEST_SECRET_VALUE');assert.equal(JSON.parse(call.opts.body).url,undefined);assert.equal((await alice.call('/v2/broker/orders/'+r.data.id,{method:'DELETE'})).status,200);});
 await t.test('equity data adapter uses configured data host and preserves raw price provenance',async()=>{const r=await alice.call('/v2/market/bars?symbol=AAPL&timeframe=1Day&start=2025-01-01');assert.equal(r.status,200);assert.equal(r.data.bars.length,1);assert.match(r.data.source,/raw\/unadjusted/);assert.equal(new URL(requests.at(-1).url).origin,ALPACA_DATA);assert.equal((await bob.call('/v2/market/bars?symbol=AAPL&timeframe=1Day&start=2025-01-01')).status,403);});
 await t.test('password whitespace is preserved, not silently normalized',async()=>{const space=client();await space.register('spaces','  significant-password  ');assert.equal((await anon.call('/v2/login',{method:'POST',body:{username:'spaces',password:'significant-password'}})).status,401);assert.equal((await anon.call('/v2/login',{method:'POST',body:{username:'spaces',password:'  significant-password  '}})).status,200);});
 await t.test('restart restores sessions, users, workspaces and explicit shared ideas',async()=>{await app.close();app=await createAureonServer({root:resolve('.'),dataDir:directory,monitor:false});base=await listen();assert.equal((await alice.call('/v2/session')).data.user.username,'alice');assert.equal((await alice.call('/v2/workspaces/'+wid)).data.revision,2);assert.equal((await bob.call('/v2/ideas/'+ideaId)).data.comments.length,1);});
 await t.test('logout revokes session; deletion does not cross accounts',async()=>{assert.equal((await alice.call('/v2/logout',{method:'POST',body:{}})).status,200);assert.equal((await alice.call('/v2/workspaces')).status,401);assert.equal((await bob.call('/v2/session')).data.user.username,'bob');});
 }finally{await app.close();await rm(directory,{recursive:true,force:true});}
});
test('monitor persists actual crossings, suppresses deleted pending alerts, and exposes provider errors',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'aureon-monitor-')),store=await new Store(directory).init();let price=99,waiter=null;const events=[];
 const provider={alertValues:async()=>{if(waiter)await waiter;return{values:{price},time:Date.now()/1000,barTime:0};}};
 const monitor=new AlertMonitor(store,provider,(user,event)=>events.push({user,event}));const rule={id:'r1',userId:'u1',symbol:'BTC-USD',interval:60,active:true,updated:1,frequency:'once',conditions:[{source:'price',op:'crossAbove',target:100}]};
 try{await store.transaction(s=>{s.users.push({id:'u1'});s.alerts.push(rule);});await monitor.poll();assert.equal(events.length,0);price=101;await monitor.poll();assert.equal(events.length,1);assert.equal(store.state.alertLog.length,1);assert.equal(store.state.alerts[0].active,false);await monitor.poll();assert.equal(events.length,1);
 await store.transaction(s=>s.alerts.push({...rule,id:'r2',updated:2,frequency:'every',conditions:[{source:'price',op:'above',target:1}]}));let release;waiter=new Promise(r=>release=r);const poll=monitor.poll();await new Promise(r=>setTimeout(r,5));await store.transaction(s=>{s.alerts=s.alerts.filter(r=>r.id!=='r2');});release();await poll;assert.equal(events.length,1);assert.equal(store.state.alertLog.length,1);
 await store.transaction(s=>s.alerts.push({...rule,id:'r3',updated:3}));provider.alertValues=async()=>{throw new Error('feed unavailable')};await monitor.poll();assert.equal(events.length,1);assert.match(monitor.errors.get('BTC-USD:60').error,/feed unavailable/);
 }finally{await monitor.stop();await rm(directory,{recursive:true,force:true});}
});
test('atomic store rolls back failed mutations and continues serial transactions',async()=>{const directory=await mkdtemp(join(tmpdir(),'aureon-store-'));try{const store=await new Store(directory).init();await assert.rejects(store.transaction(s=>{s.users.push({id:'bad'});throw new Error('rollback')}));assert.equal(store.state.users.length,0);await Promise.all(Array.from({length:12},(_,i)=>store.transaction(s=>s.users.push({id:i}))));assert.equal(store.state.users.length,12);assert.equal(JSON.parse(await readFile(store.path)).users.length,12);}finally{await rm(directory,{recursive:true,force:true});}});
test('provider adapters reject arbitrary destinations and invalid external orders before fetch',async()=>{let calls=0;const p=new Providers({fetcher:async()=>{calls++;return response({});},key:'key',secret:'secret'});for(const path of ['https://evil.invalid','//evil.invalid','/products/BTC-USD/../../secret','/products?url=evil'])await assert.rejects(p.coinbase(path));await assert.rejects(p.alpaca('https://api.alpaca.markets/v2/account'));assert.equal(calls,0);for(const change of [{symbol:'../SECRET'},{qty:-1},{qty:Infinity},{client_order_id:''},{type:'liveorder'}])assert.throws(()=>validatePaperOrder({symbol:'AAPL',side:'buy',qty:1,type:'market',time_in_force:'day',client_order_id:'abc',...change}));});
test('equity pagination is exhausted rather than dropping subsequent pages',async()=>{let calls=0;const p=new Providers({key:'key',secret:'secret',fetcher:async(url)=>{calls++;assert.equal(new URL(url).searchParams.get('page_token'),calls===1?null:'next');return response({bars:{AAPL:[{t:calls===1?'2025-01-02T00:00:00Z':'2025-01-03T00:00:00Z',o:100,h:110,l:90,c:105,v:2}]},next_page_token:calls===1?'next':null});}});const r=await p.history({symbol:'AAPL',timeframe:'1Day',start:'2025-01-01'});assert.equal(calls,2);assert.equal(r.bars.length,2);assert.equal(r.truncated,false);});
test('extension schema rejects executable/prototype-shaped values and validates nested studies',()=>{assert.throws(()=>validateExtensions({version:2,studies:[{id:'a',type:'constructor'}]}));assert.throws(()=>validateExtensions({version:2,scriptInputs:{x:{nested:'object'}}}));assert.throws(()=>validateExtensions({version:2,studyTemplates:[{id:'t',name:'bad',studies:[{id:'x',type:'missing'}]}]}));assert.throws(()=>validateExtensions({version:2,session:{open:'25:00',close:'30:00',weekdays:[9]}}));const p=payload();p.extensions.layouts=[{id:'nested',name:'invalid',payload:{}}];const out=validateExtensions({version:2,layouts:[{id:'a',name:'A',payload:p}]});assert.deepEqual(out.layouts[0].payload.extensions.layouts,[]);});
