import test from 'node:test';import assert from 'node:assert/strict';
import {PortfolioBroker,LimitQueueModel,marketImpactBps,optionSettlement,runPortfolioBacktest,MultiCurrencyCash} from '../src/execution-pro.js';
const mark=(broker,price,time=1,liquidity=Infinity)=>broker.tick({symbol:'X',price,time,liquidity});
const broker=options=>{const b=new PortfolioBroker({initial:10000,feeBps:0,slippageBps:0,reserveBufferBps:0,...options});mark(b,100);return b;};
test('pending gross notional is reserved, released on cancel and enforced on amend',()=>{const b=broker();const a=b.submit({symbol:'X',side:'buy',type:'limit',limit:90,quantity:80});assert.equal(b.reserved(),7200);assert.throws(()=>b.submit({symbol:'X',side:'buy',quantity:30}),/reservation/);assert.throws(()=>b.amend(a.id,{quantity:120}),/buying power/);b.cancel(a.id);assert.equal(b.reserved(),0);assert.equal(b.buyingPower(),10000);});
test('FIFO basis and targeted entry-ID exits preserve remaining lot economics',()=>{const b=broker();b.submit({symbol:'X',side:'buy',quantity:10,entryId:'A'});mark(b,100,2);b.submit({symbol:'X',side:'buy',quantity:10,entryId:'B'});mark(b,120,3);assert.equal(b.positions.X.average,110);b.closeEntry('X','A',3);const fill=mark(b,130,4)[0];assert.equal(fill.realized,300);assert.equal(b.positions.X.average,120);assert.equal(b.positions.X.quantity,10);assert.equal(b.cash,9100);assert.equal(b.equity(),10400);assert.equal(b.lots[0].entryId,'B');});
test('partial targeted exits cannot consume another entry lot',()=>{const b=broker();b.submit({symbol:'X',side:'buy',quantity:2,entryId:'A'});mark(b,100,2);b.submit({symbol:'X',side:'buy',quantity:3,entryId:'B'});mark(b,100,3);b.closeEntry('X','A',3);mark(b,101,4,1);mark(b,102,5,10);assert.equal(b.positions.X.quantity,3);assert.equal(b.lots[0].entryId,'B');assert.equal(b.realized,3);});
test('pyramiding accounts for pending and filled entries',()=>{const b=broker({pyramiding:1});b.submit({symbol:'X',side:'buy',quantity:1,entryId:'A'});assert.throws(()=>b.submit({symbol:'X',side:'buy',quantity:1,entryId:'B'}),/Pyramiding/);mark(b,100,2);assert.throws(()=>b.submit({symbol:'X',side:'buy',quantity:1,entryId:'B'}),/Pyramiding/);});
test('split adjusts lots, orders and marks without changing equity or cost',()=>{const b=broker();b.submit({symbol:'X',side:'buy',quantity:10});mark(b,100,2);const o=b.submit({symbol:'X',side:'sell',type:'limit',limit:120,quantity:10,reduceOnly:true}),equity=b.equity();assert.equal(b.corporateAction({id:'split',symbol:'X',time:3,kind:'split',ratio:2}),true);assert.equal(b.positions.X.quantity,20);assert.equal(b.positions.X.average,50);assert.equal(o.quantity,20);assert.equal(o.limit,60);assert.equal(b.equity(),equity);assert.equal(b.corporateAction({id:'split',symbol:'X',time:3,kind:'split',ratio:2}),false);});
test('dividend and borrow funding cashflows are explicit, deterministic events',()=>{const b=broker();b.submit({symbol:'X',side:'sell',quantity:10});mark(b,100,2);b.corporateAction({id:'div',symbol:'X',time:3,kind:'dividend',amount:2});assert.equal(b.cash,10980);const cash=b.accrue(3+31557600,{borrowRate:.1});assert.equal(cash,-100);assert.equal(b.cashEvents.length,2);});
test('portfolio snapshot restores lots and reservations and rejects mismatched quantities',()=>{const b=broker();b.submit({symbol:'X',side:'buy',quantity:2,entryId:'A'});mark(b,100,2);const restored=PortfolioBroker.restore(b.snapshot());assert.equal(restored.equity(),b.equity());assert.equal(restored.lots[0].entryId,'A');const bad=b.snapshot();bad.lots[0].quantity++;assert.throws(()=>PortfolioBroker.restore(bad),/mismatch/);});
test('observed queue consumption honors ahead and finite trade liquidity',()=>{const q=new LimitQueueModel();q.add({id:'L',side:'buy',price:100,quantity:3,ahead:2});assert.deepEqual(q.trade({id:'1',time:1,price:100,size:1,side:'sell'}),[]);const fill=q.trade({id:'2',time:2,price:100,size:3,side:'sell'});assert.equal(fill[0].quantity,2);assert.deepEqual(q.trade({id:'2',time:2,price:100,size:3,side:'sell'}),[]);assert.equal(q.trade({id:'3',time:3,price:99,size:1,side:'sell'})[0].quantity,1);});
test('cash and physical option settlement use signed contracts and explicit multipliers',()=>{const x={right:'call',strike:100,multiplier:100,quantity:2,expiry:100,time:100,spot:110};assert.equal(optionSettlement(x).cashFlow,2000);const physical=optionSettlement({...x,style:'physical',cash:20000});assert.equal(physical.cash,0);assert.equal(physical.underlyingShares,200);const short=optionSettlement({...x,quantity:-1,style:'physical'});assert.equal(short.underlyingShares,-100);assert.equal(short.cash,10000);assert.throws(()=>optionSettlement({...x,time:99}),/Invalid/);});
test('impact is bounded, monotonic and assumption-driven',()=>{assert.equal(marketImpactBps(0,100),0);assert.equal(marketImpactBps(25,100),5);assert.equal(marketImpactBps(1000000,1),500);});
test('advanced backtest routes entry IDs and limit orders causally',()=>{const bars=[100,101,102,103,104].map((c,i)=>({t:60*i,o:c,h:c+1,l:c-1,c,v:100}));const r=runPortfolioBacktest(bars,{feeBps:0,slippageBps:0,commands:[{index:0,id:'A',action:'entry',direction:1,quantity:2},{index:2,id:'A',action:'close'}]});assert.equal(r.trades.length,1);assert.equal(r.trades[0].price,101);assert.equal(r.trades[0].exitPrice,103);assert.equal(r.net,4);});
test('bar magnifier refuses gaps or nonreconciling prints instead of synthesizing history',()=>{const bars=[{t:0,o:100,h:101,l:100,c:101,v:2},{t:60,o:101,h:102,l:101,c:102,v:2}];const ticks=[{time:0,price:100,size:1},{time:20,price:101,size:1},{time:60,price:101,size:1},{time:80,price:102,size:1}];const r=runPortfolioBacktest(bars,{ticks,feeBps:0,slippageBps:0,commands:[{index:0,id:'A',action:'entry',direction:1,quantity:1}]});assert.equal(r.lots[0].price,101);assert.equal(r.net,1);assert.throws(()=>runPortfolioBacktest(bars,{ticks:ticks.slice(0,2)}),/gap/);assert.throws(()=>runPortfolioBacktest(bars,{ticks:ticks.map(t=>({...t,size:2}))}),/reconcile/);});

test('Same-price queue orders consume the external queue once, then our FIFO quantities',()=>{const q=new LimitQueueModel();q.add({id:'a',side:'buy',price:100,quantity:2,ahead:3});q.add({id:'b',side:'buy',price:100,quantity:2,ahead:3});assert.deepEqual(q.trade({id:'t1',t:1,price:100,size:6,side:'sell'}).map(f=>[f.orderId,f.quantity]),[['a',2],['b',1]]);assert.deepEqual(q.trade({id:'t2',t:2,price:100,size:1,side:'sell'}).map(f=>[f.orderId,f.quantity]),[['b',1]]);});
test('Explicitly disabled pending reservations do not silently reduce buying power',()=>{const b=new PortfolioBroker({initial:1000,reserveOrders:false,feeBps:0,slippageBps:0});b.submit({symbol:'X',side:'buy',type:'limit',quantity:5,limit:100},1);assert.equal(b.reserved(),0);assert.equal(b.buyingPower(),1000);});
