import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createAureonServer} from '../server/app.mjs';
import {totp,verifyAudit} from '../server/security-pro.mjs';
import {drawingLevel} from '../server/services-pro.mjs';
import {defaultExtensions} from '../src/workspace-v2.js';
const payload=()=>({application:'Aureon Terminal',version:2,workspace:{version:1,symbol:'BTC-USD',interval:3600,drawings:{},indicators:['ema'],watchlist:['BTC-USD'],style:'candles'},extensions:defaultExtensions()});
test('Private v3 service authentication, MFA, collaboration, notifications and monitoring',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'aureon-services-')),password='safe-fixture-password-2026',network=[];let app,base;
 const fetcher=async(url,o)=>{network.push({url,o});if(url.startsWith('https://api.stlouisfed.org/'))return new Response(JSON.stringify({count:1,observations:[{date:'2020-01-01',value:'2'}]}));if(url==='https://api.resend.com/emails')return new Response(JSON.stringify({id:'fixture'}));throw new Error('Unexpected network fixture: '+url);};
 const start=async configured=>{app=await createAureonServer({root:resolve('.'),dataDir:dir,monitor:false,fetcher,pro:configured?{researchUser:'alice',research:{fredKey:'FRED_FIXTURE_PRIVATE'},moderators:['carol'],delivery:{recipients:{alice:{email:'owner@example.com'}},resendKey:'RESEND_FIXTURE_PRIVATE',emailFrom:'test@example.com'}}:{researchUser:'alice',moderators:['carol']}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+app.server.address().port;};
 const client=()=>({cookie:'',csrf:'',async call(path,{method='GET',body,headers={},csrf=true}={}){const r=await fetch(base+'/v2/'+path,{method,headers:{Origin:base,...(this.cookie?{Cookie:this.cookie}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...(csrf&&this.csrf?{'X-CSRF-Token':this.csrf}:{}),...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,data:await r.json()};},async session(){const r=await this.call('session');this.csrf=r.data.csrf;this.id=r.data.user?.id;return r;},async register(username){const r=await this.call('register',{method:'POST',body:{username,password}});assert.equal(r.status,200,JSON.stringify(r.data));await this.session();},async login(username,code){const r=await this.call('login',{method:'POST',body:{username,password,code}});if(r.status===200)await this.session();return r;}});
 const alice=client(),bob=client(),carol=client(),anonymous=client();let sharedRoom,library,secret,codes;
 try{
 await start(false);await alice.register('alice');await bob.register('bob');await carol.register('carol');
 await t.test('Configured operator role names cannot be claimed by registration during a running process',async()=>{assert.deepEqual((await alice.call('pro/capabilities')).data.research,{});assert.equal((await carol.call('pro/moderation')).status,403);});
 await app.close();await start(true);for(const c of[alice,bob,carol])await c.session();
 await t.test('Pro API needs authentication and CSRF; private implementation and vault are not served',async()=>{assert.equal((await anonymous.call('pro/security')).status,401);assert.equal((await alice.call('pro/privacy',{method:'POST',body:{allowDM:true},csrf:false})).status,403);for(const path of['/server/security-pro.mjs','/.aureon-data/vault.key','/.env'])assert.equal((await fetch(base+path)).status,404);assert.equal((await fetch(base+'/sw.js')).status,200);assert.equal((await fetch(base+'/manifest.webmanifest')).status,200);});
 await t.test('Configured owner alone can query research and no API secret reaches responses',async()=>{assert.equal((await bob.call('pro/research/macro?series=GDP')).status,403);const r=await alice.call('pro/research/macro?series=GDP&vintage=2020-02-01');assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.items[0].value,2);assert.ok(!JSON.stringify(r.data).includes('PRIVATE'));});
 await t.test('Notifications require explicit consent and operator-bound recipient; user body cannot reroute',async()=>{assert.equal((await alice.call('pro/channels',{method:'POST',body:{type:'email'}})).status,400);assert.equal((await bob.call('pro/channels',{method:'POST',body:{type:'email',consent:true}})).status,400);const r=await alice.call('pro/channels',{method:'POST',body:{type:'email',consent:true,to:'attacker@example.com'}});assert.equal(r.status,201,JSON.stringify(r.data));assert.equal((await bob.call('pro/channels')).data.items.length,0);assert.equal((await bob.call('pro/channels/'+r.data.id,{method:'DELETE'})).status,404);});
 await t.test('Library versions are immutable, private by default and public only by explicit publication',async()=>{let r=await alice.call('pro/libraries',{method:'POST',body:{name:'SecretStudy',version:1,source:'export f(x) => x * 2'}});assert.equal(r.status,201);assert.equal((await bob.call('pro/libraries/alice/SecretStudy/1')).status,404);r=await alice.call('pro/libraries',{method:'POST',body:{name:'PublicStudy',version:1,source:'export f(x) => x * 2',public:true}});assert.equal(r.status,201);library=r.data.id;assert.equal((await bob.call('pro/libraries/'+library)).status,200);assert.equal((await alice.call('pro/libraries',{method:'POST',body:{name:'PublicStudy',version:1,source:'export f(x) => 999',public:true}})).status,409);});
 await t.test('Shared rooms isolate membership and concurrent revision writes have one winner',async()=>{const r=await alice.call('pro/rooms',{method:'POST',body:{name:'Shared',members:[bob.id],payload:payload()}});assert.equal(r.status,201,JSON.stringify(r.data));sharedRoom=r.data.id;assert.equal((await carol.call('pro/rooms/'+sharedRoom)).status,404);const writes=await Promise.all([alice,bob].map(c=>c.call('pro/rooms/'+sharedRoom,{method:'PUT',headers:{'If-Match':'1'},body:{payload:payload()}})));assert.deepEqual(writes.map(r=>r.status).sort(),[200,409]);assert.equal((await bob.call('pro/rooms/'+sharedRoom)).data.revision,2);assert.equal((await bob.call('pro/rooms/'+sharedRoom,{method:'DELETE'})).status,403);});
 await t.test('Direct messages are default-deny; recipient opt-in and bilateral blocks are enforced',async()=>{assert.equal((await alice.call('pro/messages',{method:'POST',body:{to:bob.id,text:'hello'}})).status,403);assert.equal((await bob.call('pro/privacy',{method:'POST',body:{allowDM:true}})).status,200);assert.equal((await alice.call('pro/messages',{method:'POST',body:{to:bob.id,text:'hello'}})).status,201);assert.equal((await carol.call('pro/messages')).data.items.length,0);await bob.call('pro/block/'+alice.id,{method:'POST'});assert.equal((await alice.call('pro/messages',{method:'POST',body:{to:bob.id,text:'blocked'}})).status,403);assert.equal((await alice.call('pro/follow/'+bob.id,{method:'POST'})).status,403);});
 await t.test('Moderator role is operator-bound and reports can hide public library versions',async()=>{let r=await bob.call('pro/reports',{method:'POST',body:{kind:'library',id:library,reason:'test moderation'}});assert.equal(r.status,201);const id=r.data.id;assert.equal((await bob.call('pro/moderation')).status,403);assert.equal((await carol.call('pro/moderation',{method:'POST',body:{id,action:'hide'}})).status,200);assert.equal((await bob.call('pro/libraries/'+library)).status,404);});
 await t.test('MFA enrollment requires password; secret encrypted and enrollment consumes the TOTP counter',async()=>{assert.equal((await alice.call('pro/security/enroll',{method:'POST',body:{password:'wrong'}})).status,401);const r=await alice.call('pro/security/enroll',{method:'POST',body:{password}});assert.equal(r.status,200,JSON.stringify(r.data));secret=r.data.secret;assert.match(r.data.uri,/otpauth:/);const code=totp(secret),confirm=await alice.call('pro/security/confirm',{method:'POST',body:{password,code}});assert.equal(confirm.status,200,JSON.stringify(confirm.data));codes=confirm.data.recoveryCodes;assert.equal(codes.length,10);assert.ok(!(await readFile(join(dir,'state.json'),'utf8')).includes(secret));assert.equal((await client().login('alice',code)).status,401);});
 await t.test('Recovery codes are one-use, MFA login is mandatory and session response hides credentials',async()=>{const other=client();assert.equal((await other.login('alice')).status,401);assert.equal((await other.login('alice',codes[0])).status,200);assert.equal((await client().login('alice',codes[0])).status,401);assert.equal((await alice.call('pro/security')).data.recoveryRemaining,9);const session=(await other.session()).data;assert.ok(!JSON.stringify(session).includes(secret));assert.ok(!JSON.stringify(session).includes('hash'));});
 await t.test('Current session can revoke other sessions without invalidating itself',async()=>{const other=client();assert.equal((await other.login('alice',codes[1])).status,200);assert.equal((await alice.call('pro/security/revoke',{method:'POST',body:{password}})).status,200);assert.equal((await other.call('pro/security')).status,401);assert.equal((await alice.call('pro/security')).status,200);});
 await t.test('Actual isolated script endpoint calculates and rejects unknown globals',async()=>{const bars=Array.from({length:3},(_,i)=>({t:100+i*60,o:i+1,h:i+1,l:i+1,c:i+1,v:1}));const r=await alice.call('pro/scripts/run',{method:'POST',body:{source:'plot(close * 2)',bars}});assert.equal(r.status,200,JSON.stringify(r.data));assert.deepEqual(r.data.plots[0].values,[4,6]);assert.notEqual((await alice.call('pro/scripts/run',{method:'POST',body:{source:'plot(globalThis)',bars}})).status,200);});
 await t.test('Drawing and server-script monitors establish baseline, fire once and durably enqueue delivery',async()=>{let barTime=1200,price=99;app.proServices.providers.alertValues=async()=>({barTime,time:barTime+60,values:{close:price},bars:[{t:barTime,o:price,h:price,l:price,c:price,v:1}]});const rule={symbol:'BTC-USD',interval:60,direction:'above',once:true};let r=await alice.call('pro/monitors',{method:'POST',body:{...rule,kind:'drawing',drawing:{type:'hline',points:[{t:1,p:100}]}}});assert.equal(r.status,201,JSON.stringify(r.data));r=await alice.call('pro/monitors',{method:'POST',body:{...rule,kind:'script',source:'plot(close)',threshold:100}});assert.equal(r.status,201);await app.proServices.poll();assert.equal(app.store.state.pro.monitorLog.length,0);barTime+=60;price=101;await app.proServices.poll();assert.equal(app.store.state.pro.monitorLog.length,2);assert.equal(app.store.state.pro.outbox.length,2);assert.equal(app.store.state.pro.monitors.filter(r=>r.active).length,0);await app.proServices.poll();assert.equal(app.store.state.pro.monitorLog.length,2);assert.equal((await bob.call('pro/monitors')).data.log.length,0);await app.proServices.delivery.flush();assert.equal(app.store.state.pro.outbox.filter(j=>j.status==='sent').length,2);for(const n of network.filter(n=>n.url==='https://api.resend.com/emails'))assert.deepEqual(JSON.parse(n.o.body).to,['owner@example.com']);});
 await t.test('Deleted monitor cannot fire after an asynchronous provider read returns',async()=>{const r=await alice.call('pro/monitors',{method:'POST',body:{symbol:'BTC-USD',interval:60,kind:'drawing',drawing:{type:'hline',points:[{t:1,p:100}]}}});let release;app.proServices.providers.alertValues=()=>new Promise(resolve=>release=resolve);const polling=app.proServices.poll();for(let attempt=0;!release&&attempt<200;attempt++)await new Promise(resolve=>setTimeout(resolve,5));assert.ok(release,'provider read must begin after durable lease acquisition');await alice.call('pro/monitors/'+r.data.id,{method:'DELETE'});release({barTime:2000,time:2060,values:{close:102}});await polling;assert.equal(app.store.state.pro.monitors.some(x=>x.id===r.data.id),false);assert.equal(app.store.state.pro.monitorLog.length,2);});
 await t.test('Real-money HTTP routes require HTTPS and never send on this default-disabled server',async()=>{const before=network.length;assert.equal((await alice.call('pro/live/preview',{method:'POST',body:{symbol:'AAPL',side:'buy',quantity:1,limit:100}})).status,403);assert.equal((await alice.call('pro/capabilities')).data.live.enabled,false);assert.equal(network.length,before);});
 await t.test('Audit verifies and restart retains MFA, workspace revisions and delivered outbox',async()=>{assert.equal(verifyAudit(app.store.state.pro.audit,app.store.state.pro.auditAnchor),true);await app.close();await start(true);assert.equal((await alice.call('pro/security')).data.mfa,true);assert.equal((await bob.call('pro/rooms/'+sharedRoom)).data.revision,2);assert.equal(app.store.state.pro.outbox.filter(j=>j.status==='sent').length,2);assert.equal((await client().login('alice',codes[0])).status,401);});
 }finally{if(app)await app.close();await rm(dir,{recursive:true,force:true});}
});
test('Drawing price alerts respect time domains and reject vertical/unsupported geometry',()=>{assert.equal(drawingLevel({type:'trend',points:[{t:10,p:100},{t:20,p:120}]},15),110);assert.ok(Number.isNaN(drawingLevel({type:'trend',points:[{t:10,p:100},{t:20,p:120}]},21)));assert.equal(drawingLevel({type:'ray',points:[{t:10,p:100},{t:20,p:120}]},30),140);assert.ok(Number.isNaN(drawingLevel({type:'horizontalray',points:[{t:10,p:100}]},9)));assert.throws(()=>drawingLevel({type:'trend',points:[{t:10,p:100},{t:10,p:120}]},10),/Vertical/);assert.throws(()=>drawingLevel({type:'rectangle',points:[]},1));});
