import test from 'node:test';
import assert from 'node:assert/strict';
import {DrawingDocument,DrawingReplica} from '../src/drawing-crdt.js';
import {runScriptPortfolioBacktest} from '../src/execution-pro.js';
import {performJob} from '../src/jobs.js';
const drawing=(id='line')=>({id,type:'hline',points:[{t:100,p:10}],color:'#ff0000',width:1,locked:false});
const fixture=()=>Array.from({length:30},(_,i)=>({t:1000+i*60,o:100+i,h:102+i,l:99+i,c:101+i,v:100}));
function replicas(){const a=new DrawingReplica('alice'),seed=a.applySnapshot([],[drawing()]);return [a,new DrawingReplica('bob',a.document.snapshot()),seed];}
test('drawing CRDT merges disjoint properties without overwriting remote edits',()=>{const[a,b,seed]=replicas();const x=a.applySnapshot(a.drawings,[{...a.drawings[0],color:'#00ff00'}]),y=b.applySnapshot(b.drawings,[{...b.drawings[0],width:3}]);a.merge(y);b.merge(x);assert.deepEqual(a.drawings,b.drawings);assert.equal(a.drawings[0].color,'#00ff00');assert.equal(a.drawings[0].width,3);assert.equal(a.merge([...seed,...x,...y]),0);});
test('drawing selective undo preserves another author later property edit',()=>{const[a,b]=replicas();const x=a.applySnapshot(a.drawings,[{...a.drawings[0],color:'#00ff00'}]);b.merge(x);const y=b.applySnapshot(b.drawings,[{...b.drawings[0],color:'#0000ff'}]);a.merge(y);const u=a.undo();b.merge(u);assert.equal(a.drawings[0].color,'#0000ff');assert.deepEqual(a.drawings,b.drawings);b.merge(a.redo());assert.equal(b.drawings[0].color,'#0000ff');});
test('drawing undo delivered before its target converges',()=>{const[a,,seed]=replicas();const x=a.applySnapshot(a.drawings,[{...a.drawings[0],width:4}]),u=a.undo();const c=new DrawingDocument();c.merge(u);c.merge(x);c.merge(seed);assert.deepEqual(c.materialize(),a.drawings);});
test('drawing delete does not resurrect under concurrent property update',()=>{const[a,b]=replicas(),del=a.applySnapshot(a.drawings,[]),edit=b.applySnapshot(b.drawings,[{...b.drawings[0],width:2}]);a.merge(edit);b.merge(del);assert.deepEqual(a.drawings,[]);assert.deepEqual(b.drawings,[]);b.merge(a.undo());assert.equal(b.drawings[0].width,2);});
test('drawing equivocation and invalid batch reject atomically',()=>{const[a]=replicas(),snapshot=a.document.snapshot();assert.throws(()=>a.merge([{...snapshot.operations[0],fields:{$alive:false}}]),/identity/);assert.throws(()=>a.merge([{kind:'set',actor:'x',clock:100,drawing:'x',fields:{$alive:true}}, {kind:'set',actor:'x',clock:101,drawing:'x',fields:{constructor:1}}]));assert.deepEqual(a.document.snapshot(),snapshot);});
test('drawing document rejects arbitrary tool, invalid geometry and forged undo targets',()=>{for(const fields of [{type:'invented'},{points:[{t:0,p:Infinity}]},{width:200},{$alive:'true'}])assert.throws(()=>new DrawingDocument({version:1,operations:[{kind:'set',actor:'a',clock:1,drawing:'x',fields}]}));assert.throws(()=>new DrawingDocument({version:1,operations:[{kind:'toggle',actor:'a',clock:1,target:2,enabled:false}]}));});
test('drawing operations converge over deterministic shuffled delivery and duplicated batches',()=>{const[a,b,seed]=replicas();const all=[...seed];for(let i=0;i<15;i++){const r=i%2?a:b;const edit=r.applySnapshot(r.drawings,[{...r.drawings[0],width:1+i%9}]);all.push(...edit);if(i%3===0)all.push(...r.undo());if(i%4===0){a.merge(all);b.merge(all);}}const expected=new DrawingDocument({version:1,operations:all}).materialize();for(let seed=1;seed<=20;seed++){let state=seed;const shuffled=[...all];for(let i=shuffled.length-1;i>0;i--){state=(state*1664525+1013904223)>>>0;const j=state%(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}const d=new DrawingDocument();for(const op of shuffled)d.merge([op,op]);assert.deepEqual(d.materialize(),expected);}});
test('drawing capacity rejects without forgetting undo history',()=>{const r=new DrawingReplica('a',undefined,{maxOperations:1});r.applySnapshot([],[drawing()]);const before=r.document.snapshot();assert.throws(()=>r.undo(),/capacity/);assert.deepEqual(r.document.snapshot(),before);assert.equal(r.undoStack.length,1);});
const strategy=`strategy("Position feedback")
if strategy.position_size == 0 and bar_index == 1
    strategy.entry("entry", strategy.long, qty=2)
if strategy.position_size > 0 and bar_index == 5
    strategy.close("entry")
plot(strategy.position_size, "Position")
plot(strategy.equity, "Equity")
plot(strategy.closedtrades, "Closed")`;
test('strategy position feedback observes next-open fills and next-open exits',()=>{const bars=fixture(),r=runScriptPortfolioBacktest(bars,strategy,{feeBps:0,slippageBps:0});const p=[...r.script.plots[0].values];assert.deepEqual(p.slice(0,8),[0,0,2,2,2,2,0,0]);assert.equal(r.trades.length,1);assert.equal(r.trades[0].price,bars[2].o);assert.equal(r.trades[0].exitPrice,bars[6].o);assert.equal(r.script.plots[2].values[6],1);});
test('strategy equity feedback reconciles account and supports history references',()=>{const bars=fixture(),r=runScriptPortfolioBacktest(bars,strategy,{feeBps:5,slippageBps:3});assert.equal(r.script.plots[1].values.at(-1),r.equity.at(-1).value);const h=runScriptPortfolioBacktest(bars,strategy+'\nplot(strategy.position_size[1], "Previous")');assert.equal(h.script.plots[3].values[2],0);assert.equal(h.script.plots[3].values[3],2);});
test('strategy feedback and economics are invariant to arbitrary future perturbations',()=>{const bars=fixture(),whole=runScriptPortfolioBacktest(bars,strategy);for(const n of [3,6,10,20]){const prefix=runScriptPortfolioBacktest(bars.slice(0,n),strategy);assert.deepEqual([...prefix.script.plots[0].values],[...whole.script.plots[0].values.slice(0,n)]);assert.deepEqual(prefix.equity,whole.equity.slice(0,n));}});
test('worker portfolio path uses causal script feedback, not precomputed flat positions',()=>{const r=performJob('portfolio',fixture(),{source:strategy});assert.equal(r.trades.length,1);assert.equal(r.script.plots[0].values[3],2);});
test('strategy partial bar never executes its own signal',()=>{const bars=fixture().slice(0,3);bars[2].partial=true;const r=runScriptPortfolioBacktest(bars,strategy);assert.equal(r.orders.length,0);assert.equal(r.equity.length,2);});
test('holdout evaluates warmup but initializes its account flat',()=>{const r=runScriptPortfolioBacktest(fixture(),strategy,{start:3,end:10});assert.equal(r.trades.length,0);assert.equal(r.equity.length,7);});
test('shared drawing scalar properties reject rendering-hostile values atomically',()=>{for(const fields of [{text:{}},{name:[]},{group:true},{opacity:2},{quantity:-1},{z:0.5},{ratios:[NaN]},{color:'#fffff'}])assert.throws(()=>new DrawingDocument({version:1,operations:[{kind:'set',actor:'a',clock:1,drawing:'x',fields}]}));});
test('both scripted worker backtest entry points use causal feedback',()=>{const options={source:strategy},a=performJob('backtest',fixture(),options),b=performJob('portfolio',fixture(),options);assert.deepEqual(a.equity,b.equity);assert.equal(a.script.plots[0].values[3],2);});
