/** Opt-in durable alert delivery. Arbitrary HTTP proxying is never offered:
 * webhooks are operator-defined aliases; browser-push destinations are restricted
 * to known push services. DNS is checked and pinned to a public IPv4 address.
 */
import https from 'node:https';
import {resolve4} from 'node:dns/promises';
import {createECDH,randomBytes,hkdfSync,createCipheriv,createPrivateKey,sign,createHmac,randomUUID} from 'node:crypto';
import {boundedJSON} from './research-pro.mjs';
const bad=message=>Object.assign(new Error(message),{status:400});
export function publicIPv4(ip){if(!/^\d{1,3}(?:\.\d{1,3}){3}$/.test(ip))return false;const n=ip.split('.').map(Number);if(n.some(x=>x>255))return false;const[a,b,c]=n;return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&(b===168||b===0||b===2||b===88&&c===99)||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19||b===51&&c===100)||a===203&&b===0&&c===113);}
export function validateHTTPS(value){let u;try{u=new URL(value);}catch{throw bad('Invalid HTTPS destination');}if(u.protocol!=='https:'||u.port&&u.port!=='443'||u.username||u.password||u.hash||u.href.length>3000||!/^([a-z0-9-]+\.)+[a-z]{2,}$/i.test(u.hostname))throw bad('HTTPS public DNS destination with port 443 required');return u;}
export function validatePush(raw){const u=validateHTTPS(raw?.endpoint);if(!['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].includes(u.hostname)&&!u.hostname.endsWith('.push.apple.com'))throw bad('Unsupported browser push service');const publicKey=Buffer.from(String(raw.keys?.p256dh||''),'base64url'),auth=Buffer.from(String(raw.keys?.auth||''),'base64url');if(publicKey.length!==65||publicKey[0]!==4||auth.length!==16)throw bad('Invalid browser push keys');try{const check=createECDH('prime256v1');check.generateKeys();check.computeSecret(publicKey);}catch{throw bad('Invalid browser public key');}return{endpoint:u.href,keys:{p256dh:publicKey.toString('base64url'),auth:auth.toString('base64url')}};}
export async function pinnedPost(destination,{headers={},body,lookup=resolve4,timeout=12000}={}){const u=validateHTTPS(destination),addresses=await lookup(u.hostname);if(!addresses.length||!addresses.every(publicIPv4))throw bad('Destination DNS does not resolve exclusively to public IPv4');const address=addresses[0];return new Promise((resolve,reject)=>{const req=https.request(u,{method:'POST',headers:{...headers,'Content-Length':Buffer.byteLength(body)},lookup:(_h,o,cb)=>o.all?cb(null,[{address,family:4}]):cb(null,address,4),servername:u.hostname,timeout},res=>{res.resume();res.on('end',()=>{if(res.statusCode<200||res.statusCode>=300)reject(Object.assign(new Error('Delivery HTTP '+res.statusCode),{status:res.statusCode}));else resolve({status:res.statusCode});});});const deadline=setTimeout(()=>req.destroy(new Error('Delivery deadline exceeded')),timeout);req.on('close',()=>clearTimeout(deadline));req.on('timeout',()=>req.destroy(new Error('Delivery timed out')));req.on('error',reject);req.end(body);});}
export function newVapid(){const ecdh=createECDH('prime256v1');ecdh.generateKeys();return{publicKey:ecdh.getPublicKey().toString('base64url'),privateKey:ecdh.getPrivateKey().toString('base64url')};}
export function pushRequest(subscription,payload,vapid,{subject,time=Date.now(),privateKey,salt=randomBytes(16)}={}){const valid=validatePush(subscription),ua=Buffer.from(valid.keys.p256dh,'base64url'),auth=Buffer.from(valid.keys.auth,'base64url'),message=Buffer.from(JSON.stringify(payload));if(message.length>3000)throw bad('Push payload exceeds 3000 bytes');if(!/^mailto:[^\s@]+@[^\s@]+$/.test(subject||''))throw bad('VAPID contact email required');if(salt.length!==16)throw bad('Invalid push salt');const ecdh=createECDH('prime256v1');if(privateKey)ecdh.setPrivateKey(privateKey);else ecdh.generateKeys();const pub=ecdh.getPublicKey(),secret=ecdh.computeSecret(ua),ikm=Buffer.from(hkdfSync('sha256',secret,auth,Buffer.concat([Buffer.from('WebPush: info\0'),ua,pub]),32)),key=Buffer.from(hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: aes128gcm\0'),16)),nonce=Buffer.from(hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: nonce\0'),12)),cipher=createCipheriv('aes-128-gcm',key,nonce),header=Buffer.alloc(21);salt.copy(header);header.writeUInt32BE(4096,16);header[20]=65;const body=Buffer.concat([header,pub,cipher.update(Buffer.concat([message,Buffer.from([2])])),cipher.final(),cipher.getAuthTag()]);const vk=Buffer.from(vapid.publicKey,'base64url'),jwk={kty:'EC',crv:'P-256',x:vk.subarray(1,33).toString('base64url'),y:vk.subarray(33).toString('base64url'),d:vapid.privateKey},jwtHeader=Buffer.from(JSON.stringify({typ:'JWT',alg:'ES256'})).toString('base64url'),claims=Buffer.from(JSON.stringify({aud:new URL(valid.endpoint).origin,exp:Math.floor(time/1000)+43200,sub:subject})).toString('base64url'),unsigned=jwtHeader+'.'+claims,signature=sign('sha256',Buffer.from(unsigned),{key:createPrivateKey({key:jwk,format:'jwk'}),dsaEncoding:'ieee-p1363'}).toString('base64url');return{body,headers:{Authorization:`vapid t=${unsigned}.${signature}, k=${vapid.publicKey}`,'Content-Encoding':'aes128gcm','Content-Type':'application/octet-stream',TTL:'300'}};}
export function enqueueDelivery(state,userId,event){const pro=state.pro;if(!pro)return;const channels=pro.channels.filter(c=>c.userId===userId&&c.active);for(const c of channels){const id=event.id+':'+c.id;if(pro.outbox.some(x=>x.id===id))continue;if(pro.outbox.filter(x=>!['sent','failed'].includes(x.status)).length>=5000)break;pro.outbox.push({id,userId,channelId:c.id,event:{id:event.id,time:event.time,message:String(event.message||'Alert').slice(0,1000),symbol:String(event.symbol||'').slice(0,40)},status:'pending',attempts:0,nextAt:Date.now(),created:Date.now()});}if(pro.outbox.length>10000){const active=pro.outbox.filter(x=>!['sent','failed'].includes(x.status)),done=pro.outbox.filter(x=>['sent','failed'].includes(x.status));pro.outbox=[...done.slice(-(10000-active.length)),...active];}}
export class DeliveryQueue {
  constructor(store,{fetcher=fetch,post=pinnedPost,recipients={},webhooks={},resendKey='',emailFrom='',twilioSid='',twilioToken='',smsFrom='',vapid=null,pushSubject=''}={}){Object.assign(this,{store,fetcher,post,recipients,webhooks,resendKey,emailFrom,twilioSid,twilioToken,smsFrom,vapid,pushSubject});this.busy=false;for(const w of Object.values(webhooks)){validateHTTPS(w.url);if(typeof w.username!=='string'||typeof w.secret!=='string'||w.secret.length<32)throw bad('Webhook owner and at least 32-character signing secret required');}}
  capabilities(username){const r=this.recipients[username]||{};return{email:!!(r.email&&this.resendKey&&this.emailFrom),sms:!!(r.sms&&this.twilioSid&&this.twilioToken&&this.smsFrom),webhooks:Object.keys(this.webhooks).filter(k=>this.webhooks[k].username===username),push:!!(this.vapid&&this.pushSubject),pushPublicKey:this.vapid?.publicKey||null};}
  async send(channel,event){if(channel.type==='push'){const request=pushRequest(channel.subscription,{title:'Aureon alert',body:event.message,tag:event.id},this.vapid,{subject:this.pushSubject});return this.post(channel.subscription.endpoint,request);}const recipient=this.recipients[channel.username]||{};
    if(channel.type==='email'){if(!recipient.email||!this.resendKey||!this.emailFrom)throw bad('Email channel no longer configured');return boundedJSON(this.fetcher,'https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+this.resendKey,'Content-Type':'application/json','Idempotency-Key':'aureon/'+event.id+'/'+channel.id},body:JSON.stringify({from:this.emailFrom,to:[recipient.email],subject:'Aureon alert: '+event.symbol,text:event.message})});}
    if(channel.type==='sms'){if(!recipient.sms||!/^AC[a-f\d]{32}$/i.test(this.twilioSid)||!this.twilioToken)throw bad('SMS channel no longer configured');const params=new URLSearchParams({From:this.smsFrom,To:recipient.sms,Body:event.symbol+' '+event.message});return boundedJSON(this.fetcher,'https://api.twilio.com/2010-04-01/Accounts/'+this.twilioSid+'/Messages.json',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(this.twilioSid+':'+this.twilioToken).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});}
    if(channel.type==='webhook'){const w=this.webhooks[channel.alias];if(!w||w.username!==channel.username)throw bad('Webhook channel no longer configured');const body=Buffer.from(JSON.stringify(event)),timestamp=String(Math.floor(Date.now()/1000)),signature=createHmac('sha256',w.secret).update(timestamp+'.').update(body).digest('hex');return this.post(w.url,{body,headers:{'Content-Type':'application/json','X-Aureon-Id':event.id,'X-Aureon-Time':timestamp,'X-Aureon-Signature':'sha256='+signature}});}throw bad('Unsupported notification channel');
  }
  async flush(){if(this.busy)return;this.busy=true;try{for(let count=0;count<20;count++){if(!this.store.state.pro.outbox.some(j=>['pending','sending'].includes(j.status)&&j.nextAt<=Date.now()))break;const item=await this.store.transaction(s=>{const job=s.pro.outbox.find(j=>['pending','sending'].includes(j.status)&&j.nextAt<=Date.now());if(!job)return null;job.status='sending';job.attempts++;job.nextAt=Date.now()+60000;return job;});if(!item)break;const channel=this.store.state.pro.channels.find(c=>c.id===item.channelId&&c.userId===item.userId&&c.active);let error;try{if(!channel)throw bad('Channel disabled or deleted');await this.send(channel,item.event);}catch(e){error=e;}await this.store.transaction(s=>{const job=s.pro.outbox.find(j=>j.id===item.id);if(!job)return;if(!error){job.status='sent';job.sent=Date.now();}else{job.error=String(error.message).slice(0,200);job.status=job.attempts>=5||!channel||[400,401,403,404,410].includes(error.status)?'failed':'pending';job.nextAt=Date.now()+Math.min(3600000,10000*2**job.attempts);if([404,410].includes(error.status)&&channel?.type==='push'){const c=s.pro.channels.find(c=>c.id===channel.id);if(c)c.active=false;}}});}}finally{this.busy=false;}}
  start(){this.timer=setInterval(()=>this.flush().catch(()=>{}),5000);this.timer.unref?.();}
  async close(){clearInterval(this.timer);while(this.busy)await new Promise(r=>setTimeout(r,10));}
}
