/** Separately enabled real-money adapter. No script/alert can invoke this class.
 * Default disabled. Fixed Alpaca production host, pre-existing owner, MFA,
 * HTTPS, whole-share long-only DAY limit orders, explicit per-order approval.
 * An uncertain submission is never retried automatically. Reconcile by client ID.
 */
import {randomUUID} from 'node:crypto';
import {boundedJSON} from './research-pro.mjs';
import {audit} from './security-pro.mjs';
const fail=(status,message)=>Object.assign(new Error(message),{status});
export class LiveGateway {
  constructor(store,{enabled=false,key='',secret='',owner='',maxNotional=1000,dailyNotional=5000,feed='iex',fetcher=fetch,now=Date.now}={}){Object.assign(this,{store,key,secret,maxNotional,dailyNotional,feed,fetcher,now});if(!Number.isFinite(maxNotional)||maxNotional<=0||maxNotional>100000||!Number.isFinite(dailyNotional)||dailyNotional<maxNotional||dailyNotional>1000000||!['iex','sip'].includes(feed))throw fail(400,'Invalid live risk limits/feed');this.enabled=enabled===true;this.ownerId=store.state.users.find(u=>u.username===owner)?.id;}
  allowed(user){return this.enabled&&!!(this.key&&this.secret&&this.ownerId)&&user?.id===this.ownerId&&!!user.mfa;}
  check(user){if(!this.allowed(user))throw fail(403,'Real-money routing is disabled or requires the configured MFA owner');}
  get headers(){return{'APCA-API-KEY-ID':this.key,'APCA-API-SECRET-KEY':this.secret,Accept:'application/json'};}
  async api(path,{method='GET',body}={}){if(!/^\/v2\/(account|positions|orders(?:\?status=open&limit=500|:by_client_order_id\?client_order_id=[A-Za-z0-9_-]{1,48}|\/[a-f\d-]{36})?)$/.test(path))throw fail(400,'Unsupported live endpoint');return boundedJSON(this.fetcher,'https://api.alpaca.markets'+path,{method,headers:{...this.headers,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});}
  async risk(order){const [account,positions,pending,quoteData]=await Promise.all([this.api('/v2/account'),this.api('/v2/positions'),this.api('/v2/orders?status=open&limit=500'),boundedJSON(this.fetcher,'https://data.alpaca.markets/v2/stocks/'+order.symbol+'/quotes/latest?feed='+this.feed,{headers:this.headers})]);if(account.status!=='ACTIVE'||account.trading_blocked||account.account_blocked||account.trade_suspended_by_user)throw fail(409,'Live account is not enabled for trading');if(!Array.isArray(positions)||!Array.isArray(pending)||pending.length>=500)throw fail(409,'Cannot verify complete open-order risk');const quote=quoteData.quote,age=this.now()-Date.parse(quote?.t);if(!Number.isFinite(age)||age< -1000||age>15000||![+quote?.ap,+quote?.bp].every(x=>Number.isFinite(x)&&x>0)||+quote.ap<+quote.bp)throw fail(409,'Fresh non-crossed bid/ask required (15 seconds)');const quantity=+order.qty,limit=+order.limit_price,notional=quantity*limit;if(notional>this.maxNotional)throw fail(409,'Per-order live notional limit exceeded');if(order.side==='buy'){if(!Number.isFinite(+account.cash)||+account.cash<notional||+account.buying_power<notional)throw fail(409,'Insufficient live cash/buying power');}else{const held=positions.find(p=>p.symbol===order.symbol),reserved=pending.filter(o=>o.symbol===order.symbol&&o.side==='sell').reduce((n,o)=>n+Math.max(0,+o.qty-(+o.filled_qty||0)),0);if(!Number.isFinite(reserved)||!(+held?.qty-reserved>=quantity))throw fail(409,'Short selling is disabled; unreserved long shares required');}if(Math.abs(limit/(order.side==='buy'?+quote.ap:+quote.bp)-1)>.2)throw fail(409,'Limit price deviates over 20% from the current quote');return{bid:+quote.bp,ask:+quote.ap,time:quote.t,feed:this.feed,notional,currency:'USD'};}
  async preview(user,b){this.check(user);if(!/^[A-Z][A-Z0-9.]{0,14}$/.test(b.symbol||'')||!['buy','sell'].includes(b.side)||!Number.isInteger(b.quantity)||b.quantity<1||b.quantity>10000||!Number.isFinite(b.limit)||b.limit<=0||Math.abs(b.limit*100-Math.round(b.limit*100))>1e-7)throw fail(400,'Whole-share equity DAY limit order with cent-aligned positive price required');const id=randomUUID(),order={symbol:b.symbol,side:b.side,qty:String(b.quantity),type:'limit',time_in_force:'day',limit_price:b.limit.toFixed(2),extended_hours:false,client_order_id:'aureon-live-'+id},quote=await this.risk(order),phrase=`LIVE ${order.side.toUpperCase()} ${order.qty} ${order.symbol} @ ${order.limit_price}`,p={id,userId:user.id,order,quote,phrase,status:'preview',created:this.now(),expires:this.now()+60000};await this.store.transaction(s=>{s.pro.live??=[];s.pro.live=s.pro.live.filter(x=>x.created>this.now()-31*86400000);if(s.pro.live.filter(x=>x.status==='preview'&&x.expires>this.now()).length>=20)throw fail(429,'Too many active order previews');s.pro.live.push(p);audit(s,user.id,'live.preview',id);});return p;}
  async confirm(user,id,phrase,{authorize=()=>{}}={}){this.check(user);const proposal=this.store.state.pro.live?.find(x=>x.id===id&&x.userId===user.id);if(!proposal||proposal.status!=='preview'||proposal.expires<this.now()||proposal.phrase!==phrase)throw fail(409,'Preview missing, expired, used, or confirmation phrase mismatched');await this.risk(proposal.order);await this.store.transaction(s=>{const currentUser=s.users.find(u=>u.id===user.id);this.check(currentUser);const p=s.pro.live.find(x=>x.id===id&&x.userId===user.id);if(!p||p.status!=='preview'||p.expires<this.now())throw fail(409,'Preview was already consumed');const day=new Date(this.now()).toISOString().slice(0,10),used=s.pro.live.filter(x=>x.status!=='preview'&&new Date(x.attempted||0).toISOString().startsWith(day)).reduce((n,x)=>n+x.quote.notional,0);if(used+p.quote.notional>this.dailyNotional)throw fail(409,'Daily live attempted-notional cap exceeded');authorize(s,currentUser);p.status='submitting';p.attempted=this.now();audit(s,user.id,'live.submit-attempt',id);});let result,error;try{result=await this.api('/v2/orders',{method:'POST',body:proposal.order});if(result.client_order_id!==proposal.order.client_order_id)throw new Error('Provider order identity mismatch');}catch(e){error=e;}await this.store.transaction(s=>{const p=s.pro.live.find(x=>x.id===id);p.status=error?'uncertain':'submitted';p.providerId=result?.id||null;p.providerStatus=result?.status||null;p.error=error?'Provider response uncertain. Reconcile by client_order_id; do not resubmit.':null;audit(s,user.id,'live.'+p.status,id);});if(error)throw fail(502,'Live submission outcome is uncertain. Do not retry: reconcile using its client order ID.');return{proposalId:id,id:result.id,clientOrderId:result.client_order_id,status:result.status};}
  async reconcile(user,id){this.check(user);const p=this.store.state.pro.live?.find(x=>x.id===id&&x.userId===user.id&&x.status!=='preview');if(!p)throw fail(404,'Attempted order not found');const r=await this.api('/v2/orders:by_client_order_id?client_order_id='+p.order.client_order_id);if(r.client_order_id!==p.order.client_order_id)throw fail(502,'Provider identity mismatch');await this.store.transaction(s=>{const item=s.pro.live.find(x=>x.id===id);item.status='reconciled';item.providerId=r.id;item.providerStatus=r.status;delete item.error;audit(s,user.id,'live.reconciled',id);});return{id:r.id,status:r.status,filled_qty:r.filled_qty,filled_avg_price:r.filled_avg_price,client_order_id:r.client_order_id};}
}
