/** Fixed-host provider adapters. Browser input never controls destination hosts.
 * Account/orders are PAPER ONLY. No real-money endpoint is present in this app.
 */
import {normalizeCandles,resample} from '../src/core.js';
import {computeIndicators} from '../src/indicators.js';
export const COINBASE='https://api.exchange.coinbase.com';
export const ALPACA_PAPER='https://paper-api.alpaca.markets';
export const ALPACA_DATA='https://data.alpaca.markets';
const err=(message,status=400)=>Object.assign(new Error(message),{status});
async function jsonFetch(fetcher,url,options={}){let response;try{response=await fetcher(url,{...options,redirect:'error',signal:AbortSignal.timeout(12000)});}catch{throw err('Upstream provider could not be reached.',502);}const text=await response.text();if(text.length>30_000_000)throw err('Provider response too large.',502);let body;try{body=JSON.parse(text);}catch{throw err('Provider returned a non-JSON response.',502);}if(!response.ok)throw err(`Provider HTTP ${response.status}: ${String(body.message||body.error||'request rejected').slice(0,300)}`,response.status===429?429:502);return body;}
export function validatePaperOrder(raw){if(!raw||!/^[A-Z][A-Z0-9.]{0,14}$/.test(raw.symbol||''))throw err('Invalid equity symbol.');if(!['buy','sell'].includes(raw.side)||!['market','limit','stop','stop_limit','trailing_stop'].includes(raw.type)||!['day','gtc'].includes(raw.time_in_force))throw err('Invalid paper order type, side or time-in-force.');const qty=Number(raw.qty);if(!(qty>0&&qty<=1e8&&Number.isFinite(qty)))throw err('Invalid paper quantity.');const order={symbol:raw.symbol,side:raw.side,type:raw.type,time_in_force:raw.time_in_force,qty:String(qty),client_order_id:String(raw.client_order_id||'')};if(!/^[A-Za-z0-9_-]{1,48}$/.test(order.client_order_id))throw err('A unique client_order_id of 1–48 safe characters is required.');const positive=(key)=>{const n=Number(raw[key]);if(!(n>0&&n<=1e12&&Number.isFinite(n)))throw err('Invalid '+key);return String(n);};if(['limit','stop_limit'].includes(order.type))order.limit_price=positive('limit_price');if(['stop','stop_limit'].includes(order.type))order.stop_price=positive('stop_price');if(order.type==='trailing_stop')order.trail_price=positive('trail_price');return order;}
export class Providers {
  constructor({fetcher=fetch,key='',secret='',feed='iex'}={}){this.fetcher=fetcher;this.key=key;this.secret=secret;this.feed=feed;this.cache=new Map();this.next=0;this.tail=Promise.resolve();}
  get configured(){return !!(this.key&&this.secret);}
  async coinbase(path){if(!/^\/products(?:\/[A-Z0-9.-]{1,32}(?:\/(?:candles|stats|ticker|book))?)?(?:\?|$)/.test(path))throw err('Unsupported Coinbase endpoint.');const u=new URL(COINBASE+path);if(u.origin!==COINBASE||!/^\/products(?:\/[A-Z0-9.-]{1,32}(?:\/(?:candles|stats|ticker|book))?)?$/.test(u.pathname))throw err('Invalid market path.');for(const k of u.searchParams.keys())if(!['granularity','start','end','level'].includes(k))throw err('Unsupported market query.');const old=this.cache.get(path);if(old&&old.expires>Date.now())return old.data;const previous=this.tail;let release;this.tail=new Promise(r=>release=r);await previous;try{const wait=this.next-Date.now();if(wait>0)await new Promise(r=>setTimeout(r,wait));this.next=Date.now()+180;const data=await jsonFetch(this.fetcher,u.href,{headers:{Accept:'application/json','User-Agent':'AureonTerminal/2.0'}});this.cache.set(path,{data,expires:Date.now()+(u.pathname.endsWith('/candles')?5000:1500)});if(this.cache.size>300)this.cache.delete(this.cache.keys().next().value);return data;}finally{release();}}
  async alertValues(symbol,interval){if(!/^[A-Z0-9.-]+-USD$/.test(symbol))throw err('Server alert feed supports Coinbase USD products.');const native=[60,300,900,3600,21600,86400].includes(interval)?interval:interval===14400?3600:interval===604800?86400:null;if(!native)throw err('Unsupported alert interval.');const ticker=await this.coinbase('/products/'+symbol+'/ticker'),rows=await this.coinbase('/products/'+symbol+'/candles?granularity='+native);if(!Array.isArray(rows))throw err('Invalid provider candles.',502);let bars=normalizeCandles(rows.map(r=>({t:+r[0],l:+r[1],h:+r[2],o:+r[3],c:+r[4],v:+r[5]})));if(native!==interval)bars=resample(bars,interval);const now=Date.now()/1000;bars=bars.filter(b=>b.t+interval<=now&&!b.partial);if(!bars.length)throw err('No closed candles available for this interval.',502);const indicators=computeIndicators(bars),b=bars.at(-1);return{values:{price:+ticker.price,close:b.c,volume:b.v,rsi:indicators.rsi.at(-1),ema:indicators.ema.at(-1),sma:indicators.sma.at(-1)},barTime:b.t,time:now};}
  async alpaca(path,{method='GET',body,data=false}={}){if(!this.configured)throw err('Alpaca server credentials are not configured.',503);if(!/^\/v2\/(?:account|orders(?:\/[a-f0-9-]{36})?|stocks\/bars)(?:\?|$)/i.test(path))throw err('Unsupported paper/data endpoint.');const base=data?ALPACA_DATA:ALPACA_PAPER,u=new URL(path,base);if(u.origin!==base)throw err('Invalid provider destination.');return jsonFetch(this.fetcher,u.href,{method,headers:{'APCA-API-KEY-ID':this.key,'APCA-API-SECRET-KEY':this.secret,Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});}
  async cancelPaper(id){if(!/^[a-f0-9-]{36}$/i.test(id))throw err('Invalid order ID');if(!this.configured)throw err('Alpaca server credentials are not configured.',503);let response;try{response=await this.fetcher(ALPACA_PAPER+'/v2/orders/'+id,{method:'DELETE',redirect:'error',signal:AbortSignal.timeout(12000),headers:{'APCA-API-KEY-ID':this.key,'APCA-API-SECRET-KEY':this.secret}});}catch{throw err('Paper provider unavailable.',502);}if(!response.ok)throw err('Paper cancellation rejected: HTTP '+response.status,502);return{ok:true};}
  async history(query){const intervals={'1Min':60,'5Min':300,'15Min':900,'1Hour':3600,'1Day':86400,'1Week':604800},symbol=String(query.symbol||'').toUpperCase(),interval=intervals[query.timeframe];if(!/^[A-Z][A-Z0-9.]{0,14}$/.test(symbol)||!interval||!/^\d{4}-\d{2}-\d{2}$/.test(query.start||''))throw err('Invalid equity history request.');const start=new Date(query.start+'T00:00:00Z');if(!Number.isFinite(start.getTime())||start.getTime()>Date.now())throw err('Invalid history start.');let pageToken,bars=[];for(let page=0;page<5;page++){const args=new URLSearchParams({symbols:symbol,timeframe:query.timeframe,start:start.toISOString(),limit:'10000',adjustment:'raw',feed:this.feed,sort:'asc'});if(pageToken)args.set('page_token',pageToken);const data=await this.alpaca('/v2/stocks/bars?'+args,{data:true});const items=data.bars?.[symbol]||[];bars.push(...items.map(b=>({t:Date.parse(b.t)/1000,o:+b.o,h:+b.h,l:+b.l,c:+b.c,v:+b.v})));pageToken=data.next_page_token;if(!pageToken)break;}return{symbol,interval,bars:normalizeCandles(bars),truncated:!!pageToken,source:`Alpaca ${this.feed.toUpperCase()} historical bars · raw/unadjusted${pageToken?' · truncated at 50,000 rows':''}`};}
}
