/** Read-only, fixed-destination research adapters. API responses keep provenance,
 * vintage/as-of metadata and explicit pagination truncation. Keys stay server-side.
 */
const bad=(message,status=400)=>Object.assign(new Error(message),{status});
const symbol=x=>{if(!/^[A-Z][A-Z0-9.]{0,14}$/.test(x||''))throw bad('Invalid equity symbol');return x;};
const date=x=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(x||'')||new Date(x+'T00:00:00Z').toISOString().slice(0,10)!==x)throw bad('Invalid ISO date');return x;};
export async function boundedJSON(fetcher,url,options={}){let response;try{response=await fetcher(url,{...options,redirect:'error',signal:AbortSignal.timeout(12000)});}catch{throw bad('Research provider unavailable',502);}if(!response.ok)throw bad('Research provider rejected request: HTTP '+response.status,response.status===429?429:502);let text='';if(response.body?.getReader){const reader=response.body.getReader(),decoder=new TextDecoder();let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>12_000_000){await reader.cancel();throw bad('Research response exceeds 12 MB',502);}text+=decoder.decode(value,{stream:true});}text+=decoder.decode();}finally{reader.releaseLock();}}else{text=await response.text();if(text.length>12_000_000)throw bad('Research response exceeds 12 MB',502);}try{return JSON.parse(text);}catch{throw bad('Invalid research provider JSON',502);}}
export class ResearchProviders {
  constructor({fetcher=fetch,key='',secret='',optionFeed='indicative',fredKey='',secAgent=''}={}){if(!['indicative','opra'].includes(optionFeed))throw bad('Invalid option feed');Object.assign(this,{fetcher,key,secret,optionFeed,fredKey,secAgent});this.cache=new Map();this.pending=new Map();this.lastSEC=0;}
  get capabilities(){return{options:!!(this.key&&this.secret),news:!!(this.key&&this.secret),macro:!!this.fredKey,filings:!!this.secAgent};}
  async get(kind,q={}){if(!this.capabilities[kind])throw bad('Provider is not configured for '+kind,503);const key=kind+JSON.stringify(q),cached=this.cache.get(key);if(cached&&cached.expires>Date.now())return{...cached.value,cached:true};if(this.pending.has(key))return this.pending.get(key);if(this.pending.size>=4)throw bad('Research requests busy',429);const promise=this.load(kind,q).then(value=>{this.cache.set(key,{value,expires:Date.now()+60000});if(this.cache.size>100)this.cache.delete(this.cache.keys().next().value);return value;}).finally(()=>this.pending.delete(key));this.pending.set(key,promise);return promise;}
  async alpaca(path){if(!/^\/v1beta1\/(options\/snapshots\/[A-Z][A-Z0-9.]{0,14}|news)\?/.test(path))throw bad('Unsupported research path');return boundedJSON(this.fetcher,'https://data.alpaca.markets'+path,{headers:{'APCA-API-KEY-ID':this.key,'APCA-API-SECRET-KEY':this.secret,Accept:'application/json'}});}
  async load(kind,q){const asOf=new Date().toISOString();
    if(kind==='options'){const underlying=symbol(q.symbol),items=Object.create(null);let token=null;for(let page=0;page<10;page++){const a=new URLSearchParams({feed:this.optionFeed,limit:'1000'});if(q.expiration)a.set('expiration_date',date(q.expiration));if(token)a.set('page_token',token);const r=await this.alpaca('/v1beta1/options/snapshots/'+underlying+'?'+a);if(!r.snapshots||typeof r.snapshots!=='object'||Array.isArray(r.snapshots))throw bad('Invalid option chain response',502);Object.assign(items,r.snapshots);token=r.next_page_token;if(!token)break;}return{kind,underlying,source:'Alpaca '+this.optionFeed+' option snapshots; entitlement/delay depend on feed',asOf,items,truncated:!!token,nextPageToken:token};}
    if(kind==='news'){const symbols=String(q.symbols||'').split(',').filter(Boolean);if(symbols.length>10)throw bad('At most 10 news symbols');symbols.forEach(symbol);let token=null,items=[];for(let page=0;page<5;page++){const a=new URLSearchParams({limit:'50',sort:'desc',include_content:'false',exclude_contentless:'true'});if(symbols.length)a.set('symbols',symbols.join(','));if(token)a.set('page_token',token);const r=await this.alpaca('/v1beta1/news?'+a);if(!Array.isArray(r.news))throw bad('Invalid news response',502);items.push(...r.news);token=r.next_page_token;if(!token)break;}return{kind,source:'Alpaca news; upstream timestamps retained',asOf,items,truncated:!!token};}
    if(kind==='macro'){if(!/^[A-Za-z0-9_]{1,80}$/.test(q.series||''))throw bad('Invalid FRED series ID');const vintage=date(q.vintage||asOf.slice(0,10));if(vintage>asOf.slice(0,10))throw bad('FRED vintage cannot be in the future');const a=new URLSearchParams({series_id:q.series,api_key:this.fredKey,file_type:'json',realtime_start:vintage,realtime_end:vintage,limit:'10000',sort_order:'asc'});if(q.start)a.set('observation_start',date(q.start));const r=await boundedJSON(this.fetcher,'https://api.stlouisfed.org/fred/series/observations?'+a);if(!Array.isArray(r.observations))throw bad('Invalid FRED observations',502);return{kind,series:q.series,source:'FRED/ALFRED vintage '+vintage,asOf,vintage,count:r.count,items:r.observations.map(x=>({...x,value:x.value==='.'?null:Number(x.value)})),truncated:Number(r.count)>r.observations.length};}
    if(kind==='filings'){if(!/^\d{1,10}$/.test(q.cik||'')||!/@/.test(this.secAgent))throw bad('SEC requires numeric CIK and operator contact User-Agent');const wait=this.lastSEC+200-Date.now();this.lastSEC=Math.max(this.lastSEC+200,Date.now());if(wait>0)await new Promise(r=>setTimeout(r,wait));const cik=q.cik.padStart(10,'0'),r=await boundedJSON(this.fetcher,'https://data.sec.gov/api/xbrl/companyfacts/CIK'+cik+'.json',{headers:{'User-Agent':this.secAgent,Accept:'application/json'}});return{kind,source:'SEC EDGAR XBRL company facts; filing dates and units retained',asOf,cik,entity:r.entityName,items:r.facts};}
    throw bad('Unknown research type');
  }
}
