/** Authenticated private services. Invoked only after the host/origin/session/CSRF gate.
 * Workspace snapshots use revisions; drawings use authored operations. External
 * notification destinations belong to operator configuration, not request bodies.
 */
import {appendEvent} from './events.mjs';
import {drawingRoomRequest} from './drawing-rooms.mjs';
import {LeaseCoordinator} from './lease.mjs';
import {LiveGateway} from './live-gateway.mjs';
import {randomBytes,randomUUID} from 'node:crypto';
import {PrivateVault,base32Encode,verifyTOTP,digest,recoveryCodes,audit,verifyAudit} from './security-pro.mjs';
import {ResearchProviders} from './research-pro.mjs';
import {DeliveryQueue,newVapid,validatePush,enqueueDelivery} from './delivery-pro.mjs';
import {ServerScripts} from './script-runner.mjs';
const problem=(status,message)=>Object.assign(new Error(message),{status});
const text=(v,name,max=200)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw problem(400,'Invalid '+name);return v.trim();};
const forbidden=['__proto__','prototype','constructor'];
function symbolInterval(b){if(!/^[A-Z0-9.-]{1,25}-USD$/.test(b.symbol||'')||![60,300,900,3600,14400,21600,86400,604800].includes(b.interval))throw problem(400,'Server monitoring requires supported Coinbase USD symbol/interval');}
export function drawingLevel(d,time){if(!d||!['hline','trend','ray','extended','horizontalray'].includes(d.type)||!Array.isArray(d.points)||d.points.length!==(d.type==='hline'||d.type==='horizontalray'?1:2)||d.points.some(p=>!Number.isFinite(p.t)||p.t<0||!Number.isFinite(p.p)))throw problem(400,'Invalid supported drawing');const[a,b]=d.points;if(d.type==='hline')return a.p;if(d.type==='horizontalray')return time>=a.t?a.p:NaN;if(a.t===b.t)throw problem(400,'Vertical segment has no single price');if(d.type==='trend'&&(time<Math.min(a.t,b.t)||time>Math.max(a.t,b.t)))return NaN;if(d.type==='ray'&&(b.t>a.t?time<a.t:time>a.t))return NaN;return a.p+(b.p-a.p)*(time-a.t)/(b.t-a.t);}
export class ProServices {
  constructor(store,providers,emit,{fetcher=fetch,research={},delivery={},moderators=[],researchUser='',scripts={},live={},monitorInterval=15000}={}){Object.assign(this,{store,providers,emit,options:{research,delivery,moderators,researchUser,monitorInterval},fetcher});this.live=new LiveGateway(store,{...live,fetcher});this.scripts=new ServerScripts(scripts);this.research=new ResearchProviders({...research,fetcher});this.errors=new Map();this.busy=false;this.coordinator=new LeaseCoordinator(store);}
  async init(){this.vault=await PrivateVault.open(this.store.directory);const owners=this.store.state.users;this.researchOwner=owners.find(u=>u.username===this.options.researchUser)?.id;this.moderators=new Set(owners.filter(u=>this.options.moderators.includes(u.username)).map(u=>u.id));const recipientNames=Object.keys(this.options.delivery.recipients||{}),hookNames=Object.values(this.options.delivery.webhooks||{}).map(w=>w.username);this.notificationOwners=new Set(owners.filter(u=>recipientNames.includes(u.username)||hookNames.includes(u.username)).map(u=>u.id));await this.store.transaction(s=>{s.pro??={};for(const key of ['channels','outbox','monitors','monitorLog','libraries','rooms','follows','messages','blocks','privacy','reports','audit'])s.pro[key]??=[];if(!s.pro.vapid)s.pro.vapid=this.vault.seal(newVapid(),'vapid');if(!verifyAudit(s.pro.audit,s.pro.auditAnchor))throw new Error('Private audit verification failed');});this.delivery=new DeliveryQueue(this.store,{...this.options.delivery,fetcher:this.fetcher,vapid:this.vault.open(this.store.state.pro.vapid,'vapid')});return this;}
  consumeMFA(state,user,code){if(!user.mfa)return;if(typeof code!=='string'||code.length>100)throw problem(401,'MFA code required');const match=user.mfa.recovery?.indexOf(digest(code));if(match>=0){user.mfa.recovery.splice(match,1);audit(state,user.id,'mfa.recovery-login');return;}const secret=this.vault.open(user.mfa.secret,'mfa:'+user.id),step=verifyTOTP(secret,code,{lastStep:user.mfa.lastStep??-1});if(step===null)throw problem(401,'Invalid or already-used MFA code');user.mfa.lastStep=step;}
  capabilities(user){return{version:4,live:{enabled:this.live.allowed(user),maxNotional:this.live.maxNotional,dailyNotional:this.live.dailyNotional},mfa:!!user?.mfa,research:this.researchOwner===user?.id?this.research.capabilities:{},notifications:this.notificationOwners.has(user?.id)?this.delivery.capabilities(user.username):{push:!!this.options.delivery.pushSubject,pushPublicKey:this.delivery.vapid.publicKey},moderator:this.moderators.has(user?.id),collaboration:'revisioned workspaces and operation-set drawing rooms',scriptMonitor:true};}
  async handle({path,method,url,req,user,body,validatePayload,verifyPassword,passwordHash,session,expected}){if(!path.startsWith('pro/'))return null;const route=path.slice(4),read=()=>body(req,2_000_000),state=this.store.state,p=state.pro;const result=(data,status=200)=>({data,status});
    if(route.startsWith('live/')){if(!expected?.startsWith('https://'))throw problem(403,'Real-money routing requires HTTPS');if(route==='live/preview'&&method==='POST')return result(await this.live.preview(user,await read()));if(route==='live/confirm'&&method==='POST'){const b=await read();return result(await this.live.confirm(user,b.id,b.phrase,{authorize:(s,u)=>this.consumeMFA(s,u,String(b.code||''))}));}if(route==='live/reconcile'&&method==='POST'){const b=await read();return result(await this.live.reconcile(user,b.id));}if(route==='live/orders'&&method==='GET'){this.live.check(user);return result({items:(p.live||[]).filter(x=>x.userId===user.id).slice(-100)});}throw problem(404,'Unsupported real-money operation');}
    if(route==='capabilities'&&method==='GET')return result(this.capabilities(user));
    if(route==='security'&&method==='GET')return result({mfa:!!user.mfa,recoveryRemaining:user.mfa?.recovery?.length||0,sessions:state.sessions.filter(s=>s.userId===user.id).map(s=>({expires:s.expires,current:s.tokenHash===session.tokenHash})),audit:p.audit.filter(e=>e.userId===user.id).slice(-100)});
    if(route.startsWith('security/')&&method==='POST'){const b=await read();if(!await verifyPassword(b.password,user))throw problem(401,'Current password required');const account=()=>this.store.state.users.find(u=>u.id===user.id);
      if(route==='security/enroll'){if(user.mfa)throw problem(409,'MFA is already enabled');const secret=base32Encode(randomBytes(20));await this.store.transaction(s=>{const u=s.users.find(u=>u.id===user.id);if(u.mfa)throw problem(409,'MFA is already enabled');u.mfaPending={secret:this.vault.seal(secret,'mfa:'+u.id),expires:Date.now()+600000};audit(s,u.id,'mfa.enrollment-started');});return result({secret,uri:'otpauth://totp/'+encodeURIComponent('Aureon:'+user.username)+'?secret='+secret+'&issuer=Aureon&algorithm=SHA1&digits=6&period=30'});}
      if(route==='security/confirm'){const codes=recoveryCodes();await this.store.transaction(s=>{const u=s.users.find(u=>u.id===user.id),pending=u.mfaPending;if(u.mfa||!pending||pending.expires<Date.now())throw problem(409,'Enrollment expired or already completed');const secret=this.vault.open(pending.secret,'mfa:'+u.id),step=verifyTOTP(secret,String(b.code||''));if(step===null)throw problem(400,'Invalid authenticator code');u.mfa={secret:pending.secret,lastStep:step,recovery:codes.map(digest)};delete u.mfaPending;s.sessions=s.sessions.filter(x=>x.userId!==u.id||x.tokenHash===session.tokenHash);audit(s,u.id,'mfa.enabled');});return result({enabled:true,recoveryCodes:codes});}
      if(route==='security/disable'){await this.store.transaction(s=>{const u=s.users.find(u=>u.id===user.id);this.consumeMFA(s,u,String(b.code||''));delete u.mfa;delete u.mfaPending;audit(s,u.id,'mfa.disabled');});return result({enabled:false});}
      if(route==='security/revoke'){await this.store.transaction(s=>{s.sessions=s.sessions.filter(x=>x.userId!==user.id||x.tokenHash===session.tokenHash);audit(s,user.id,'sessions.revoked');});return result({ok:true});}
      if(route==='security/password'){if(typeof b.newPassword!=='string'||b.newPassword.length<12||b.newPassword.length>200)throw problem(400,'New password must contain 12–200 characters');const credential=await passwordHash(b.newPassword);await this.store.transaction(s=>{const u=s.users.find(u=>u.id===user.id);if(u.hash!==user.hash)throw problem(409,'Account changed; sign in again');this.consumeMFA(s,u,String(b.code||''));Object.assign(u,credential);s.sessions=s.sessions.filter(x=>x.userId!==user.id||x.tokenHash===session.tokenHash);audit(s,user.id,'password.changed');});return result({ok:true});}
    }
    if(route.startsWith('research/')&&method==='GET'){if(this.researchOwner!==user.id)throw problem(403,'Research feeds require a pre-existing configured owner account');return result(await this.research.get(route.slice(9),Object.fromEntries(url.searchParams)));}
    if(route==='scripts/run'&&method==='POST'){const b=await read();return result(await this.scripts.run(b.source,b.bars,b.options||{}));}
    if(route==='channels'){
      if(method==='GET')return result({capabilities:this.capabilities(user).notifications,items:p.channels.filter(c=>c.userId===user.id).map(({subscription,...c})=>({...c,subscription:subscription?{endpoint:new URL(subscription.endpoint).origin}:undefined})),log:p.outbox.filter(j=>j.userId===user.id).slice(-100)});
      if(method==='POST'){const b=await read(),type=b.type,cap=this.capabilities(user).notifications;if(!['email','sms','webhook','push'].includes(type)||(type==='webhook'?!cap.webhooks?.includes(b.alias):!cap[type]))throw problem(400,'Notification channel is not configured');if(b.consent!==true)throw problem(400,'Explicit notification consent is required');const value={id:randomUUID(),userId:user.id,username:user.username,type,active:true,created:Date.now()};if(type==='push')value.subscription=validatePush(b.subscription);if(type==='webhook')value.alias=b.alias;await this.store.transaction(s=>{if(s.pro.channels.filter(c=>c.userId===user.id).length>=5)throw problem(400,'At most five notification channels');s.pro.channels.push(value);audit(s,user.id,'notifications.enabled',type);});return result({id:value.id,type},201);}
    }
    const channel=/^channels\/([a-f\d-]+)$/.exec(route);if(channel&&method==='DELETE'){await this.store.transaction(s=>{const c=s.pro.channels.find(c=>c.id===channel[1]&&c.userId===user.id);if(!c)throw problem(404,'Channel not found');s.pro.channels=s.pro.channels.filter(x=>x!==c);audit(s,user.id,'notifications.disabled',c.type);});return result({ok:true});}
    if(route==='monitors'){
      if(method==='GET')return result({items:p.monitors.filter(r=>r.userId===user.id),log:p.monitorLog.filter(r=>r.userId===user.id).slice(-100),errors:p.monitors.filter(r=>r.userId===user.id&&this.errors.has(r.id)).map(r=>({id:r.id,error:this.errors.get(r.id)}))});
      if(method==='POST'){const b=await read();symbolInterval(b);if(!['script','drawing'].includes(b.kind))throw problem(400,'Unsupported monitor kind');const r={id:randomUUID(),userId:user.id,symbol:b.symbol,interval:b.interval,kind:b.kind,active:true,once:b.once!==false,message:text(b.message||'Aureon monitor','message',1000),revision:1,created:Date.now()};if(r.kind==='script'){r.source=text(b.source,'source',80000);r.plot=Number(b.plot||0);r.threshold=Number(b.threshold??0);if(!Number.isInteger(r.plot)||r.plot<0||r.plot>=64||!Number.isFinite(r.threshold))throw problem(400,'Invalid script plot or threshold');}else{drawingLevel(b.drawing,0);r.drawing=structuredClone(b.drawing);}r.direction=b.direction||'cross';if(!['cross','above','below'].includes(r.direction))throw problem(400,'Invalid crossing direction');await this.store.transaction(s=>{if(s.pro.monitors.filter(x=>x.userId===user.id).length>=20)throw problem(400,'At most 20 script/drawing monitors');s.pro.monitors.push(r);audit(s,user.id,'monitor.created',r.id);});return result(r,201);}
    }
    const monitor=/^monitors\/([a-f\d-]+)$/.exec(route);if(monitor&&['DELETE','PATCH'].includes(method)){const b=method==='PATCH'?await read():{};await this.store.transaction(s=>{const r=s.pro.monitors.find(x=>x.id===monitor[1]&&x.userId===user.id);if(!r)throw problem(404,'Monitor not found');if(method==='DELETE')s.pro.monitors=s.pro.monitors.filter(x=>x!==r);else{if(typeof b.active!=='boolean')throw problem(400,'active must be boolean');r.active=b.active;r.revision++;delete r.previous;delete r.lastBar;}audit(s,user.id,'monitor.'+method.toLowerCase(),r.id);});return result({ok:true});}
    if(route==='libraries'){
      if(method==='GET')return result({items:p.libraries.filter(x=>!x.hidden&&(x.public||x.userId===user.id)).map(({source,...x})=>x)});
      if(method==='POST'){const b=await read(),name=text(b.name,'library name',40);if(!/^[A-Za-z][A-Za-z0-9_]*$/.test(name)||forbidden.includes(name)||!Number.isInteger(b.version)||b.version<1||b.version>100000)throw problem(400,'Invalid library name/version');const source=text(b.source,'source',80000),item={id:user.username+'/'+name+'/'+b.version,userId:user.id,name,version:b.version,source,public:b.public===true,description:String(b.description||'').slice(0,500),created:Date.now()};await this.store.transaction(s=>{if(s.pro.libraries.some(x=>x.id===item.id))throw problem(409,'Library versions are immutable; publish a new version');if(s.pro.libraries.filter(x=>x.userId===user.id).length>=100)throw problem(400,'Library quota exceeded');s.pro.libraries.push(item);audit(s,user.id,'library.published',item.id);});return result(item,201);}
    }
    if(route.startsWith('libraries/')&&method==='GET'){const item=p.libraries.find(x=>x.id===route.slice(10)&&!x.hidden&&(x.public||x.userId===user.id));if(!item)throw problem(404,'Library not found');return result(item);}
    if(route==='people'&&method==='GET')return result({items:state.users.map(u=>({id:u.id,username:u.username,following:p.follows.some(x=>x.from===user.id&&x.to===u.id),blocked:p.blocks.some(x=>x.from===user.id&&x.to===u.id)})),allowDM:!!p.privacy.find(x=>x.userId===user.id)?.allowDM});
    if(route==='privacy'&&method==='POST'){const b=await read();if(typeof b.allowDM!=='boolean')throw problem(400,'allowDM boolean required');await this.store.transaction(s=>{const q=s.pro.privacy.find(x=>x.userId===user.id);if(q)q.allowDM=b.allowDM;else s.pro.privacy.push({userId:user.id,allowDM:b.allowDM});});return result({ok:true});}
    const relation=/^(follow|block)\/([a-f\d-]+)$/.exec(route);if(relation&&['POST','DELETE'].includes(method)){const[operation,id]=relation.slice(1);if(id===user.id||!state.users.some(u=>u.id===id))throw problem(404,'Other user not found');await this.store.transaction(s=>{if(operation==='follow'&&method==='POST'&&s.pro.blocks.some(x=>x.from===user.id&&x.to===id||x.from===id&&x.to===user.id))throw problem(403,'Blocked users cannot follow each other');const key=operation==='follow'?'follows':'blocks';s.pro[key]=s.pro[key].filter(x=>!(x.from===user.id&&x.to===id));if(method==='POST')s.pro[key].push({from:user.id,to:id});if(operation==='block')s.pro.follows=s.pro.follows.filter(x=>!(x.from===user.id&&x.to===id||x.from===id&&x.to===user.id));});return result({ok:true});}
    if(route==='messages'){
      if(method==='GET')return result({items:p.messages.filter(m=>!m.hidden&&(m.from===user.id||m.to===user.id)&&!p.blocks.some(b=>b.from===user.id&&(b.to===m.from||b.to===m.to))).slice(-200)});
      if(method==='POST'){const b=await read();if(!state.users.some(u=>u.id===b.to)||b.to===user.id)throw problem(404,'Recipient not found');const m={id:randomUUID(),from:user.id,to:b.to,username:user.username,text:text(b.text,'message',2000),created:Date.now()};await this.store.transaction(s=>{if(!s.pro.privacy.find(x=>x.userId===b.to)?.allowDM||s.pro.blocks.some(x=>x.from===user.id&&x.to===b.to||x.from===b.to&&x.to===user.id))throw problem(403,'Recipient does not accept messages');if(s.pro.messages.filter(x=>x.from===user.id&&x.created>Date.now()-86400000).length>=100)throw problem(429,'Daily message limit reached');if(s.pro.messages.length>=50000)throw problem(507,'Server message capacity reached');s.pro.messages.push(m);appendEvent(s,b.to,{type:'message',id:m.id});});this.emit(b.to,{type:'message',id:m.id});return result(m,201);}
    }
    if(/^rooms\/[a-f\d-]+\/drawings$/.test(route))return drawingRoomRequest({store:this.store,route,method,url,user,read,result});
    if(route==='rooms'){
      if(method==='GET')return result({items:p.rooms.filter(x=>x.members.includes(user.id)).map(({payload,drawingDocuments,...x})=>x)});
      if(method==='POST'){const b=await read(),name=text(b.name,'room name',100),members=[...new Set([user.id,...(Array.isArray(b.members)?b.members:[])])];if(members.length>16||members.some(id=>!state.users.some(u=>u.id===id)))throw problem(400,'Room members must be up to 16 existing account IDs');const room={id:randomUUID(),userId:user.id,name,members,payload:validatePayload(b.payload),revision:1,updated:Date.now()};await this.store.transaction(s=>{if(s.pro.rooms.filter(x=>x.userId===user.id).length>=20)throw problem(400,'Room quota exceeded');s.pro.rooms.push(room);audit(s,user.id,'room.created',room.id);});return result(room,201);}
    }
    const roomMatch=/^rooms\/([a-f\d-]+)$/.exec(route);if(roomMatch){const id=roomMatch[1],room=p.rooms.find(x=>x.id===id&&x.members.includes(user.id));if(!room)throw problem(404,'Room not found');if(method==='GET')return result(room);if(method==='PUT'){const b=await read(),payload=validatePayload(b.payload),revision=Number(req.headers['if-match']);if(!Number.isInteger(revision)||revision<1)throw problem(428,'If-Match revision required');const saved=await this.store.transaction(s=>{const r=s.pro.rooms.find(x=>x.id===id&&x.members.includes(user.id));if(!r)throw problem(404,'Room no longer available');if(r.revision!==revision)throw problem(409,'Room changed; fetch latest before publishing');r.payload=payload;r.revision++;r.updated=Date.now();audit(s,user.id,'room.updated',id);for(const member of r.members)appendEvent(s,member,{type:'room',id,revision:r.revision});return r;});for(const member of saved.members)this.emit(member,{type:'room',id,revision:saved.revision});return result({id,revision:saved.revision});}if(method==='DELETE'){if(room.userId!==user.id)throw problem(403,'Room owner required');await this.store.transaction(s=>{s.pro.rooms=s.pro.rooms.filter(x=>x.id!==id);audit(s,user.id,'room.deleted',id);});return result({ok:true});}}
    if(route==='reports'&&method==='POST'){const b=await read();if(!['idea','library','message'].includes(b.kind))throw problem(400,'Invalid report kind');const list=b.kind==='idea'?state.ideas:b.kind==='library'?p.libraries:p.messages,item=list.find(x=>x.id===b.id);if(!item||b.kind==='message'&&item.from!==user.id&&item.to!==user.id||b.kind==='library'&&!item.public&&item.userId!==user.id)throw problem(404,'Report subject not found');const report={id:randomUUID(),userId:user.id,kind:b.kind,subject:b.id,reason:text(b.reason,'reason',1000),created:Date.now(),status:'open'};await this.store.transaction(s=>{if(s.pro.reports.filter(x=>x.userId===user.id&&x.created>Date.now()-86400000).length>=20)throw problem(429,'Report quota reached');s.pro.reports.push(report);if(s.pro.reports.length>10000)s.pro.reports.shift();});return result({id:report.id},201);}
    if(route==='moderation'&&method==='GET'){if(!this.moderators.has(user.id))throw problem(403,'Configured moderator required');return result({items:p.reports.filter(x=>x.status==='open')});}
    if(route==='moderation'&&method==='POST'){if(!this.moderators.has(user.id))throw problem(403,'Configured moderator required');const b=await read();if(!['dismiss','hide'].includes(b.action))throw problem(400,'Invalid moderation action');await this.store.transaction(s=>{const r=s.pro.reports.find(x=>x.id===b.id);if(!r)throw problem(404,'Report not found');r.status=b.action;r.moderator=user.id;if(b.action==='hide'){const list=r.kind==='idea'?s.ideas:r.kind==='library'?s.pro.libraries:s.pro.messages,item=list.find(x=>x.id===r.subject);if(item)item.hidden=true;}audit(s,user.id,'moderation.'+b.action,r.subject);});return result({ok:true});}
    throw problem(404,'Pro service route not found');
  }
  async poll(){if(this.busy)return;this.busy=true;let lease;try{lease=await this.coordinator.acquire('monitors:pro');if(!lease)return;const groups=new Map();for(const r of this.store.state.pro.monitors.filter(x=>x.active)){const key=r.symbol+':'+r.interval;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}for(const list of groups.values()){let sample;try{sample=await this.providers.alertValues(list[0].symbol,list[0].interval);}catch(e){for(const r of list)this.errors.set(r.id,String(e.message).slice(0,300));continue;}for(const r of list){try{if(sample.barTime<=r.lastBar)continue;let value;if(r.kind==='drawing')value=sample.values.close-drawingLevel(r.drawing,sample.barTime+r.interval);else{const output=await this.scripts.run(r.source,sample.bars||[],{symbol:r.symbol,interval:r.interval});value=output.plots[r.plot]?.values.at(-1)-r.threshold;}if(!Number.isFinite(value))throw new Error('Monitor value is unavailable, outside drawing domain, or warming up');let event;await this.store.transaction(s=>{if(!this.coordinator.owns(s,lease))return;const current=s.pro.monitors.find(x=>x.id===r.id);if(!current?.active||current.revision!==r.revision||current.lastBar>=sample.barTime)return;const previous=current.previous,crossUp=Number.isFinite(previous)&&previous<=0&&value>0,crossDown=Number.isFinite(previous)&&previous>=0&&value<0;current.previous=value;current.lastBar=sample.barTime;if(r.direction==='above'?crossUp:r.direction==='below'?crossDown:crossUp||crossDown){event={id:randomUUID(),userId:r.userId,ruleId:r.id,symbol:r.symbol,time:sample.time,barTime:sample.barTime,message:r.message,value};s.pro.monitorLog.push(event);s.pro.monitorLog=s.pro.monitorLog.slice(-10000);if(current.once)current.active=false;enqueueDelivery(s,r.userId,event);appendEvent(s,r.userId,{type:'alert',event});}});if(event)this.emit(r.userId,{type:'alert',event});this.errors.delete(r.id);}catch(e){this.errors.set(r.id,String(e.message).slice(0,300));}}}}finally{try{await this.coordinator.release(lease);}finally{this.busy=false;}}}
  start(){this.timer=setInterval(()=>this.poll().catch(()=>{}),Math.max(5000,this.options.monitorInterval));this.timer.unref?.();this.delivery.start();}
  async close(){clearInterval(this.timer);while(this.busy)await new Promise(r=>setTimeout(r,10));await this.delivery.close();await this.scripts.close();}
}
