import {rsi,sma,ema,atr} from './indicators.js';
/** OHLC approximation distributes each candle's volume uniformly over [low,high].
 * Exact tick profile accepts individual trades instead; provenance is returned.
 */
export function volumeProfile(bars,{bins=48,valueArea=.7,mode='ohlc',trades=[]}={}){
  if(!Number.isInteger(bins)||bins<2||bins>500||!(valueArea>0&&valueArea<=1))throw new Error('Invalid profile settings.');if(!['ohlc','ticks'].includes(mode))throw new Error('Invalid profile mode.');if(mode==='ticks'&&trades.some(t=>!Number.isFinite(t.price)||t.price<=0||!Number.isFinite(t.size)||t.size<0))throw new Error('Invalid profile trade.');
  const lows=mode==='ticks'?trades.map(t=>t.price):bars.map(b=>b.l),highs=mode==='ticks'?lows:bars.map(b=>b.h);
  if(!lows.length)return{rows:[],total:0,mode};let low=Infinity,high=-Infinity;for(const p of lows)low=Math.min(low,p);for(const p of highs)high=Math.max(high,p);
  const step=(high-low)/bins||Math.max(Math.abs(low)*1e-6,1e-8),rows=Array.from({length:bins},(_,i)=>({low:low+i*step,high:low+(i+1)*step,volume:0,buy:0,sell:0}));
  const index=p=>Math.max(0,Math.min(bins-1,Math.floor((p-low)/step)));
  if(mode==='ticks'){for(const t of trades){if(!(t.size>=0))throw new Error('Invalid trade volume.');const r=rows[index(t.price)];r.volume+=t.size;if(['buy','sell'].includes(t.side))r[t.side]+=t.size;}}
  else for(const b of bars){if(b.h===b.l){rows[index(b.c)].volume+=b.v;continue;}const first=index(b.l),last=index(b.h);let allocated=0;for(let j=first;j<=last;j++){const v=j===last?b.v-allocated:b.v*Math.max(0,Math.min(b.h,rows[j].high)-Math.max(b.l,rows[j].low))/(b.h-b.l);rows[j].volume+=v;allocated+=v;}}
  const total=rows.reduce((s,r)=>s+r.volume,0);let poc=0;for(let i=1;i<rows.length;i++)if(rows[i].volume>rows[poc].volume)poc=i;
  let lo=poc,hi=poc,sum=rows[poc].volume;while(sum<total*valueArea&&(lo>0||hi<bins-1)){if(lo===0||(hi<bins-1&&rows[hi+1].volume>rows[lo-1].volume))sum+=rows[++hi].volume;else sum+=rows[--lo].volume;}
  return{rows,total,step,poc:(rows[poc].low+rows[poc].high)/2,pocIndex:poc,val:rows[lo].low,vah:rows[hi].high,mode,description:mode==='ticks'?'Observed trade volume only; coverage starts at connection.':'OHLC range-distributed volume approximation; not exchange volume-at-price.'};
}
export function timePriceOpportunity(bars,{bins=32,period=1800}={}){
  if(!Number.isInteger(bins)||bins<2||bins>200||!Number.isInteger(period)||period<1)throw new Error('Invalid TPO parameters.');
  if(!bars.length)return[];let lo=Infinity,hi=-Infinity;for(const b of bars){lo=Math.min(lo,b.l);hi=Math.max(hi,b.h);}const step=(hi-lo)/bins||1,rows=Array.from({length:bins},(_,i)=>({price:lo+(i+.5)*step,periods:new Set()}));
  for(const b of bars){const a=Math.max(0,Math.floor((b.l-lo)/step)),z=Math.min(bins-1,Math.floor((b.h-lo)/step));for(let i=a;i<=z;i++)rows[i].periods.add(Math.floor(b.t/period));}
  return rows.map(r=>({price:r.price,count:r.periods.size,periods:[...r.periods]}));
}
export function screenSymbol(symbol,bars,meta={}){if(!bars.length)return{symbol,error:'No bars',...meta};const b=bars.at(-1),closes=bars.map(b=>b.c),r=rsi(closes,14).at(-1),avg=sma(closes,50).at(-1),e=ema(closes,20).at(-1),a=atr(bars,14).at(-1),v=sma(bars.map(b=>b.v),20).at(-1),prev=bars.at(-2)?.c??b.o;
  return{...meta,symbol,price:b.c,change:prev?(b.c/prev-1)*100:NaN,volume:b.v,turnover:b.v*b.c,rsi:r,sma50:avg,ema20:e,atrPct:b.c?a/b.c*100:NaN,relativeVolume:v?b.v/v:NaN,trend:b.c>avg&&e>avg?'Bullish':b.c<avg&&e<avg?'Bearish':'Mixed',time:b.t,bars:bars.length};}
export function filterScreener(rows,filters=[],sort={field:'change',direction:'desc'}){const valid=new Set(['price','change','volume','turnover','rsi','sma50','ema20','atrPct','relativeVolume']);for(const f of filters)if(!valid.has(f.field)||!['>','>=','<','<=','=','between'].includes(f.op)||!Number.isFinite(Number(f.value)))throw new Error('Invalid screener filter.');return rows.filter(r=>filters.every(f=>{const v=r[f.field],a=Number(f.value),b=Number(f.max);if(!Number.isFinite(v))return false;return f.op==='>'?v>a:f.op==='>='?v>=a:f.op==='<'?v<a:f.op==='<='?v<=a:f.op==='='?v===a:v>=a&&v<=b;})).sort((a,b)=>{const av=a[sort.field],bv=b[sort.field];if(!Number.isFinite(av))return 1;if(!Number.isFinite(bv))return -1;return(sort.direction==='asc'?1:-1)*(av-bv);});}
/** Binary weighted treemap: deterministic, positive finite areas, no overlaps. */
export function treemap(items,width,height,weight=x=>x.weight){const clean=items.filter(x=>Number.isFinite(weight(x))&&weight(x)>0).map(x=>({...x,_weight:weight(x)})).sort((a,b)=>b._weight-a._weight),result=[];function split(a,x,y,w,h){if(!a.length)return;if(a.length===1){const {_weight,...item}=a[0];result.push({...item,x,y,w,h});return;}const total=a.reduce((s,v)=>s+v._weight,0);let sum=0,k=0;while(k<a.length-1&&(sum<total/2||k===0)){sum+=a[k++]._weight;}const ratio=sum/total;if(w>=h){split(a.slice(0,k),x,y,w*ratio,h);split(a.slice(k),x+w*ratio,y,w*(1-ratio),h);}else{split(a.slice(0,k),x,y,w,h*ratio);split(a.slice(k),x,y+h*ratio,w,h*(1-ratio));}}split(clean,0,0,width,height);return result;}
export function performanceByMonth(bars){const groups=new Map();for(const b of bars){const key=new Date(b.t*1000).toISOString().slice(0,7);const old=groups.get(key);if(old)old.close=b.c;else groups.set(key,{key,open:b.o,close:b.c});}return [...groups.values()].map(x=>({...x,returnPct:x.open?(x.close/x.open-1)*100:NaN}));}
export function seasonality(bars){const months=Array.from({length:12},(_,month)=>({month,returns:[],mean:NaN,median:NaN,positive:0}));for(const x of performanceByMonth(bars)){const r=months[Number(x.key.slice(5))-1];r.returns.push({year:Number(x.key.slice(0,4)),value:x.returnPct});}for(const x of months){const a=x.returns.map(r=>r.value).filter(Number.isFinite).sort((a,b)=>a-b);if(a.length){x.mean=a.reduce((s,v)=>s+v,0)/a.length;x.median=a.length%2?a[Math.floor(a.length/2)]:(a[a.length/2-1]+a[a.length/2])/2;x.positive=a.filter(v=>v>0).length/a.length;}}return months;}
/** Complete-time alignment: only publish a higher-timeframe value after its close. */
export function alignClosedSeries(target,source,values,sourceInterval,targetInterval){const out=new Float64Array(target.length).fill(NaN);let j=-1;for(let i=0;i<target.length;i++){const knownAt=target[i].t+targetInterval;while(j+1<source.length&&source[j+1].t+sourceInterval<=knownAt&&!source[j+1].partial)j++;if(j>=0)out[i]=values[j];}return out;}
export function spreadSeries(a,b,operator='difference',ratio=1){if(!['difference','ratio','sum'].includes(operator)||!Number.isFinite(ratio))throw new Error('Invalid spread operator.');const map=new Map(b.map(x=>[x.t,x])),out=[];for(const x of a){const y=map.get(x.t);if(!y)continue;const f=(u,v)=>operator==='ratio'?(ratio*v?u/(ratio*v):NaN):operator==='sum'?u+ratio*v:u-ratio*v;const o=f(x.o,y.o),c=f(x.c,y.c),candidates=operator==='ratio'&&y.l<=0&&y.h>=0?[NaN]:[f(x.h,y.h),f(x.h,y.l),f(x.l,y.h),f(x.l,y.l)];if(![o,c,...candidates].every(Number.isFinite))continue;out.push({t:x.t,o,c,h:Math.max(o,c,...candidates),l:Math.min(o,c,...candidates),v:0,synthetic:true});}return out;}
export class SessionCalendar {
  constructor({timezone='UTC',open='00:00',close='24:00',weekdays=[0,1,2,3,4,5,6],holidays=[]}={}){this.zone=timezone;this.format=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23',weekday:'short'});const parse=s=>{if(!/^\d{2}:\d{2}$/.test(s))throw new Error('Session hours must be HH:MM.');const [h,m]=s.split(':').map(Number);if(h>24||m>59||(h===24&&m!==0))throw new Error('Invalid session time.');return h*60+m;};this.open=parse(open);this.close=parse(close);this.days=new Set(weekdays);this.holidays=new Set(holidays);}
  contains(t){const p=Object.fromEntries(this.format.formatToParts(new Date(t*1000)).map(x=>[x.type,x.value]));const day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(p.weekday),minute=Number(p.hour)*60+Number(p.minute),date=`${p.year}-${p.month}-${p.day}`;if(this.holidays.has(date))return false;if(this.open<=this.close)return this.days.has(day)&&minute>=this.open&&minute<this.close;return(minute>=this.open&&this.days.has(day))||(minute<this.close&&this.days.has((day+6)%7));}
  filter(bars){return bars.filter(b=>this.contains(b.t));}
}
