import {Workbench} from './workbench.js';
import {CHART_TYPES} from './chart-types.js';
import {CandleSeries,bucketTime,lowerBound,UndoStack,PaperBroker,AlertEngine,VERSION,demoCandles,normalizeCandles,parseCSV,toCSV,validateWorkspace,clamp,uid} from './core.js';
import {Chart,INDICATOR_INFO,formatPrice,compact} from './chart.js';
import {MarketData,CandleCache,PRODUCTS,TIMEFRAMES} from './data.js';
import {ComputeClient} from './compute.js';
import {icon,hydrateIcons} from './icons.js';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const signed=(x,d=2)=>`${x>=0?'+':''}${Number(x).toFixed(d)}`;
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const DEFAULT={version:VERSION,symbol:'BTC-USD',interval:3600,style:'candles',scale:'linear',indicators:['ema','sma','rsi'],drawings:{},watchlist:PRODUCTS.map(p=>p.id),split:false,theme:'dark'};
const DEMO_BASE={'BTC-USD':67000,'ETH-USD':3400,'SOL-USD':148,'XRP-USD':.58,'DOGE-USD':.13,'ADA-USD':.42,'AVAX-USD':32,'LINK-USD':14};
const STYLE_NAMES=CHART_TYPES;
const tools=[['cursor','Crosshair / select (V)'],['trend','Trend line (T)'],['ray','Ray'],['hline','Horizontal line (H)'],['vline','Vertical line'],['fib','Fibonacci retracement (F)'],['rectangle','Rectangle'],['text','Text annotation'],['measure','Price / time measure']];
class Application {
  constructor(){
    try{this.state=validateWorkspace(read('aureon.workspace',DEFAULT));}catch{this.state=structuredClone(DEFAULT);}
    if(!this.state.watchlist.length)this.state.watchlist=DEFAULT.watchlist;
    this.forceDemo=new URLSearchParams(location.search).has('demo')||document.documentElement.dataset.mode==='demo';this.kind='demo';this.feedState='connecting';this.panel='overview';this.depthTab='book';this.history=new UndoStack();this.compute=new ComputeClient();this.cache=new CandleCache();this.market=new MarketData();this.demoQuotes=new Map();this.modeLabel='Synthetic preview';this.loadId=0;this.indicatorId=0;this.alerts=new AlertEngine(this.readAlerts());this.broker=this.readBroker();this.paperSide='buy';this.comparisonSymbol='ETH-USD';this.compareLoad=0;this.comparison=null;this.replaying=false;this.replayTimer=null;this.book=null;this.tradesSeen=new Set();this.currentHover=null;this.computationBusy=false;this.computationAgain=false;this.panelDirty=false;this.lastMetrics=0;this.products=[...PRODUCTS];
    hydrateIcons();$('drawing-tools').innerHTML=tools.map(([tool,title])=>`<button class="tool-button ${tool==='cursor'?'active':''}" data-tool="${tool}" title="${title}" aria-label="${title}">${icon(tool)}</button>`).join('');
    this.chart=new Chart($('primary-chart'),{symbol:this.state.symbol,interval:this.state.interval,
      onHover:(b,i)=>this.hover(b,i),onView:v=>{if(this.comparison)this.comparison.syncView(v);},onCrosshair:t=>{if(this.comparison){this.comparison.linkedTime=t;this.comparison.invalidate(false);}},
      onNeedMore:()=>this.loadMore(),onMode:mode=>{$('renderer-label').textContent=mode;},onFrame:m=>this.metrics(m),onTool:tool=>this.syncTools(tool),onDrawings:(before,after)=>this.drawingChanged(before,after),
      onSelect:()=>{if(this.depthTab==='drawings')this.renderDepth();},onContext:position=>this.chartMenu(position),sourceLabel:()=>this.exportLabel()});
    this.applyState();this.installEvents();this.installFeed();this.renderWatchlist();this.renderPanel();this.updateIdentity();this.setTheme(this.state.theme,false);
    this.clock=setInterval(()=>this.updateClock(),1000);this.updateClock();this.health=setInterval(()=>this.refreshHealth(),3000);this.autosave=setInterval(()=>this.save(false),20000);
    this.start();if(!this.forceDemo)this.market.connect(this.feedSymbols());else this.setFeedStatus({state:'demo',text:'Offline demo · synthetic data'});
    window.addEventListener('beforeunload',()=>this.save(false));
    window.aureon={app:this,version:VERSION};this.workbench=new Workbench(this);window.aureon.workbench=this.workbench;
  }
  async start(){
    const meta=read('aureon.import',null);
    if(meta&&!this.forceDemo&&meta.symbol===this.state.symbol){
      const cached=await this.cache.get('workspace-import');
      if(cached?.bars?.length&&cached.symbol===meta.symbol){
        const viewInterval=this.state.interval;await this.installImported(this.state,normalizeCandles(cached.bars),cached.interval,cached.source);
        if(viewInterval!==cached.interval)this.changeInterval(viewInterval);return;
      }
    }
    this.loadSymbol(this.state.symbol,this.state.interval);
  }
  readAlerts(){const a=read('aureon.alerts',[]);return Array.isArray(a)?a.filter(x=>x&&typeof x.symbol==='string'&&Number.isFinite(x.price)&&typeof x.active==='boolean'&&typeof x.id==='string'&&Number.isFinite(x.created)&&(!x.triggered||Number.isFinite(x.triggered))).slice(0,500):[];}
  readBroker(){try{const s=read('aureon.paper',null);if(s&&Number.isFinite(s.cash)&&s.cash>=0&&Number.isFinite(s.initial)&&s.initial>0&&s.positions&&Array.isArray(s.orders)&&Array.isArray(s.fills)&&Number.isFinite(s.feeBps)&&s.feeBps>=0&&s.feeBps<=1000){for(const p of Object.values(s.positions))if(![p.qty,p.cost,p.realized].every(Number.isFinite)||p.qty<0||p.cost<0)throw new Error();return new PaperBroker(s);}}catch{}return new PaperBroker();}
  applyState(){Object.assign(this.chart,{symbol:this.state.symbol,interval:this.state.interval,style:this.state.style,scale:this.state.scale,theme:this.state.theme,enabled:[...this.state.indicators],drawings:this.state.drawings[this.state.symbol]||[]});this.chart.invalidate();this.syncToolbar();}
  feedSymbols(){return [...new Set([this.state.symbol,this.comparisonSymbol,...this.state.watchlist,...this.alerts.alerts.filter(a=>a.active).map(a=>a.symbol),...Object.keys(this.broker.state.positions),...this.broker.state.orders.filter(o=>o.status==='open').map(o=>o.symbol)])];}
  demoData(symbol,interval=this.state.interval){const seed=Math.max(1,this.products.findIndex(p=>p.id===symbol)+11);return demoCandles(1000,interval,seed,DEMO_BASE[symbol]||100);}
  previewQuote(symbol,bars){const b=bars.at(-1),sample=bars.slice(-Math.max(2,Math.ceil(86400/this.state.interval)));if(!b)return null;return{symbol,price:b.c,open:sample[0].o,high:Math.max(...sample.map(b=>b.h)),low:Math.min(...sample.map(b=>b.l)),volume:sample.reduce((s,b)=>s+b.v,0),change:(b.c/sample[0].o-1)*100,time:b.t,received:0,preview:true};}
  async loadSymbol(symbol,interval=this.state.interval){
    this.abort?.abort();this.abort=new AbortController();const signal=this.abort.signal,id=++this.loadId;this.stopReplay();this.loading=true;this.moreExhausted=false;this.state.symbol=symbol;this.state.interval=interval;this.market.active=symbol;this.market.trades=[];this.book=null;this.chart.symbol=symbol;this.chart.interval=interval;this.chart.drawings=this.state.drawings[symbol]||[];this.chart.selected=null;this.chart.markers=[];this.strategyResult=null;this.currentHover=null;this.updateIdentity();this.syncToolbar();
    const preview=this.demoData(symbol,interval);this.kind='demo';this.modeLabel=this.forceDemo?'Synthetic demonstration':'Synthetic preview · connecting';this.series=new CandleSeries(preview,interval);this.chart.setData(this.series.bars,{}, {reset:true});this.refreshIndicators();this.setSource();
    this.demoQuotes.clear();for(const product of this.state.watchlist)this.demoQuotes.set(product,this.previewQuote(product,product===symbol?preview:this.demoData(product,interval)));this.demoQuotes.set(symbol,this.previewQuote(symbol,preview));this.updateAllUI();
    if(this.forceDemo){this.loading=false;this.setFeedStatus({state:'demo',text:'Offline demo · synthetic data'});if(this.state.split)this.openComparison();return;}
    this.market.setSymbols(this.feedSymbols());
    try{
      const cached=await this.cache.get(`${symbol}:${interval}`);if(id!==this.loadId)return;
      if(cached?.bars?.length){this.kind='cache';this.modeLabel='Cached Coinbase history';this.series=new CandleSeries(cached.bars,interval);this.chart.setData(this.series.bars,{}, {reset:true});this.refreshIndicators();this.setSource();this.updateAllUI();}
      const result=await this.market.history(symbol,interval,{signal});if(id!==this.loadId)return;if(!result.bars.length)throw new Error('No candles returned for this symbol.');
      this.kind='market';this.modeLabel='Coinbase Exchange';this.series=new CandleSeries(result.bars,interval);this.series.acceptAfter=result.cutoff;this.chart.setData(this.series.bars,{}, {reset:true});this.refreshIndicators();this.cache.put(`${symbol}:${interval}`,{bars:result.bars,source:result.source});this.setSource();this.updateAllUI();this.loadBook();
      if(this.state.split)this.openComparison();
    }catch(e){if(id!==this.loadId||signal.aborted)return;this.modeLabel=this.kind==='cache'?'Cached history · connection unavailable':'Synthetic demo · connection unavailable';this.setSource();this.toast(`${e.message} ${this.kind==='cache'?'Showing cached history.':'Showing clearly labeled synthetic data.'}`,true);this.updateAllUI();}
    finally{if(id===this.loadId){this.loading=false;this.save(false);}}
  }
  async refreshIndicators(){
    if(this.computationBusy){this.computationAgain=true;return;}if(!this.series)return;this.computationBusy=true;const id=this.loadId,series=this.series,version=series.version;
    try{const data=await this.compute.run('indicators',series.bars);if(id!==this.loadId||series!==this.series)return;this.indicatorData=data;this.chart.setIndicators(data);this.renderIndicatorLegend();this.workbench?.refresh();if(['data','overview'].includes(this.panel))this.renderPanel();}
    catch(e){this.toast('Indicator calculation failed: '+e.message,true);}
    finally{this.computationBusy=false;if(this.computationAgain||series!==this.series||version!==series.version){this.computationAgain=false;this.refreshIndicators();}}
  }
  async loadMore(){if(this.loading||this.loadingMore||this.kind!=='market'||this.moreExhausted||this.replaying||!this.series?.bars.length||this.series.bars.length>180000)return;this.loadingMore=true;const id=this.loadId;try{const old=this.series.bars[0].t,result=await this.market.history(this.state.symbol,this.state.interval,{end:old-1,pages:2,signal:this.abort?.signal});if(id!==this.loadId)return;const earlier=result.bars.filter(b=>b.t<old);if(!earlier.length){this.moreExhausted=true;return;}this.series.merge(earlier);this.chart.setData(this.series.bars);this.refreshIndicators();this.updateBarCount();}catch(e){if(id===this.loadId&&!this.abort?.signal.aborted){this.moreExhausted=true;this.toast('Earlier history unavailable: '+e.message,true);}}finally{this.loadingMore=false;}}
  installFeed(){
    this.market.addEventListener('status',e=>this.setFeedStatus(e.detail));
    this.market.addEventListener('quote',({detail:q})=>{
      const triggered=this.alerts.evaluate(q.symbol,q.price);for(const a of triggered){this.toast(`PRICE ALERT · ${a.symbol} crossed ${formatPrice(a.price)} USD`);if('Notification'in window&&Notification.permission==='granted')new Notification('Aureon price alert',{body:`${a.symbol} crossed ${formatPrice(a.price)} USD`});}
      const fills=this.broker.onQuote(q.symbol,q);for(const f of fills)this.toast(`Paper ${f.side} filled · ${f.quantity} ${f.symbol} @ ${formatPrice(f.fillPrice)}`);
      if(triggered.length||fills.length){this.save(false);if(['alerts','paper'].includes(this.panel))this.renderPanel();}
      this.queueUI();
    });
    this.market.addEventListener('trade',({detail:tick})=>{
      if(tick.symbol===this.state.symbol&&this.kind==='market'&&!this.loading&&this.series){const last=this.series.bars.at(-1)?.t;if(this.series.tick(tick)){this.queueTick();if(this.series.bars.at(-1)?.t!==last)this.reconcile();}}
      if(this.comparisonSeries&&tick.symbol===this.comparisonSymbol&&this.comparisonKind==='market'){if(this.comparisonSeries.tick(tick)){this.comparison?.setData(this.comparisonSeries.bars);this.queueCompareIndicators();}}
      if(tick.symbol===this.state.symbol&&this.depthTab==='trades')this.queueUI();
    });
    this.market.addEventListener('reconnect',()=>{if(this.kind==='market')this.reconcile();});
  }
  queueTick(){if(this.tickTimer)return;this.tickTimer=setTimeout(()=>{this.tickTimer=null;this.chart.setData(this.series.bars);this.refreshIndicators();this.hover(this.visibleBars().at(-1),this.visibleBars().length-1);this.updateBarCount();},100);}
  queueUI(){if(this.uiTimer)return;this.uiTimer=setTimeout(()=>{this.uiTimer=null;this.updateAllUI(false);},250);}
  queueCompareIndicators(){if(this.compareComputeTimer)return;this.compareComputeTimer=setTimeout(async()=>{this.compareComputeTimer=null;const s=this.comparisonSeries,c=this.comparison;if(s&&c){const r=await this.compute.run('indicators',s.bars);if(c===this.comparison&&s===this.comparisonSeries)c.setIndicators(r);}},300);}
  async reconcile(){if(this.reconciling||this.loading||this.kind!=='market')return;this.reconciling=true;const id=this.loadId;
    try{const r=await this.market.history(this.state.symbol,this.state.interval,{pages:1,signal:this.abort?.signal});if(id!==this.loadId)return;const boundary=bucketTime(Date.now()/1000,this.state.interval);const incoming=r.bars.filter(b=>b.t<boundary);this.workbench?.reconcileLiveHistory(incoming);this.series.merge(incoming);this.chart.setData(this.series.bars);this.refreshIndicators();this.cache.put(`${this.state.symbol}:${this.state.interval}`,{bars:this.series.bars,source:'Coinbase Exchange'});}catch{}finally{this.reconciling=false;}
  }
  setFeedStatus(status){this.feedState=status.state;this.feedText=status.text;$('connection-status').textContent=status.text;this.setSource();}
  setSource(){if(!this.series)return;const badge=$('feed-badge');badge.className='feed-badge';let label,text;
    if(this.replaying){if(this.comparison)$('comparison-source').textContent='HISTORICAL REPLAY';label='REPLAY';badge.classList.add('demo');text=`Historical replay · ${this.kind==='demo'?'synthetic sample':this.modeLabel} · no future bars shown`;}
    else if(this.kind==='demo'){label='DEMO';badge.classList.add('demo');text=this.forceDemo?'SYNTHETIC DATA · deterministic offline demo':this.modeLabel;}
    else if(this.kind==='import'){label='IMPORTED';badge.classList.add('demo');text=this.modeLabel+' · historical / imported · no live feed';}
    else if(this.kind==='cache'){label='CACHED';badge.classList.add('stale');text='Cached history · reconnect to refresh';}
    else if(this.feedState==='live'){const q=this.market.quotes.get(this.state.symbol),stale=q&&Date.now()-q.received>20000;label=stale?'STALE':'LIVE';if(stale)badge.classList.add('stale');text=stale?'No recent trade · last quote is stale':'Coinbase live trades · forming candle is provisional';}
    else{label='HISTORY';badge.classList.add('stale');text='Coinbase history · live feed unavailable';}
    badge.textContent=label;$('source-text').textContent=text;$('source-banner').querySelector('.status-dot').style.background=this.kind==='market'&&this.feedState==='live'&&!this.replaying?'var(--up)':'var(--gold)';
    $('watchlist-source').textContent=this.kind==='demo'?'Synthetic sample · not real quotes':this.kind==='market'?'Coinbase public markets · live ticker':'Live watchlist / selected historical chart';$('watchlist-dot').style.background=this.kind==='demo'?'var(--gold)':'var(--up)';
    $('alert-count').textContent=this.alerts.alerts.filter(a=>a.active).length;
  }
  refreshHealth(){if(this.kind==='market'&&this.feedState==='live'){const q=this.market.quotes.get(this.state.symbol);if(q&&Date.now()-q.received>20000){$('feed-badge').textContent='STALE';$('feed-badge').className='feed-badge stale';$('source-text').textContent='No recent trade · latest quote is stale';}else this.setSource();}if(this.depthTab==='book'&&this.kind==='market'&&Date.now()-(this.book?.received||0)>12000)this.loadBook();if(this.panel==='paper')this.updatePaperAccount();}
  metrics(m){if(performance.now()-this.lastMetrics<600)return;this.lastMetrics=performance.now();$('renderer-label').textContent=m.mode;$('render-metrics').textContent=`${m.ms.toFixed(1)} ms · ${compact(m.primitives)} primitives`;}
  updateClock(){const now=new Date();$('header-time').textContent=now.toISOString().slice(11,19)+' UTC';}
  updateIdentity(){const p=this.product(this.state.symbol),short=this.state.symbol.replace('-','');$('toolbar-symbol').textContent=short;$('chart-name').textContent=this.friendlyName(this.state.symbol);$('detail-symbol').textContent=short;$('detail-name').textContent=this.friendlyName(this.state.symbol);$('chart-interval').textContent=TIMEFRAMES.find(x=>x.value===this.state.interval)?.label||'1h';$('volume-unit').textContent=p.short;for(const id of['toolbar-coin','detail-coin']){$(id).textContent=p.short==='BTC'?'₿':p.short==='ETH'?'Ξ':p.short[0];$(id).style.background=p.color;}document.title=`${short} · Aureon Terminal`;}
  product(symbol){return this.products.find(p=>p.id===symbol)||{id:symbol,name:symbol.split('-')[0],short:symbol.split('-')[0],color:'#778cb0'};}
  friendlyName(symbol){const p=this.product(symbol);return`${p.name} / U.S. Dollar`;}
  syncToolbar(){for(const b of document.querySelectorAll('[data-interval]'))b.classList.toggle('active',+b.dataset.interval===this.state.interval);for(const b of document.querySelectorAll('[data-scale]'))b.classList.toggle('active',b.dataset.scale===this.state.scale);$('style-label').textContent=STYLE_NAMES[this.state.style];document.querySelector('[data-action="split"]')?.classList.toggle('active',this.state.split);}
  syncTools(tool){for(const b of document.querySelectorAll('[data-tool]'))b.classList.toggle('active',b.dataset.tool===tool);}
  visibleBars(){return this.replaying?this.series.bars.slice(0,this.chart.endLimit):this.series?.bars||[];}
  hover(bar,index){if(!bar)return;this.currentHover={bar,index};const up=bar.c>=bar.o,css=up?'positive':'negative';$('ohlc-line').innerHTML=[['O',bar.o],['H',bar.h],['L',bar.l],['C',bar.c]].map(([k,v])=>`<span>${k}<b class="${css}">${formatPrice(v)}</b></span>`).join('')+`<span class="${css}">${signed((bar.c/bar.o-1)*100)}%</span>`;
    if(this.indicatorData)this.renderIndicatorLegend(index);if(this.panel==='data'){clearTimeout(this.hoverTimer);this.hoverTimer=setTimeout(()=>this.renderPanel(),40);}}
  renderIndicatorLegend(index){const i=index??(this.replaying?this.chart.endLimit-1:this.series?.bars.length-1);$('indicator-legend').innerHTML=this.state.indicators.filter(k=>INDICATOR_INFO[k].pane==='price').map(k=>{const val=k==='bb'?this.indicatorData?.bb?.mid?.[i]:this.indicatorData?.[k]?.[i],info=INDICATOR_INFO[k];return`<div class="indicator-item" style="color:${info.color}"><span>${info.label}</span><span>${formatPrice(val)}</span><button data-remove-indicator="${k}" title="Remove indicator">✕</button></div>`;}).join('');}
  quote(symbol){if(this.kind==='demo')return this.demoQuotes.get(symbol);if(symbol===this.state.symbol&&(this.kind==='import'||this.kind==='cache'))return this.previewQuote(symbol,this.visibleBars());return this.market.quotes.get(symbol)||(symbol===this.state.symbol?this.previewQuote(symbol,this.visibleBars()):null);}
  renderWatchlist(){const el=$('watchlist');el.innerHTML=this.state.watchlist.map(symbol=>{const p=this.product(symbol);return`<button class="watch-row ${symbol===this.state.symbol?'active':''}" data-select-symbol="${esc(symbol)}" title="${esc(p.name)} · Coinbase USD"><span class="watch-symbol"><i style="background:${p.color}">${p.short==='BTC'?'₿':esc(p.short[0])}</i>${esc(p.short)}<span class="muted tiny">USD</span></span><span class="watch-price" data-quote-price="${esc(symbol)}">—</span><span class="watch-change" data-quote-change="${esc(symbol)}">—</span></button>`;}).join('');this.updateWatchlist();}
  updateWatchlist(){for(const symbol of this.state.watchlist){const q=this.quote(symbol),p=document.querySelector(`[data-quote-price="${CSS.escape(symbol)}"]`),c=document.querySelector(`[data-quote-change="${CSS.escape(symbol)}"]`);if(!p||!c)continue;p.textContent=q?formatPrice(q.price):'—';c.textContent=Number.isFinite(q?.change)?signed(q.change)+'%':'—';c.className=`watch-change ${q?.change>=0?'positive':q?.change<0?'negative':''}`;p.closest('.watch-row').classList.toggle('active',symbol===this.state.symbol);}}
  updateDetails(){const symbol=this.state.symbol,q=this.quote(symbol);if(!q)return;$('detail-price').textContent=formatPrice(q.price);$('detail-change').textContent=Number.isFinite(q.change)?`${signed(q.price-q.open)} (${signed(q.change)}%) ${q.preview?'· sample window':'· 24h'}`:'24h change unavailable';$('detail-change').className='detail-change '+(q.change>=0?'positive':'negative');$('detail-volume').textContent=compact(q.volume);$('detail-percent').textContent=Number.isFinite(q.change)?signed(q.change)+'%':'—';$('detail-percent').className=q.change>=0?'positive':'negative';$('detail-low').textContent=formatPrice(q.low);$('detail-high').textContent=formatPrice(q.high);$('range-marker').style.left=clamp((q.price-q.low)/(q.high-q.low||1)*100,0,100)+'%';$('sell-price').textContent=q.bid>0?formatPrice(q.bid):'—';$('buy-price').textContent=q.ask>0?formatPrice(q.ask):'—';$('session-text').textContent=q.preview?`${this.kind==='demo'?'Synthetic':'Historical'} candle sample · no executable quote`:`Last trade ${new Date(q.time*1000).toISOString().slice(11,19)} UTC`;
    if(!q.preview)document.title=`${formatPrice(q.price)} ${this.state.symbol.replace('-','')} · Aureon Terminal`;
  }
  updateBarCount(){$('bar-count').textContent=`${compact(this.visibleBars().length)} bars${this.chart.lod>1?' · LOD '+this.chart.lod+'×':''}`;}
  updateAllUI(full=true){this.updateWatchlist();this.updateDetails();this.updateBarCount();if(full){this.hover(this.visibleBars().at(-1),this.visibleBars().length-1);this.renderPanel();}else if(this.panel==='overview')this.renderOverview();if(full||this.depthTab==='trades'||this.depthTab==='drawings')this.renderDepth();this.setSource();}
  async loadBook(){if(this.bookLoading||this.kind!=='market'||this.depthTab!=='book')return;this.bookLoading=true;const symbol=this.state.symbol;try{const b=await this.market.book(symbol);if(symbol!==this.state.symbol)return;this.book=b;this.bookError=null;this.renderDepth();}catch(e){this.bookError=e.message;this.renderDepth();}finally{this.bookLoading=false;}}
  renderDepth(){const el=$('depth-content');for(const b of document.querySelectorAll('[data-depth]'))b.classList.toggle('active',b.dataset.depth===this.depthTab);
    if(this.depthTab==='drawings'){el.innerHTML=this.chart.drawings.length?this.chart.drawings.map(d=>`<div class="object-row"><i style="background:${esc(d.color||'#84adfa')}"></i><button class="object-label" data-select-drawing="${esc(d.id)}">${esc(d.type==='text'?d.text:d.type.replace(/^./,x=>x.toUpperCase()))}</button><button data-edit-drawing="${esc(d.id)}" title="Edit drawing">⚙</button><button data-delete-drawing="${esc(d.id)}" title="Delete drawing">✕</button></div>`).join(''):`<div class="empty-state">${icon('layers')}<p>Drawings are anchored to time and price.<br>Choose a tool on the left to begin.</p></div>`;return;}
    if(this.kind==='demo'||this.kind==='import'||this.kind==='cache'){el.innerHTML=`<div class="empty-state">${icon('depth')}<p>${this.kind==='demo'?'Synthetic demo does not invent an order book.':'No live depth for this historical dataset.'}</p><button class="secondary-button" data-action="reconnect">Connect live data</button></div>`;return;}
    if(this.depthTab==='trades'){const rows=this.market.trades.filter(t=>t.symbol===this.state.symbol).slice(0,30);el.innerHTML='<div class="snapshot-note">Real executions · color is opposite reported maker side</div><div class="depth-labels"><span>Price (USD)</span><span>Size</span><span>Time UTC</span></div>'+rows.map(t=>`<div class="book-row"><span class="${t.side==='sell'?'positive':'negative'}">${formatPrice(t.price)}</span><span>${t.size.toFixed(5)}</span><span class="muted">${new Date(t.time*1000).toISOString().slice(11,19)}</span></div>`).join('')+(rows.length?'':'<div class="empty-state">Waiting for the next execution…</div>');return;}
    if(!this.book){el.innerHTML=`<div class="empty-state">${icon('depth')}<p>${esc(this.bookError||'Loading public order-book snapshot…')}</p></div>`;return;}
    const {bids,asks,received}=this.book,volume=Math.max(...bids.map(x=>x.size),...asks.map(x=>x.size),1),row=(b,side)=>`<div class="book-row" style="--depth:${Math.round(b.size/volume*100)}%;--depth-color:${side==='bid'?'#25bd9c13':'#ef647013'}"><span class="${side==='bid'?'positive':'negative'}">${formatPrice(b.price)}</span><span>${b.size.toFixed(5)}</span><span class="muted">${compact(b.price*b.size)}</span></div>`;
    el.innerHTML=`<div class="snapshot-note">REST snapshot · ${new Date(received).toISOString().slice(11,19)} UTC · ~12s refresh</div><div class="depth-labels"><span>Price (USD)</span><span>Size</span><span>Total (USD)</span></div>${asks.slice(0,5).reverse().map(b=>row(b,'ask')).join('')}<div class="book-mid">${formatPrice(this.market.quotes.get(this.state.symbol)?.price)} <span class="muted tiny">spread ${bids[0]&&asks[0]?formatPrice(asks[0].price-bids[0].price):'—'}</span></div>${bids.slice(0,5).map(b=>row(b,'bid')).join('')}`;
  }
  drawingChanged(before,after){this.history.push({symbol:this.state.symbol,drawings:before},{symbol:this.state.symbol,drawings:after});this.state.drawings[this.state.symbol]=after;this.chart.drawings=after;this.renderDepth();this.save(false);}
  restoreDrawings(value){if(!value)return;this.state.drawings[value.symbol]=value.drawings;if(value.symbol===this.state.symbol){this.chart.drawings=value.drawings;this.chart.selected=null;this.chart.invalidate();}this.renderDepth();this.save(false);}
  setPanel(name){this.panel=name;this.workbench?.onPanel(name);for(const b of document.querySelectorAll('[data-panel]'))b.classList.toggle('active',b.dataset.panel===name);$('analysis-panel').classList.remove('minimized');this.renderPanel();}
  renderPanel(){if(!this.series)return;if(this.workbench?.renderPanel())return;if(this.panel==='overview')this.renderOverview();else if(this.panel==='strategy')this.renderStrategy();else if(this.panel==='paper')this.renderPaper();else if(this.panel==='data')this.renderDataWindow();else this.renderAlerts();}
  renderOverview(){const bars=this.visibleBars();if(!bars.length)return;const first=bars[0],last=bars.at(-1),change=(last.c/first.o-1)*100;let high=-Infinity,low=Infinity,volume=0;for(const b of bars){high=Math.max(high,b.h);low=Math.min(low,b.l);volume+=b.v;}const i=bars.length-1,rsi=this.indicatorData?.rsi?.[i],atr=this.indicatorData?.atr?.[i];
    $('panel-content').innerHTML=`<div class="overview"><div class="overview-heading"><span class="eyebrow">${esc(this.state.symbol)} · loaded history</span><span class="data-tag">${this.kind==='demo'?'SYNTHETIC SAMPLE':this.kind==='import'?'IMPORTED DATA':'COINBASE EXCHANGE'}</span></div><div class="stat-cards"><div class="stat-card"><div class="stat-card-label">Window return</div><div class="stat-card-value ${change>=0?'positive':'negative'}">${signed(change)}<span style="font-size:13px">%</span></div><div class="stat-card-note">First open → latest close</div></div><div class="stat-card"><div class="stat-card-label">Window volume</div><div class="stat-card-value">${compact(volume)} <span class="tiny muted">${esc(this.product(this.state.symbol).short)}</span></div><div class="stat-card-note">${bars.length.toLocaleString()} observed candles</div></div><div class="stat-card"><div class="stat-card-label">Relative strength · RSI 14</div><div class="stat-card-value" style="color:#b698ed">${Number.isFinite(rsi)?rsi.toFixed(2):'—'}</div><div class="stat-card-note">${rsi>70?'Above 70 threshold':rsi<30?'Below 30 threshold':'Between 30 and 70 thresholds'}</div></div><div class="stat-card"><div class="stat-card-label">Average true range · ATR 14</div><div class="stat-card-value">${formatPrice(atr)}</div><div class="stat-card-note">Wilder smoothing · USD</div></div></div><div class="overview-note"><span class="status-dot"></span>${new Date(first.t*1000).toISOString().slice(0,10)} → ${new Date(last.t*1000).toISOString().slice(0,10)}<span class="muted">&nbsp;|&nbsp; Range ${formatPrice(low)} — ${formatPrice(high)}</span><span class="header-spacer"></span><button data-action="show-data" class="muted">Inspect data ↗</button></div></div>`;
  }
  renderStrategy(){const r=this.strategyResult;$('panel-content').innerHTML=`<div class="panel-pad"><form id="strategy-form" class="panel-toolbar"><h3>EMA crossover · long only</h3><label>Fast <input name="fast" type="number" min="2" max="500" value="${r?.assumptions.fast||12}" required></label><label>Slow <input name="slow" type="number" min="3" max="1000" value="${r?.assumptions.slow||26}" required></label><label>Fee (bps) <input name="feeBps" type="number" min="0" max="1000" value="${r?.assumptions.feeBps??10}" required></label><label>Slippage <input name="slippageBps" type="number" min="0" max="1000" value="${r?.assumptions.slippageBps??5}" required></label><button class="primary-button" type="submit" id="run-strategy">Run backtest</button>${r?'<button type="button" class="secondary-button" data-action="export-trades">Export trades</button>':''}</form><div class="small-note">Signals use the previous closed candle; fills occur at the next open. $100,000 initial capital, 100% cash allocation. No leverage. Final open positions are marked to close, not artificially liquidated. ${this.kind==='demo'?'<span class="demo-watermark">SYNTHETIC DATA</span>':''}</div>${r?`<div class="result-summary"><div class="result-stat"><span>Net P&L</span><b class="${r.net>=0?'positive':'negative'}">$${formatPrice(r.net)}</b></div><div class="result-stat"><span>Return</span><b>${signed(r.returnPct)}%</b></div><div class="result-stat"><span>Max drawdown</span><b class="negative">${r.maxDrawdownPct.toFixed(2)}%</b></div><div class="result-stat"><span>Closed trades</span><b>${r.trades.length}</b></div><div class="result-stat"><span>Win rate</span><b>${r.winRate.toFixed(1)}%</b></div><div class="result-stat"><span>Open position</span><b>${r.openPosition?'Yes':'None'}</b></div></div><canvas class="equity-mini" id="equity-chart" aria-label="Strategy equity curve"></canvas><table class="report-table"><thead><tr><th>Entry (UTC)</th><th>Exit (UTC)</th><th class="num">Entry price</th><th class="num">Exit price</th><th class="num">P&L after costs</th></tr></thead><tbody>${r.trades.slice().reverse().map(t=>`<tr><td>${new Date(t.t*1000).toISOString().slice(0,16)}</td><td>${new Date(t.exitTime*1000).toISOString().slice(0,16)}</td><td class="num">${formatPrice(t.price)}</td><td class="num">${formatPrice(t.exitPrice)}</td><td class="num ${t.pnl>=0?'positive':'negative'}">${formatPrice(t.pnl)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><p>Run the strategy against loaded OHLCV data.<br>Costs, execution timing, trades, and equity are computed—not prefilled.</p></div>'}</div>`;if(r)this.drawEquity(r.equity);}
  drawEquity(points){const canvas=$('equity-chart');if(!canvas)return;const w=canvas.clientWidth,h=72,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);let lo=Infinity,hi=-Infinity;for(const p of points){lo=Math.min(lo,p.value);hi=Math.max(hi,p.value);}ctx.strokeStyle='#77a1ff';ctx.lineWidth=1.5;ctx.beginPath();for(let i=0;i<points.length;i++){const x=8+i/(points.length-1)*(w-16),y=8+(hi-points[i].value)/(hi-lo||1)*(h-16);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}
  async runStrategy(form){const f=new FormData(form),options=Object.fromEntries([...f].map(([k,v])=>[k,Number(v)]));$('run-strategy').disabled=true;$('run-strategy').textContent='Calculating…';const id=this.loadId;try{const result=await this.compute.run('backtest',this.visibleBars(),options);if(id!==this.loadId)return;this.strategyResult=result;this.chart.markers=result.markers;this.chart.invalidate();this.renderStrategy();}catch(e){this.toast(e.message,true);$('run-strategy').disabled=false;$('run-strategy').textContent='Run backtest';}}
  renderPaper(){const fresh=this.kind==='market'&&!this.replaying;$('panel-content').innerHTML=`<div class="panel-pad paper-layout"><form class="paper-ticket" id="paper-form"><h3>${esc(this.state.symbol)} <span class="tab-tag">PAPER ONLY</span></h3><div class="segmented"><button type="button" data-paper-side="buy" class="${this.paperSide==='buy'?'active':''}">Buy</button><button type="button" data-paper-side="sell" class="${this.paperSide==='sell'?'active':''}">Sell</button></div><div class="form-row"><label>Order type<select name="type" id="paper-type"><option value="market">Market</option><option value="limit">Limit</option><option value="stop">Stop market</option></select></label><label>Quantity (${esc(this.product(this.state.symbol).short)})<input name="quantity" type="number" min="0.00000001" step="any" value="0.01" required></label></div><div class="form-row" id="paper-price-row" hidden><label>Trigger / limit price (USD)<input name="price" type="number" min="0.00000001" step="any" value="${this.quote(this.state.symbol)?.price||0}"></label></div><button class="primary-button" type="submit" ${fresh?'':'disabled'}>${this.paperSide==='buy'?'Buy':'Sell'} · paper order</button><div class="small-note">${fresh?'Market fills require a live bid/ask less than 15s old. Fee: 10 bps.':'Connect live data and exit replay to place paper orders.'} Browser-local, long-only spot. Open orders do not reserve funds; insufficient funds at trigger cause rejection. No real order is sent.</div></form><div class="paper-account" id="paper-account"></div></div>`;this.updatePaperAccount();}
  updatePaperAccount(){const el=$('paper-account');if(!el)return;const s=this.broker.state,equity=this.broker.equity(this.market.quotes),positions=Object.entries(s.positions).filter(([,p])=>p.qty>1e-10),orders=s.orders.slice(-50).reverse();el.innerHTML=`<div class="account-head"><h3>Local paper account</h3><button data-action="reset-paper">Reset account</button></div><div class="result-summary"><div class="result-stat"><span>Cash (USD)</span><b>${formatPrice(s.cash)}</b></div><div class="result-stat"><span>Equity · last available marks</span><b>${formatPrice(equity)}</b></div><div class="result-stat"><span>Total return</span><b class="${equity>=s.initial?'positive':'negative'}">${signed((equity/s.initial-1)*100)}%</b></div></div><table class="report-table"><thead><tr><th>Position</th><th class="num">Quantity</th><th class="num">Avg cost incl. fees</th><th class="num">Realized P&L</th></tr></thead><tbody>${positions.map(([symbol,p])=>`<tr><td>${esc(symbol)}</td><td class="num">${p.qty.toFixed(6)}</td><td class="num">${formatPrice(p.cost/p.qty)}</td><td class="num">${formatPrice(p.realized)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">No open positions.</td></tr>'}</tbody></table>${orders.length?`<table class="report-table"><thead><tr><th>Pending / historical orders</th><th>Type</th><th>Quantity</th><th>Trigger</th><th>Status</th><th></th></tr></thead><tbody>${orders.map(o=>`<tr><td>${esc(o.side)} ${esc(o.symbol)}</td><td>${esc(o.type)}</td><td>${o.quantity}</td><td>${formatPrice(o.price)}</td><td title="${esc(o.reason||'')}">${esc(o.status)}</td><td>${o.status==='open'?`<button data-cancel-order="${esc(o.id)}">Cancel</button>`:''}</td></tr>`).join('')}</tbody></table>`:''}<table class="report-table"><thead><tr><th>Recent fills</th><th>Quantity</th><th>Price</th><th>Fee</th></tr></thead><tbody>${s.fills.slice(0,15).map(f=>`<tr><td>${esc(f.side)} ${esc(f.symbol)}</td><td>${f.quantity}</td><td>${formatPrice(f.fillPrice)}</td><td>${formatPrice(f.fee)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">No fills. Paper execution is disabled without a fresh live quote.</td></tr>'}</tbody></table>`;}
  placePaper(form){if(this.kind!=='market'||this.replaying)throw new Error('Paper execution requires live market mode, outside bar replay.');const f=new FormData(form),order=this.broker.place({symbol:this.state.symbol,side:this.paperSide,type:f.get('type'),quantity:Number(f.get('quantity')),price:Number(f.get('price'))},this.market.quotes.get(this.state.symbol));this.save(false);this.toast(order.status==='filled'?`Paper ${order.side} filled at ${formatPrice(order.fillPrice)} USD.`:'Paper order queued. It is monitored only while this application is open.');this.updatePaperAccount();}
  renderDataWindow(){const bars=this.visibleBars(),i=clamp(this.currentHover?.index??bars.length-1,0,bars.length-1),b=bars[i];if(!b)return;const rows=[['Symbol',this.state.symbol],['Data provenance',this.exportLabel()],['Candle open (UTC)',new Date(b.t*1000).toISOString()],['Open',formatPrice(b.o,8)],['High',formatPrice(b.h,8)],['Low',formatPrice(b.l,8)],['Close',formatPrice(b.c,8)],['Volume (base units)',formatPrice(b.v,8)],['Candle status',b.partial?'Provisional / partial':'Historical']];for(const key of this.state.indicators){const v=key==='bb'?this.indicatorData?.bb?.mid?.[i]:key==='macd'?this.indicatorData?.macd?.line?.[i]:key==='stoch'?this.indicatorData?.stoch?.k?.[i]:this.indicatorData?.[key]?.[i];rows.push([INDICATOR_INFO[key].label,formatPrice(v,6)]);}$('panel-content').innerHTML=`<div class="panel-pad"><div class="panel-toolbar"><h3>Data window</h3><span class="small-note">Move the crosshair to inspect a bar · raw OHLCV (not Heikin-Ashi)</span><div class="header-spacer"></div><button class="secondary-button" data-action="export-csv">Export OHLCV</button></div><table class="report-table"><tbody>${rows.map(([k,v])=>`<tr><td class="muted">${esc(k)}</td><td class="mono">${esc(v)}</td></tr>`).join('')}</tbody></table></div>`;}
  renderAlerts(){$('panel-content').innerHTML=`<div class="panel-pad"><div class="panel-toolbar"><h3>Price alerts</h3><span class="small-note">Crossing triggers · monitored only while the app and feed are running.</span><div class="header-spacer"></div><button class="secondary-button" data-action="notifications">Enable notifications</button><button class="primary-button" data-action="alert">Create alert</button></div>${this.alerts.alerts.map(a=>`<div class="alerts-row">${icon('alert')}<div class="alert-desc">${esc(a.symbol)} · ${esc(a.direction)} ${formatPrice(a.price)} USD<small>${a.triggered?'Triggered '+new Date(a.triggered).toISOString():'Created '+new Date(a.created).toISOString()}</small></div><span class="alert-pill ${a.active?'':'triggered'}">${a.active?'Watching':'Triggered'}</span><button data-remove-alert="${esc(a.id)}" title="Remove alert">✕</button></div>`).join('')||'<div class="empty-state"><p>No alerts yet. Set a price level to watch for a crossing.</p></div>'}</div>`;}
  installEvents(){
    document.addEventListener('click',async e=>{
      const b=e.target.closest('button,[data-action]');if(!b||b.disabled)return;
      try{
        if(b.dataset.selectSymbol){const symbol=b.dataset.selectSymbol;if(this.searchMode==='compare'&&$('modal').open){this.comparisonSymbol=symbol;this.closeModal();await this.openComparison();}else{this.closeModal();if(!this.state.watchlist.includes(symbol)){this.state.watchlist.push(symbol);this.renderWatchlist();}await this.loadSymbol(symbol);}return;}
        if(b.dataset.interval){this.closePopup();this.changeInterval(+b.dataset.interval);return;}
        if(b.dataset.style){this.closePopup();this.state.style=b.dataset.style;this.chart.setStyle(this.state.style,this.workbench?.config.typeOptions);this.syncToolbar();this.save(false);return;}
        if(b.dataset.tool){this.chart.setTool(b.dataset.tool);return;}
        if(b.dataset.scale){this.state.scale=this.state.scale===b.dataset.scale&&b.dataset.scale!=='linear'?'linear':b.dataset.scale;this.chart.scale=this.state.scale;this.chart.manualRange=null;this.chart.invalidate();this.syncToolbar();this.save(false);return;}
        if(b.dataset.range){if(b.dataset.range==='all')this.chart.fitAll();else{const bars=Math.round(+b.dataset.range/this.state.interval);this.chart.count=clamp(bars,15,Math.max(30,this.series.bars.length+10));this.chart.right=this.chart.length+4;this.chart.manualRange=null;this.chart.invalidate();this.chart.emitView();}return;}
        if(b.dataset.panel){this.setPanel(b.dataset.panel);return;}
        if(b.dataset.depth){this.depthTab=b.dataset.depth;this.renderDepth();if(this.depthTab==='book')this.loadBook();return;}
        if(b.dataset.removeIndicator){this.toggleIndicator(b.dataset.removeIndicator,false);return;}
        if(b.dataset.paperSide){this.paperSide=b.dataset.paperSide;this.renderPaper();return;}
        if(b.dataset.side){this.paperSide=b.dataset.side;this.setPanel('paper');return;}
        if(b.dataset.cancelOrder){this.broker.cancel(b.dataset.cancelOrder);this.save(false);this.updatePaperAccount();return;}
        if(b.dataset.removeAlert){this.alerts.alerts=this.alerts.alerts.filter(a=>a.id!==b.dataset.removeAlert);this.setSource();this.renderAlerts();this.save(false);return;}
        if(b.dataset.selectDrawing){this.chart.selected=b.dataset.selectDrawing;this.chart.invalidate();return;}
        if(b.dataset.deleteDrawing){this.chart.selected=b.dataset.deleteDrawing;this.chart.deleteSelected();return;}
        if(b.dataset.editDrawing){this.editDrawing(b.dataset.editDrawing);return;}
        if(b.dataset.action)await this.action(b.dataset.action,b,e);
      }catch(error){this.toast(error.message||String(error),true);}
    });
    document.addEventListener('change',e=>{const t=e.target;try{
      if(t.dataset.indicator)this.toggleIndicator(t.dataset.indicator,t.checked);
      if(t.id==='theme-select')this.setTheme(t.value);
      if(t.id==='paper-type')$('paper-price-row').hidden=t.value==='market';
      if(t.id==='replay-speed'&&this.replayTimer){this.pauseReplay();this.playReplay();}
      if(t.id==='settings-scale'){this.state.scale=t.value;this.chart.scale=t.value;this.chart.manualRange=null;this.chart.invalidate();this.syncToolbar();this.save(false);}
    }catch(error){this.toast(error.message,true);}});
    document.addEventListener('input',e=>{if(e.target.id==='symbol-search')this.renderSymbolResults(e.target.value);if(e.target.id==='replay-position'){this.pauseReplay();this.seekReplay(+e.target.value);}});
    document.addEventListener('submit',async e=>{e.preventDefault();try{if(e.target.id==='strategy-form')await this.runStrategy(e.target);if(e.target.id==='paper-form')this.placePaper(e.target);if(e.target.id==='alert-form')this.createAlert(e.target);if(e.target.id==='drawing-form')this.saveDrawing(e.target);}catch(error){this.toast(error.message,true);}});
    document.addEventListener('pointerdown',e=>{if(!e.target.closest('#popup-menu')&&!e.target.closest('[data-action]'))this.closePopup();});
    document.addEventListener('keydown',e=>this.key(e));
    $('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.closeModal();}});
    $('file-input').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>30_000_000)throw new Error('File exceeds the 30 MB limit.');await this.importFile(file);}catch(error){this.toast(error.message,true);}finally{e.target.value='';}});
    const resizer=$('panel-resizer');resizer.addEventListener('pointerdown',e=>{const start=e.clientY,height=$('analysis-panel').getBoundingClientRect().height;resizer.setPointerCapture(e.pointerId);const move=event=>{document.documentElement.style.setProperty('--analysis',clamp(height+start-event.clientY,90,window.innerHeight-300)+'px');$('analysis-panel').classList.remove('minimized');};const end=()=>{resizer.removeEventListener('pointermove',move);resizer.removeEventListener('pointerup',end);resizer.removeEventListener('pointercancel',end);};resizer.addEventListener('pointermove',move);resizer.addEventListener('pointerup',end);resizer.addEventListener('pointercancel',end);});
    resizer.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const h=$('analysis-panel').getBoundingClientRect().height;document.documentElement.style.setProperty('--analysis',clamp(h+(e.key==='ArrowUp'?20:-20),90,window.innerHeight-300)+'px');}});
  }
  async action(name,button){this.closePopup();switch(name){
    case 'search':this.openSearch();break;case 'compare':this.openSearch('compare');break;case 'close-modal':this.closeModal();break;
    case 'indicators':this.workbench?this.workbench.openStudies():this.openIndicators();break;case 'settings':this.openSettings();break;case 'help':this.openHelp();break;
    case 'save':this.save(true);break;case 'undo':this.restoreDrawings(this.history.undo());break;case 'redo':this.restoreDrawings(this.history.redo());break;
    case 'timeframes':this.popup(button,TIMEFRAMES.map(t=>({label:t.label,interval:t.value,active:this.state.interval===t.value})));break;
    case 'chart-style':this.popup(button,Object.entries(STYLE_NAMES).map(([style,label])=>({label,style,active:this.state.style===style})));break;
    case 'split':if(this.workbench?.config.layout>1){await this.workbench.setLayout(1);break;}if(this.state.split)this.closeComparison();else await this.openComparison();break;
    case 'alert':this.openAlert(button.dataset.price?+button.dataset.price:undefined);break;
    case 'show-alerts':this.setPanel('alerts');break;case 'show-data':this.setPanel('data');break;case 'show-objects':this.depthTab='drawings';$('right-sidebar').hidden=false;this.renderDepth();break;
    case 'snapshot':{const blob=await this.chart.snapshot();if(!blob)throw new Error('Chart export failed.');this.download(blob,`aureon-${this.state.symbol}.png`);this.toast('Chart PNG exported.');break;}
    case 'fullscreen':if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();break;
    case 'zoom-out':this.chart.zoom(1.25);break;case 'zoom-in':this.chart.zoom(.8);break;case 'fit':this.chart.fit();break;case 'latest':this.chart.right=this.chart.length+6;this.chart.invalidate();this.chart.emitView();break;
    case 'snap':this.chart.snap=!this.chart.snap;button.classList.toggle('active',this.chart.snap);this.toast(this.chart.snap?'Snapping to candle OHLC enabled.':'Snapping disabled.');break;
    case 'lock':this.chart.locked=!this.chart.locked;button.classList.toggle('active',this.chart.locked);this.toast(this.chart.locked?'Drawing edits locked.':'Drawing edits unlocked.');break;
    case 'hide-drawings':this.chart.drawingsVisible=!this.chart.drawingsVisible;button.classList.toggle('active',!this.chart.drawingsVisible);this.chart.invalidate();break;
    case 'delete-drawing':if(this.chart.selected)this.chart.deleteSelected();else this.toast('Select a drawing first, or use Objects to manage drawings.');break;
    case 'reconnect':this.forceDemo=false;this.market.closed=false;this.market.connect(this.feedSymbols());await this.loadSymbol(this.state.symbol,this.state.interval);break;
    case 'toggle-panel':$('analysis-panel').classList.toggle('minimized');break;case 'sidebar':$('right-sidebar').hidden=!$('right-sidebar').hidden;break;
    case 'replay':if(this.replaying)this.stopReplay();else this.startReplay();break;case 'replay-play':if(this.replayTimer)this.pauseReplay();else this.playReplay();break;case 'replay-step':this.pauseReplay();this.seekReplay(Math.min(this.series.bars.length,this.chart.endLimit+1));break;
    case 'layout-menu':case 'export-menu':this.popup(button,[{label:'Save workspace',action:'save',hint:'⌘ S'},{label:'Export workspace + OHLCV',action:'export-workspace'},{label:'Import workspace / CSV',action:'import'},{label:'Export OHLCV as CSV',action:'export-csv'},{label:'Export chart as PNG',action:'snapshot'},null,{label:'Workspace settings',action:'settings'},{label:'Use synthetic offline demo',action:'demo'}]);break;
    case 'watchlist-menu':this.popup(button,[{label:'Add / search symbol',action:'search'},{label:'Remove current from watchlist',action:'remove-watch'},{label:'Reset default watchlist',action:'reset-watch'}]);break;
    case 'remove-watch':this.state.watchlist=this.state.watchlist.filter(s=>s!==this.state.symbol);this.renderWatchlist();this.save(false);break;
    case 'reset-watch':this.state.watchlist=DEFAULT.watchlist.slice();this.renderWatchlist();this.save(false);break;
    case 'import':$('file-input').click();break;case 'export-csv':this.download(new Blob([toCSV(this.visibleBars())],{type:'text/csv'}),`${this.state.symbol}-${this.state.interval}s-${this.kind}.csv`);break;
    case 'export-workspace':this.exportWorkspace();break;
    case 'export-trades':if(this.strategyResult){const r=this.strategyResult;this.download(new Blob(['entry_time,exit_time,entry_price,exit_price,quantity,pnl\n'+r.trades.map(t=>[new Date(t.t*1000).toISOString(),new Date(t.exitTime*1000).toISOString(),t.price,t.exitPrice,t.quantity,t.pnl].join(',')).join('\n')],{type:'text/csv'}),'aureon-strategy-trades.csv');}break;
    case 'demo':this.forceDemo=true;this.market.dispose();this.closeModal();await this.loadSymbol(this.state.symbol,this.state.interval);break;
    case 'load-symbols':button.disabled=true;button.textContent='Loading Coinbase products…';try{const products=await this.market.listProducts();const map=new Map([...PRODUCTS,...products].map(p=>[p.id,p]));for(const p of PRODUCTS)map.set(p.id,p);this.products=[...map.values()];this.renderSymbolResults($('symbol-search')?.value||'');button.textContent=`${this.products.length} USD pairs available`;}catch(e){button.textContent='Try loading available pairs again';button.disabled=false;throw e;}break;
    case 'notifications':if(!('Notification'in window))throw new Error('Notifications are unavailable in this browser.');this.toast('Browser notification permission: '+await Notification.requestPermission());break;
    case 'reset-paper':this.openModal('Reset paper account','<div class="warning-note">This deletes the local paper account’s orders, fills, and positions and restores $100,000 of simulated cash. It does not affect real funds.</div><div class="modal-footer"><button class="secondary-button" data-action="close-modal">Cancel</button><button class="danger-button" data-action="confirm-reset-paper">Reset paper account</button></div>');break;
    case 'confirm-reset-paper':this.broker=new PaperBroker();this.closeModal();this.save(false);this.renderPaper();this.toast('Paper account reset to $100,000.');break;
    case 'hline-at':{const p=+button.dataset.price;this.chart.commitDrawing({id:uid(),type:'hline',points:[{t:this.visibleBars().at(-1).t,p}],color:'#84adfa'});break;}
  }}
  key(e){if(e.key==='Escape'){this.closePopup();this.chart.pending=null;this.chart.setTool('cursor');return;}const editing=e.target.closest('input,textarea,select,[contenteditable]');if(editing)return;
    const mod=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(mod&&key==='k'){e.preventDefault();this.openSearch();return;}if(mod&&key==='s'){e.preventDefault();this.save(true);return;}if(mod&&key==='z'){e.preventDefault();this.restoreDrawings(e.shiftKey?this.history.redo():this.history.undo());return;}if(mod&&key==='y'){e.preventDefault();this.restoreDrawings(this.history.redo());return;}if($('modal').open||mod||e.altKey)return;
    if(key==='delete'||key==='backspace'){e.preventDefault();this.chart.deleteSelected();return;}if(key==='i')this.openIndicators();else if(key==='a')this.openAlert();else if(key==='r'){e.preventDefault();this.replaying?this.stopReplay():this.startReplay();}else if(key==='t')this.chart.setTool('trend');else if(key==='h')this.chart.setTool('hline');else if(key==='f')this.chart.setTool('fib');else if(key==='v')this.chart.setTool('cursor');else if(key==='m')document.querySelector('[data-action="snap"]').click();else if(key==='?'||key==='/'){e.preventDefault();key==='?'?this.openHelp():this.openSearch();}
  }
  changeInterval(interval){if(this.kind==='import'&&this.importedBars){if(interval<this.importedInterval||interval%this.importedInterval!==0)throw new Error(`Imported data has ${this.importedInterval}s bars; it cannot be upsampled into real smaller candles.`);this.state.interval=interval;this.chart.interval=interval;this.series=new CandleSeries(this.importedBars,interval);if(interval>this.importedInterval)this.series=new CandleSeries(this.aggregateImported(interval),interval);this.chart.setData(this.series.bars,{}, {reset:true});this.refreshIndicators();this.updateIdentity();this.syncToolbar();this.updateAllUI();this.save(false);}else this.loadSymbol(this.state.symbol,interval);}
  aggregateImported(interval){const out=[];for(const c of this.importedBars){const t=bucketTime(c.t,interval);let b=out.at(-1);if(!b||b.t!==t)out.push({t,o:c.o,h:c.h,l:c.l,c:c.c,v:c.v});else{b.h=Math.max(b.h,c.h);b.l=Math.min(b.l,c.l);b.c=c.c;b.v+=c.v;}}return out;}
  popup(anchor,items,position){const r=anchor?.getBoundingClientRect?.()||{left:position?.x||100,bottom:position?.y||100};const el=$('popup-menu');el.innerHTML=items.map(item=>item?`<button ${item.action?`data-action="${item.action}"`:''} ${item.style?`data-style="${item.style}"`:''} ${item.interval?`data-interval="${item.interval}"`:''} ${item.price!=null?`data-price="${item.price}"`:''} class="${item.active?'active':''}">${esc(item.label)}${item.hint?`<span>${esc(item.hint)}</span>`:''}</button>`:'<hr>').join('');el.hidden=false;const box=el.getBoundingClientRect();el.style.left=clamp(r.left,6,window.innerWidth-box.width-6)+'px';el.style.top=clamp(r.bottom+4,6,window.innerHeight-box.height-6)+'px';}
  closePopup(){$('popup-menu').hidden=true;}
  chartMenu(p){this.popup(null,[{label:`Alert at ${formatPrice(p.price)}`,action:'alert',price:p.price},{label:'Add horizontal line here',action:'hline-at',price:p.price},null,{label:'Reset chart view',action:'fit'},{label:'Chart settings',action:'settings'},{label:'Export chart PNG',action:'snapshot'}],p);}
  openModal(title,content){this.closePopup();$('modal-title').textContent=title;$('modal-content').innerHTML=content;if(!$('modal').open)$('modal').showModal();}
  closeModal(){if($('modal').open)$('modal').close();this.searchMode=null;}
  openSearch(mode='primary'){this.searchMode=mode;this.openModal(mode==='compare'?'Compare markets':'Symbol search',`<div class="modal-search">${icon('search')}<input id="symbol-search" autocomplete="off" placeholder="Search symbol or asset name" aria-label="Search market symbols"></div><div class="search-filters"><span class="active">Crypto</span><span>USD spot</span><span>Coinbase Exchange</span></div><div id="symbol-results" class="symbol-results"></div><div class="modal-footer"><button class="secondary-button" data-action="load-symbols">Load all available Coinbase USD pairs</button></div><p class="small-note">Stocks, futures, and forex can be analyzed through OHLCV CSV import. This app does not fabricate exchange entitlements or provide unauthenticated licensed feeds.</p>`);this.renderSymbolResults('');setTimeout(()=>$('symbol-search')?.focus(),30);}
  renderSymbolResults(query){const text=query.trim().toLowerCase(),items=this.products.filter(p=>p.id.toLowerCase().includes(text)||p.name.toLowerCase().includes(text)).slice(0,120);$('symbol-results').innerHTML=items.map(p=>`<button class="symbol-result" data-select-symbol="${esc(p.id)}"><span class="asset-coin" style="background:${p.color}">${p.short==='BTC'?'₿':esc(p.short[0])}</span><span><b>${esc(p.id.replace('-',''))}</b><small>${esc(p.name)} / U.S. Dollar</small></span><span class="exchange-tag">COINBASE · CRYPTO</span></button>`).join('')||'<div class="empty-state">No matching symbols. Load all Coinbase USD pairs or import CSV.</div>';}
  openIndicators(){const desc={ema:'Exponential moving average · SMA seed',sma:'Simple moving average · 50 closes',bb:'Population standard deviation bands',vwap:'Volume-weighted typical price · resets at 00:00 UTC',rsi:'Relative strength · Wilder smoothing',macd:'EMA 12 − EMA 26 · signal EMA 9',atr:'Average true range · Wilder 14',stoch:'14-bar range · %D SMA 3',obv:'Cumulative signed base-asset volume'};this.openModal('Indicators & technical studies',`<p class="small-note">Calculated from source OHLCV in a dedicated worker. Warm-up values remain empty; indicators never use future bars.</p>${Object.entries(INDICATOR_INFO).map(([key,info])=>`<label class="indicator-option"><input type="checkbox" data-indicator="${key}" ${this.state.indicators.includes(key)?'checked':''}><span class="indicator-swatch" style="background:${info.color}"></span><span><b>${info.label}</b><small>${desc[key]}</small></span><span class="indicator-location">${info.pane==='price'?'Overlay':'Separate pane'}</span></label>`).join('')}<div class="modal-footer"><button class="primary-button" data-action="close-modal">Done</button></div>`);}
  toggleIndicator(key,enabled){if(!INDICATOR_INFO[key])return;this.state.indicators=enabled?[...new Set([...this.state.indicators,key])]:this.state.indicators.filter(x=>x!==key);this.chart.enabled=[...this.state.indicators];this.chart.manualRange=null;this.chart.invalidate();this.renderIndicatorLegend();this.save(false);}
  openSettings(){this.openModal('Workspace settings',`<div class="settings-section"><h3>Appearance</h3><div class="settings-row"><label for="theme-select">Color theme</label><select id="theme-select"><option value="dark" ${this.state.theme==='dark'?'selected':''}>Graphite dark</option><option value="light" ${this.state.theme==='light'?'selected':''}>Studio light</option></select></div><div class="settings-row"><label for="settings-scale">Price scale</label><select id="settings-scale"><option value="linear" ${this.state.scale==='linear'?'selected':''}>Linear / auto</option><option value="log" ${this.state.scale==='log'?'selected':''}>Logarithmic</option><option value="percent" ${this.state.scale==='percent'?'selected':''}>Percentage</option></select></div></div><div class="settings-section"><h3>Renderer diagnostics</h3><p class="small-note">Backend: <strong>${esc(this.chart.renderer.mode)}</strong><br>${this.chart.renderer.reason?'Fallback reason: '+esc(this.chart.renderer.reason)+'<br>':''}Instanced rectangles and lines; visible-range OHLC aggregation; float64 CPU calculations; viewport-relative GPU coordinates. Text and crosshair labels use a high-DPI Canvas overlay. Device loss switches safely to Canvas 2D.</p></div><div class="settings-section"><h3>Data & time</h3><p class="small-note">All candle timestamps and session boundaries are UTC. Missing market intervals stay missing, not fabricated. The current live candle is provisional and finalized candles are reconciled from REST. Watchlists and candles may update at different moments. Percentage scales use the first visible close.</p></div><div class="settings-section"><h3>Local storage</h3><p class="small-note">Workspace, drawings, alerts and the paper ledger are saved in this browser. Cached OHLCV uses IndexedDB. Export a workspace for a portable copy. No account, broker key, or cloud synchronization is required.</p></div><div class="modal-footer"><button class="secondary-button" data-action="import">Import CSV / workspace</button><button class="secondary-button" data-action="export-workspace">Export workspace</button><button class="primary-button" data-action="close-modal">Done</button></div>`);}
  openHelp(){this.openModal('Aureon Terminal',`<p class="help-intro"><strong>A clearer view of the market.</strong><br>An original, dependency-free charting workspace with WebGPU geometry, public Coinbase market data, editable analysis, and local paper execution. The chart engine, language interpreter, and application are independently implemented; no proprietary charting library or embedded third-party widget is used.</p><table class="shortcut-table"><tbody>${[['Search symbols','⌘/Ctrl K or /'],['Save layout','⌘/Ctrl S'],['Undo / redo drawings','⌘/Ctrl Z / Shift Z'],['Crosshair / select','V'],['Trend / horizontal / Fibonacci','T / H / F'],['Indicators / alert','I / A'],['Bar replay','R'],['Snap to candle OHLC','M'],['Delete selected drawing','Delete'],['Pan chart','Drag chart'],['Zoom around pointer','Mouse wheel'],['Horizontal scroll','Shift + wheel / trackpad'],['Scale price axis','Drag right axis'],['Fit chart / reset scale','Double click / Home'],['Cancel a drawing','Escape'],['Chart context menu','Right click']].map(([a,b])=>`<tr><td>${a}</td><td><kbd>${b}</kbd></td></tr>`).join('')}</tbody></table><p class="small-note">Two-point drawings support drag-to-create and click–click placement. Select a handle to resize, or drag a line to translate. Objects exposes names, colors, and removal. Run using <code>npm start</code>; all source is included.</p><div class="warning-note">Analysis software, not investment advice. Paper results are simulations with explicit assumptions, not executable prices or promises of trading performance. Browser-local alerts and orders stop being monitored when the page closes.</div><div class="modal-footer"><button class="primary-button" data-action="close-modal">Start exploring</button></div>`);}
  openAlert(price){const q=price??this.quote(this.state.symbol)?.price??0;this.openModal('Create price alert',`<form id="alert-form"><p class="small-note">${esc(this.state.symbol)} · triggered on the first live crossing. Existing conditions do not trigger immediately when the alert is created.</p><div class="form-row"><label>Condition<select name="direction"><option value="cross">Crossing in either direction</option><option value="above">Crossing above</option><option value="below">Crossing below</option></select></label></div><div class="form-row"><label>Price (USD)<input name="price" type="number" min="0.00000001" step="any" value="${q}" required></label></div><div class="warning-note">Monitoring runs only while this page is open with a live feed. Reconnect gaps may miss crossings. No server-side alerts are claimed.</div><div class="modal-footer"><button type="button" class="secondary-button" data-action="close-modal">Cancel</button><button type="submit" class="primary-button">Create alert</button></div></form>`);}
  createAlert(form){const f=new FormData(form);this.alerts.add(this.state.symbol,Number(f.get('price')),f.get('direction'));const q=this.market.quotes.get(this.state.symbol);if(q)this.alerts.previous.set(this.state.symbol,q.price);this.closeModal();if(!this.forceDemo)this.market.setSymbols(this.feedSymbols());this.setSource();this.save(false);this.setPanel('alerts');this.toast('Alert created. It will monitor live price crossings while this page stays open.');}
  editDrawing(id){const d=this.chart.drawings.find(x=>x.id===id);if(!d)return;this.chart.selected=id;this.chart.invalidate();this.openModal('Drawing properties',`<form id="drawing-form" data-id="${esc(id)}"><div class="form-row"><label>Type<input value="${esc(d.type)}" readonly></label><label>Color<input type="color" name="color" value="${esc(d.color||'#84adfa')}"></label></div>${d.type==='text'?`<div class="form-row"><label>Annotation<input name="text" maxlength="500" value="${esc(d.text||'')}"></label></div>`:''}<p class="small-note">Time / price coordinates are stored independently of zoom, pane size, and renderer backend.</p><div class="modal-footer"><button type="button" class="secondary-button" data-action="close-modal">Cancel</button><button type="submit" class="primary-button">Apply changes</button></div></form>`);}
  saveDrawing(form){const before=structuredClone(this.chart.drawings),d=this.chart.drawings.find(d=>d.id===form.dataset.id);if(!d)throw new Error('Drawing no longer exists.');const f=new FormData(form);d.color=f.get('color');if(d.type==='text')d.text=f.get('text').slice(0,500);this.drawingChanged(before,structuredClone(this.chart.drawings));this.chart.invalidate();this.closeModal();}
  setTheme(theme,save=true){this.state.theme=theme;document.body.classList.toggle('light',theme==='light');this.chart.theme=theme;this.chart.invalidate();if(this.comparison){this.comparison.theme=theme;this.comparison.invalidate();}for(const x of this.workbench?.extraCharts||[]){x.chart.theme=theme;x.chart.invalidate();}if(save)this.save(false);}
  async openComparison(){if(this.workbench?.config.layout>1)await this.workbench.setLayout(1);
    const load=++this.compareLoad;this.state.split=true;$('comparison-pane').hidden=false;$('chart-stack').classList.add('split');this.syncToolbar();
    if(!this.comparison){this.comparison=new Chart($('comparison-chart'),{symbol:this.comparisonSymbol,interval:this.state.interval,onView:v=>this.chart.syncView(v),onCrosshair:t=>{this.chart.linkedTime=t;this.chart.invalidate(false);}});this.comparison.style='area';this.comparison.enabled=['ema'];this.comparison.theme=this.state.theme;}
    const chart=this.comparison;chart.symbol=this.comparisonSymbol;chart.interval=this.state.interval;$('comparison-name').textContent=this.friendlyName(this.comparisonSymbol);
    let bars=this.demoData(this.comparisonSymbol);this.comparisonKind='demo';$('comparison-source').textContent='SYNTHETIC SAMPLE';
    if(this.kind==='market'&&!this.forceDemo)try{const result=await this.market.history(this.comparisonSymbol,this.state.interval,{pages:2});if(chart!==this.comparison||load!==this.compareLoad)return;bars=result.bars;this.comparisonKind='market';$('comparison-source').textContent='COINBASE · LIVE FEED';}catch(e){$('comparison-source').textContent='SYNTHETIC · live request failed';this.toast('Comparison data unavailable: '+e.message,true);}
    if(chart!==this.comparison||load!==this.compareLoad)return;this.comparisonSeries=new CandleSeries(bars,this.state.interval);this.comparisonSeries.acceptAfter=Date.now()/1000;chart.setData(bars,{}, {reset:true});const computed=await this.compute.run('indicators',bars);if(chart!==this.comparison||load!==this.compareLoad)return;chart.setIndicators(computed);chart.syncView({rightTime:this.chart.toTime(this.chart.right),span:this.chart.count*this.state.interval});if(!this.forceDemo)this.market.setSymbols(this.feedSymbols());this.save(false);
  }
  closeComparison(){this.compareLoad++;this.state.split=false;this.comparison?.destroy();this.comparison=null;this.comparisonSeries=null;$('comparison-pane').hidden=true;$('chart-stack').classList.remove('split');this.syncToolbar();this.save(false);}
  startReplay(){if(this.series.bars.length<35){this.toast('Load at least 35 bars for replay.',true);return;}this.replaying=true;this.strategyResult=null;this.chart.markers=[];if(this.panel==='strategy')this.renderPanel();$('replay-controls').hidden=false;$('replay-toggle').classList.add('active');$('replay-position').max=this.series.bars.length;$('replay-position').min=Math.min(30,this.series.bars.length-1);this.seekReplay(Math.max(30,Math.floor(this.series.bars.length*.7)));this.toast('Replay uses historical bars. Indicators remain causal; the advanced execution simulator can trade replayed bars.');}
  stopReplay(){if(!this.replaying)return;this.pauseReplay();this.replaying=false;if(this.comparison)$('comparison-source').textContent=this.comparisonKind==='market'?'COINBASE · MARKET DATA':'SYNTHETIC SAMPLE';this.chart.setReplay(null);this.chart.fit();this.workbench?.refresh();if(this.comparison){this.comparison.setReplay(null);this.comparison.fit();}$('replay-controls').hidden=true;$('replay-toggle').classList.remove('active');this.setSource();this.updateAllUI();}
  seekReplay(n){if(!this.replaying)return;n=clamp(Math.round(n),30,this.series.bars.length);const previous=this.chart.endLimit;this.chart.setReplay(n);this.workbench?.onReplay(previous,n);if(this.comparison&&this.comparisonSeries){const t=this.series.bars[n-1].t;this.comparison.setReplay(lowerBound(this.comparisonSeries.bars,t+this.state.interval));}$('replay-position').value=n;this.hover(this.series.bars[n-1],n-1);this.updateBarCount();this.setSource();if(['overview','data'].includes(this.panel))this.renderPanel();if(n>=this.series.bars.length)this.pauseReplay();}
  playReplay(){if(!this.replaying)this.startReplay();if(this.chart.endLimit>=this.series.bars.length)this.seekReplay(30);$('replay-play').textContent='Ⅱ';this.replayTimer=setInterval(()=>this.seekReplay(this.chart.endLimit+1),Number($('replay-speed').value));}
  pauseReplay(){clearInterval(this.replayTimer);this.replayTimer=null;$('replay-play').textContent='▶';}
  exportLabel(){return `${this.kind==='demo'?'SYNTHETIC DEMO':this.kind==='import'?'IMPORTED · '+this.modeLabel:this.kind==='cache'?'CACHED COINBASE HISTORY':'COINBASE EXCHANGE'} · ${this.state.symbol} · ${this.state.interval}s · UTC${this.replaying?' · REPLAY':''}`;}
  exportWorkspace(){if(this.workbench)return this.workbench.exportWorkspace();const payload={application:'Aureon Terminal',exportedAt:new Date().toISOString(),workspace:this.state,dataset:{symbol:this.state.symbol,interval:this.state.interval,source:this.exportLabel(),bars:this.visibleBars().map(({t,o,h,l,c,v,partial})=>({t,o,h,l,c,v,...(partial?{partial:true}:{})}))}};this.download(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`aureon-${this.state.symbol}-workspace.json`);this.toast('Portable workspace and source OHLCV exported. The paper ledger is not included.');}
  async importFile(file){const text=await file.text();if(file.name.toLowerCase().endsWith('.json')){const raw=JSON.parse(text);if(raw.extensions&&this.workbench)return this.workbench.importWorkspace(raw);}if(file.name.toLowerCase().endsWith('.csv')){const bars=parseCSV(text);if(bars.length<2)throw new Error('CSV must contain at least two valid candles.');const diffs=bars.slice(1,100).map((b,i)=>b.t-bars[i].t).sort((a,b)=>a-b),interval=diffs[Math.floor(diffs.length/2)];if(!TIMEFRAMES.some(t=>t.value===interval))throw new Error(`CSV interval ${interval}s is not supported. Use 1m, 5m, 15m, 1h, 4h, 6h, 1D or 1W.`);const s={...this.state,symbol:'CUSTOM-USD',interval};await this.installImported(s,bars,interval);this.toast(`Imported ${bars.length.toLocaleString()} OHLCV rows. Times are interpreted in UTC.`);}
    else{const raw=JSON.parse(text),state=validateWorkspace(raw.workspace||raw);if(raw.dataset?.bars){if(raw.dataset.symbol!==state.symbol||raw.dataset.interval!==state.interval)throw new Error('Dataset metadata does not match the workspace.');const bars=normalizeCandles(raw.dataset.bars);if(!bars.length)throw new Error('Workspace contains no candles.');await this.installImported(state,bars,state.interval,raw.dataset.source);this.toast('Workspace, drawings and historical OHLCV imported. Imported data is not presented as live.');}else{this.state=state;this.applyState();this.setTheme(state.theme);this.renderWatchlist();this.closeModal();await this.loadSymbol(state.symbol,state.interval);this.toast('Workspace imported.');}}
  }
  async installImported(state,bars,interval,source='Imported OHLCV'){this.abort?.abort();this.loadId++;this.stopReplay();this.loading=false;this.closeComparison();this.state=validateWorkspace({...state,interval});this.state.split=false;this.importedBars=bars;this.importedInterval=interval;this.kind='import';this.modeLabel=String(source||'Imported OHLCV').slice(0,300);this.series=new CandleSeries(bars,interval);this.applyState();this.chart.setData(bars,{}, {reset:true});this.indicatorData=null;this.strategyResult=null;this.currentHover=null;this.chart.markers=[];this.refreshIndicators();this.setTheme(this.state.theme,false);this.updateIdentity();this.renderWatchlist();this.updateAllUI();this.setSource();this.closeModal();this.history=new UndoStack();await this.cache.put('workspace-import',{bars,interval,symbol:state.symbol,source:this.modeLabel});this.save(false);}
  download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  save(notify=false){this.workbench?.save();try{localStorage.setItem('aureon.workspace',JSON.stringify(this.state));localStorage.setItem('aureon.alerts',JSON.stringify(this.alerts.alerts));localStorage.setItem('aureon.paper',JSON.stringify(this.broker.state));if(this.kind==='import')localStorage.setItem('aureon.import',JSON.stringify({symbol:this.state.symbol,interval:this.importedInterval}));else localStorage.removeItem('aureon.import');$('saved-label').textContent='Saved locally';$('storage-status').textContent='Workspace saved locally';if(notify)this.toast('Workspace, drawings, alerts, and paper ledger saved in this browser.');}catch(e){$('storage-status').textContent='Storage unavailable';if(notify)this.toast('Browser storage is unavailable. Export the workspace instead.',true);}}
  toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('toasts').appendChild(el);setTimeout(()=>el.remove(),error?8000:4500);}
}
new Application();
