/** Additional constructions share a single geometry path for drawing and picking.
 * Price/time constructions sample the nonlinear price projection rather than
 * treating a log-chart screen angle as a market-space angle.
 */
export const EXTRA_DRAWING_TOOLS={
  schiff:{name:'Schiff pitchfork',points:3,category:'Channels'},modifiedschiff:{name:'Modified Schiff pitchfork',points:3,category:'Channels'},insidepitchfork:{name:'Inside pitchfork',points:3,category:'Channels'},disjointchannel:{name:'Disjoint channel',points:4,category:'Channels'},flatchannel:{name:'Flat channel',points:2,category:'Channels'},
  trendangle:{name:'Trend angle · screen degrees',points:2,category:'Lines'},doublearrow:{name:'Double arrow',points:2,category:'Lines'},crossline:{name:'Cross line',points:1,category:'Lines'},infoline:{name:'Info line',points:2,category:'Lines'},
  fibarc:{name:'Fibonacci arcs',points:2,category:'Fibonacci / Gann'},fibwedge:{name:'Fibonacci wedge',points:3,category:'Fibonacci / Gann'},fibspiral:{name:'Fibonacci logarithmic spiral',points:2,category:'Fibonacci / Gann'},gannbox:{name:'Gann box · market coordinates',points:2,category:'Fibonacci / Gann'},gannsquare:{name:'Gann square · anchor calibrated',points:2,category:'Fibonacci / Gann'},
  polygon:{name:'Polygon · double-click ends',points:0,category:'Shapes'},curve:{name:'Quadratic Bézier curve',points:3,category:'Shapes'},doublecurve:{name:'Cubic Bézier curve',points:4,category:'Shapes'},highlighter:{name:'Highlighter path · double-click ends',points:0,category:'Shapes'},arc:{name:'Circular arc through three points',points:3,category:'Shapes'},
  projection:{name:'Three-point price projection',points:3,category:'Forecast / measure'},cycliclines:{name:'Cyclic time lines',points:2,category:'Forecast / measure'},sinewave:{name:'Sine cycle · anchor calibrated',points:3,category:'Forecast / measure'},
  flag:{name:'Flag annotation',points:1,category:'Annotation'},pricelabel:{name:'Price label',points:1,category:'Annotation'},anchorednote:{name:'Note annotation',points:1,category:'Annotation'},anchoredvwap:{name:'Anchored VWAP path',points:2,category:'Forecast / measure'},
  trianglepattern:{name:'Triangle pattern',points:5,category:'Patterns'},threeDrives:{name:'Three drives pattern',points:6,category:'Patterns'},cypher:{name:'Cypher pattern annotation',points:5,category:'Patterns'}
};
export function extraDrawingGeometry(d,chart){
  if(!Object.hasOwn(EXTRA_DRAWING_TOOLS,d.type)&&d.type!=='gannfan')return null;
  const segments=[],rects=[],labels=[],p=d.points.map(q=>({x:chart.toX(chart.timeIndex(q.t)),y:chart.toY(q.p)})),[a,b=a,c=b,e=c]=p;
  const line=(a,b,alpha=1)=>{if([a.x,a.y,b.x,b.y].every(Number.isFinite))segments.push({a,b,alpha});},label=(a,text)=>{if([a.x,a.y].every(Number.isFinite))labels.push({...a,text:String(text)});},chain=points=>points.forEach((x,i)=>{if(i)line(points[i-1],x);});
  const extend=(a,b)=>{const dx=b.x-a.x,dy=b.y-a.y;if(Math.abs(dx)<1e-9){line(a,{x:a.x,y:dy>=0?chart.price.y+chart.price.h:chart.price.y});return;}const end=dx>0?chart.plotWidth:0;line(a,{x:end,y:a.y+(end-a.x)*dy/dx});};
  const arc=(center,rx,ry,start=0,end=2*Math.PI,n=96)=>{let previous;for(let i=0;i<=n;i++){const t=start+(end-start)*i/n,q={x:center.x+rx*Math.cos(t),y:center.y+ry*Math.sin(t)};if(previous)line(previous,q);previous=q;}};
  const marketLine=(u,v)=>{let previous;for(let i=0;i<=48;i++){const f=i/48,t=u.t+(v.t-u.t)*f,price=u.p+(v.p-u.p)*f,q={x:chart.toX(chart.timeIndex(t)),y:chart.toY(price)};if(previous)line(previous,q);previous=q;}};
  switch(d.type){
    case'schiff':case'modifiedschiff':case'insidepitchfork':{let origin={...a},mid={x:(b.x+c.x)/2,y:(b.y+c.y)/2};if(d.type==='schiff')origin.y=(a.y+b.y)/2;else if(d.type==='modifiedschiff')origin={x:(a.x+b.x)/2,y:(a.y+b.y)/2};else mid={x:(a.x+mid.x)/2,y:mid.y};const delta={x:mid.x-origin.x,y:mid.y-origin.y};extend(origin,mid);extend(b,{x:b.x+delta.x,y:b.y+delta.y});extend(c,{x:c.x+delta.x,y:c.y+delta.y});line(b,c,.4);break;}
    case'disjointchannel':line(a,b);line(c,e);line({x:(a.x+c.x)/2,y:(a.y+c.y)/2},{x:(b.x+e.x)/2,y:(b.y+e.y)/2},.4);break;
    case'flatchannel':for(const y of[a.y,b.y,(a.y+b.y)/2])line({x:a.x,y},{x:b.x,y});break;
    case'trendangle':line(a,b);label(b,`${(Math.atan2(a.y-b.y,b.x-a.x)*180/Math.PI).toFixed(1)}° screen`);arc(a,28,28,0,Math.atan2(b.y-a.y,b.x-a.x),32);break;
    case'doublearrow':{line(a,b);for(const [from,to]of[[a,b],[b,a]]){const angle=Math.atan2(to.y-from.y,to.x-from.x);for(const offset of[-.45,.45])line(to,{x:to.x-12*Math.cos(angle+offset),y:to.y-12*Math.sin(angle+offset)});}break;}
    case'crossline':line({x:0,y:a.y},{x:chart.plotWidth,y:a.y});line({x:a.x,y:chart.price.y},{x:a.x,y:chart.price.y+chart.price.h});break;
    case'infoline':line(a,b);label(b,`Δ ${(d.points[1].p-d.points[0].p).toPrecision(6)} / ${((d.points[1].t-d.points[0].t)/3600).toFixed(2)} h`);break;
    case'fibarc':{const radius=Math.hypot(b.x-a.x,b.y-a.y);for(const r of[.236,.382,.5,.618,.786,1]){arc(b,radius*r,radius*r,Math.PI,2*Math.PI,64);label({x:b.x+radius*r,y:b.y},r);}line(a,b,.4);break;}
    case'fibwedge':{const start=Math.atan2(b.y-a.y,b.x-a.x),end=Math.atan2(c.y-a.y,c.x-a.x),radius=Math.max(Math.hypot(b.x-a.x,b.y-a.y),Math.hypot(c.x-a.x,c.y-a.y));line(a,b);line(a,c);for(const r of[.236,.382,.5,.618,.786,1])arc(a,radius*r,radius*r,start,end,64);break;}
    case'fibspiral':{const radius=Math.hypot(b.x-a.x,b.y-a.y),start=Math.atan2(b.y-a.y,b.x-a.x),k=Math.log((1+Math.sqrt(5))/2)/(Math.PI/2);let previous;for(let i=0;i<=256;i++){const angle=-4*Math.PI+i/256*4*Math.PI,r=radius*Math.exp(k*angle),q={x:a.x+r*Math.cos(start+angle),y:a.y+r*Math.sin(start+angle)};if(previous)line(previous,q);previous=q;}break;}
    case'gannbox':case'gannsquare':{const [u,v]=d.points;for(const ratio of[0,.125,.25,.375,.5,.625,.75,.875,1]){const t=u.t+(v.t-u.t)*ratio,price=u.p+(v.p-u.p)*ratio;marketLine({t,p:u.p},{t,p:v.p});marketLine({t:u.t,p:price},{t:v.t,p:price});}if(d.type==='gannsquare'){marketLine(u,v);marketLine({t:u.t,p:v.p},{t:v.t,p:u.p});for(const f of[.25,.5,.75]){marketLine(u,{t:v.t,p:u.p+(v.p-u.p)*f});marketLine(u,{t:u.t+(v.t-u.t)*f,p:v.p});}}label(a,'Anchor-calibrated price / time');break;}
    case'gannfan':{const [u,v]=d.points,dt=v.t-u.t;if(!dt){line(a,b);break;}const end=(chart.bars||chart.rawBars||[])[Math.max(0,Math.min((chart.bars||chart.rawBars||[]).length-1,(chart.last??(chart.bars||chart.rawBars||[]).length)-1))]?.t??v.t;for(const r of[.125,.25,.5,1,2,4,8])marketLine(u,{t:end,p:u.p+(end-u.t)*(v.p-u.p)/dt*r});label(a,'Price/time ratios');break;}
    case'polygon':chain([...p,a]);break;case'highlighter':for(let i=1;i<p.length;i++)line(p[i-1],p[i],.3);break;
    case'curve':case'doublecurve':{let previous;for(let i=0;i<=96;i++){const t=i/96,u=1-t,q=d.type==='curve'?{x:u*u*a.x+2*u*t*b.x+t*t*c.x,y:u*u*a.y+2*u*t*b.y+t*t*c.y}:{x:u**3*a.x+3*u*u*t*b.x+3*u*t*t*c.x+t**3*e.x,y:u**3*a.y+3*u*u*t*b.y+3*u*t*t*c.y+t**3*e.y};if(previous)line(previous,q);previous=q;}break;}
    case'arc':{const det=2*(a.x*(b.y-c.y)+b.x*(c.y-a.y)+c.x*(a.y-b.y));if(Math.abs(det)<1e-7){chain([a,b,c]);break;}const aa=a.x*a.x+a.y*a.y,bb=b.x*b.x+b.y*b.y,cc=c.x*c.x+c.y*c.y,center={x:(aa*(b.y-c.y)+bb*(c.y-a.y)+cc*(a.y-b.y))/det,y:(aa*(c.x-b.x)+bb*(a.x-c.x)+cc*(b.x-a.x))/det},r=Math.hypot(a.x-center.x,a.y-center.y),start=Math.atan2(a.y-center.y,a.x-center.x),mid=Math.atan2(b.y-center.y,b.x-center.x),end=Math.atan2(c.y-center.y,c.x-center.x),tau=Math.PI*2,norm=x=>(x%tau+tau)%tau;let sweep=norm(end-start);if(norm(mid-start)>sweep)sweep-=tau;arc(center,r,r,start,start+sweep);break;}
    case'projection':{const u={t:d.points[2].t+(d.points[1].t-d.points[0].t),p:d.points[2].p+(d.points[1].p-d.points[0].p)};chain(p);marketLine(d.points[2],u);label({x:chart.toX(chart.timeIndex(u.t)),y:chart.toY(u.p)},'Projected '+u.p.toPrecision(6));break;}
    case'cycliclines':{const dt=Math.abs(d.points[1].t-d.points[0].t);if(!dt)break;const first=(chart.bars||chart.rawBars||[])[chart.first]?.t??d.points[0].t,last=(chart.bars||chart.rawBars||[])[Math.min((chart.bars||chart.rawBars||[]).length-1,(chart.last??(chart.bars||chart.rawBars||[]).length)-1)]?.t??d.points[1].t,start=Math.floor((first-d.points[0].t)/dt);for(let i=0;i<200;i++){const t=d.points[0].t+(start+i)*dt;if(t>last)break;const x=chart.toX(chart.timeIndex(t));line({x,y:chart.price.y},{x,y:chart.price.y+chart.price.h},.5);}break;}
    case'sinewave':{const period=Math.abs(b.x-a.x)*2,amplitude=c.y-a.y;if(!period)break;let old;for(let i=0;i<=256;i++){const x=i/256*chart.plotWidth,q={x,y:a.y+amplitude*Math.sin((x-a.x)/period*2*Math.PI)};if(old)line(old,q);old=q;}break;}
    case'flag':line(a,{x:a.x,y:a.y-30});chain([{x:a.x,y:a.y-30},{x:a.x+25,y:a.y-23},{x:a.x,y:a.y-16}]);label({x:a.x+30,y:a.y-23},d.text||'Flag');break;
    case'pricelabel':case'anchorednote':label(a,d.type==='pricelabel'?d.points[0].p.toPrecision(8):d.text||'Note');break;
    case'anchoredvwap':{const start=Math.min(d.points[0].t,d.points[1].t),end=Math.max(d.points[0].t,d.points[1].t);let sum=0,volume=0,previous;for(const bar of chart.rawBars||chart.bars){if(bar.t<start||bar.t>end)continue;sum+=(bar.h+bar.l+bar.c)/3*bar.v;volume+=bar.v;if(!volume)continue;const q={x:chart.toX(chart.timeIndex(bar.t)),y:chart.toY(sum/volume)};if(previous)line(previous,q);previous=q;}label(a,'Anchored VWAP');break;}
    case'trianglepattern':case'threeDrives':case'cypher':chain(p);p.forEach((q,i)=>label({x:q.x,y:q.y-10},d.type==='cypher'?'XABCD'[i]:String(i)));break;
  }
  return{segments,rects,labels};
}
