import {SimulationBroker,strategyStatistics} from './execution.js';
import {validateCandle,uid} from './core.js';
import {validateTrades} from './tick-charts.js';
import {convertCurrency} from './market-analytics.js';
const ACTIVE=new Set(['open','partial','triggered']);
const positive=(n,name)=>{if(!Number.isFinite(n)||n<=0)throw new RangeError(name+' must be positive');return n;};
/** Netted portfolio with explicit FIFO/entry-ID lot basis and pending-order
 * notional reservations. Reservations are conservative, not exchange margin. */
export class PortfolioBroker extends SimulationBroker {
  constructor(options={}){super(options);this.reserveOrders=options.reserveOrders!==false;this.pyramiding=options.pyramiding??10;this.reserveBufferBps=options.reserveBufferBps??100;if(!Number.isInteger(this.pyramiding)||this.pyramiding<1||this.pyramiding>100||!Number.isFinite(this.reserveBufferBps)||this.reserveBufferBps<0||this.reserveBufferBps>5000)throw new RangeError('Invalid portfolio risk settings');this.lots=[];this.cashEvents=[];this.lastAccrual=null;}
  reserved(exceptId=null){if(!this.reserveOrders)return 0;let sum=0;const groups=new Map();for(const order of this.orders){if(!ACTIVE.has(order.status)||order.reduceOnly||order.id===exceptId)continue;const quantity=Math.max(0,order.quantity-order.filled),price=order.reservePrice??this.marks[order.symbol];if(!Number.isFinite(price))continue;const amount=quantity*price*(1+this.feeBps/10000);if(order.group)groups.set(order.group,Math.max(groups.get(order.group)||0,amount));else sum+=amount;}return sum+[...groups.values()].reduce((a,b)=>a+b,0);}
  buyingPower(){return Math.max(0,this.equity()*this.maxLeverage-this.exposure()-this.reserved());}
  submit(request,at=this.lastTime){
    const entryId=request.entryId??request.id??'manual';if(typeof entryId!=='string'||entryId.length>128)throw new Error('Invalid entry ID');
    const targetEntry=request.targetEntry??null;if(targetEntry!=null&&(typeof targetEntry!=='string'||targetEntry.length>128||!request.reduceOnly))throw new Error('Targeted exits require reduce-only and a bounded entry ID');
    if(this.orders.filter(o=>ACTIVE.has(o.status)).length>=2000)throw new Error('At most 2,000 pending portfolio orders');
    const price=request.limit??request.stop??request.referencePrice??this.marks[request.symbol];if(this.reserveOrders&&!request.reduceOnly)positive(price,'A reference/limit price for reservation');
    const reservePrice=price==null?0:price*(1+this.reserveBufferBps/10000);if(price!=null)positive(price,'Reservation price');
    if(!request.reduceOnly){const direction=request.side==='buy'?1:-1,entries=new Set([...this.lots.filter(l=>l.symbol===request.symbol&&Math.sign(l.quantity)===direction).map(l=>l.orderId),...this.orders.filter(o=>o.symbol===request.symbol&&o.side===request.side&&ACTIVE.has(o.status)).map(o=>o.id)]);if(entries.size>=this.pyramiding)throw new Error('Pyramiding limit reached');
      const amount=request.quantity*reservePrice*(1+this.feeBps/10000);if(this.reserveOrders&&(!Number.isFinite(amount)||amount>this.buyingPower()+1e-7))throw new Error('Insufficient buying power including pending reservations');}
    const order=super.submit(request,at);Object.assign(order,{entryId,targetEntry,reservePrice});return order;
  }
  amend(id,patch){const order=this.orders.find(x=>x.id===id);if(!order)throw new Error('Unknown order');const projected={...order,...patch},price=patch.limit??patch.stop??order.reservePrice/(1+this.reserveBufferBps/10000),amount=Math.max(0,projected.quantity-projected.filled)*price*(1+this.reserveBufferBps/10000)*(1+this.feeBps/10000);if(this.reserveOrders&&!order.reduceOnly&&this.exposure()+this.reserved(id)+amount>this.equity()*this.maxLeverage+1e-7)throw new Error('Amendment exceeds reserved buying power');const changed=super.amend(id,patch);changed.reservePrice=price*(1+this.reserveBufferBps/10000);return changed;}
  filterFillQuantity(order,quantity){if(!order.targetEntry)return quantity;const remaining=this.lots.filter(l=>l.symbol===order.symbol&&l.entryId===order.targetEntry&&Math.sign(l.quantity)!==(order.side==='buy'?1:-1)).reduce((s,l)=>s+Math.abs(l.quantity),0);if(!remaining){order.status='canceled';order.reason='Target entry no longer has open lots';}return Math.min(quantity,remaining);}
  onFill(fill,order,position){
    const direction=fill.side==='buy'?1:-1;let closing=fill.closedQuantity,entryNotional=0,entryFees=0,entryTime=null,gross=0;
    const candidates=this.lots.filter(l=>l.symbol===fill.symbol&&Math.sign(l.quantity)!==direction&&(!order.targetEntry||l.entryId===order.targetEntry)).sort((a,b)=>a.sequence-b.sequence);
    for(const lot of candidates){if(closing<=1e-12)break;const take=Math.min(closing,Math.abs(lot.quantity)),portion=take/Math.abs(lot.quantity),fees=lot.fees*portion;entryNotional+=take*lot.price;entryFees+=fees;entryTime=entryTime==null?lot.time:Math.min(entryTime,lot.time);gross+=(fill.price-lot.price)*take*Math.sign(lot.quantity);lot.quantity-=Math.sign(lot.quantity)*take;lot.fees-=fees;closing-=take;}
    if(closing>1e-7)throw new Error('Lot ledger invariant: insufficient closing quantity');
    this.lots=this.lots.filter(l=>Math.abs(l.quantity)>1e-12);const net=fill.closedQuantity?gross-entryFees-fill.fee*fill.closedQuantity/fill.quantity:0,difference=net-fill.realized;fill.realized=net;fill.entryId=order.entryId;fill.targetEntry=order.targetEntry;fill.entryPrice=fill.closedQuantity?entryNotional/fill.closedQuantity:null;fill.entryTime=entryTime;this.realized+=difference;position.realized+=difference;
    const opened=fill.quantity-fill.closedQuantity;if(opened>1e-12){const existing=this.lots.find(l=>l.orderId===order.id&&Math.sign(l.quantity)===direction);if(existing){const old=Math.abs(existing.quantity);existing.price=(existing.price*old+fill.price*opened)/(old+opened);existing.quantity+=direction*opened;existing.fees+=fill.fee*opened/fill.quantity;}else this.lots.push({id:uid(),symbol:fill.symbol,entryId:order.entryId,orderId:order.id,sequence:order.sequence,time:fill.time,quantity:direction*opened,price:fill.price,fees:fill.fee*opened/fill.quantity});}
    const remain=this.lots.filter(l=>l.symbol===fill.symbol),quantity=remain.reduce((s,l)=>s+Math.abs(l.quantity),0);position.average=quantity?remain.reduce((s,l)=>s+Math.abs(l.quantity)*l.price,0)/quantity:0;position.entryFees=remain.reduce((s,l)=>s+l.fees,0);if(remain.length)position.entryTime=Math.min(...remain.map(l=>l.time));
  }
  closeEntry(symbol,entryId,at=this.lastTime,{quantity=Infinity,limit,stop}={}){const lots=this.lots.filter(l=>l.symbol===symbol&&l.entryId===entryId),total=lots.reduce((s,l)=>s+Math.abs(l.quantity),0);if(!total)return null;const side=lots[0].quantity>0?'sell':'buy';return this.submit({symbol,side,quantity:Math.min(total,quantity),reduceOnly:true,targetEntry:entryId,entryId:'exit:'+entryId,type:limit!=null&&stop!=null?'stop-limit':limit!=null?'limit':stop!=null?'stop':'market',limit,stop},at);}
  accrue(time,{cashRate=0,borrowRate=0,funding={}}={}){if(!Number.isFinite(time)||time<this.lastTime||[cashRate,borrowRate].some(x=>!Number.isFinite(x))||Math.abs(cashRate)>1||borrowRate<0||borrowRate>10)throw new Error('Invalid accrual specification');const from=this.lastAccrual??this.lastTime;if(time<from)throw new Error('Accrual clock cannot reverse');if(time===from)return 0;const years=(time-from)/31557600;let cash=Math.max(0,this.cash)*cashRate*years;for(const[symbol,p]of Object.entries(this.positions)){if(!p.quantity)continue;const price=this.marks[symbol];positive(price,'Mark for accrual');if((this.markTimes?.[symbol]??-Infinity)>time)throw new Error('Future mark in accrual');if(p.quantity<0)cash-=Math.abs(p.quantity)*price*borrowRate*years;const rate=funding[symbol]??0;if(!Number.isFinite(rate)||Math.abs(rate)>1)throw new Error('Invalid period funding rate');cash-=p.quantity*price*rate;}this.cash+=cash;this.lastAccrual=time;this.lastTime=time;this.cashEvents.push({id:uid(),type:'accrual',time,from,cash,cashRate,borrowRate,funding:{...funding}});return cash;}
  corporateAction({id,symbol,time,kind,ratio,amount}){if(typeof id!=='string'||!id||id.length>128||!Number.isFinite(time)||time<this.lastTime||!['split','dividend'].includes(kind))throw new Error('Invalid corporate action');if(this.cashEvents.some(e=>e.id===id))return false;const p=this.positions[symbol];if(kind==='split')positive(ratio,'Split ratio');else if(!Number.isFinite(amount)||amount<0)throw new Error('Invalid cash dividend');let cash=0;if(kind==='split'){if(p){p.quantity*=ratio;p.average/=ratio;}if(this.marks[symbol])this.marks[symbol]/=ratio;for(const lot of this.lots.filter(l=>l.symbol===symbol)){lot.quantity*=ratio;lot.price/=ratio;}for(const order of this.orders.filter(o=>o.symbol===symbol&&ACTIVE.has(o.status))){order.quantity*=ratio;order.filled*=ratio;order.average/=ratio;for(const key of['limit','stop','trail','reservePrice','extreme'])if(order[key]!=null)order[key]/=ratio;if(order.bracket)for(const key of['takeProfit','stopLoss'])if(order.bracket[key]!=null)order.bracket[key]/=ratio;}}else{cash=(p?.quantity||0)*amount;this.cash+=cash;}this.lastTime=time;this.cashEvents.push({id,symbol,time,type:kind,ratio,amount,cash});return true;}
  snapshot(){return{version:3,base:super.snapshot(),lots:structuredClone(this.lots),cashEvents:structuredClone(this.cashEvents),lastAccrual:this.lastAccrual,settings:{reserveOrders:this.reserveOrders,pyramiding:this.pyramiding,reserveBufferBps:this.reserveBufferBps}};}
  static restore(raw){const base=SimulationBroker.restore(raw?.version===3?raw.base:raw),p=new PortfolioBroker({...base,...raw?.settings});Object.assign(p,base);const original=raw?.version===3?raw.base:raw;
    for(let i=0;i<p.orders.length;i++){const o=original.orders[i];p.orders[i].entryId=String(o.entryId||o.id).slice(0,128);p.orders[i].targetEntry=o.targetEntry==null?null:String(o.targetEntry).slice(0,128);p.orders[i].reservePrice=o.reservePrice??o.limit??o.stop??p.marks[o.symbol];if(ACTIVE.has(o.status)&&!o.reduceOnly&&p.reserveOrders)positive(p.orders[i].reservePrice,'Saved reservation');}
    if(raw?.version===3){if(!Array.isArray(raw.lots)||raw.lots.length>100000||!Array.isArray(raw.cashEvents)||raw.cashEvents.length>100000)throw new Error('Invalid portfolio ledger');p.lots=raw.lots.map(l=>{if(!l||typeof l.entryId!=='string'||!p.orders.some(o=>o.id===l.orderId)||!Number.isFinite(l.quantity)||!l.quantity||!Number.isFinite(l.fees)||l.fees<0||!Number.isFinite(l.time)||!Number.isSafeInteger(l.sequence))throw new Error('Invalid saved lot');positive(l.price,'Lot price');return structuredClone(l);});p.cashEvents=structuredClone(raw.cashEvents);if(raw.lastAccrual!=null&&!Number.isFinite(raw.lastAccrual))throw new Error('Invalid accrual time');p.lastAccrual=raw.lastAccrual;}
    else for(const[symbol,pos]of Object.entries(p.positions))if(pos.quantity)p.lots.push({id:uid(),symbol,entryId:'legacy',orderId:p.fills.findLast(f=>f.symbol===symbol)?.orderId||'legacy',sequence:0,time:pos.entryTime,quantity:pos.quantity,price:pos.average,fees:pos.entryFees});
    for(const[symbol,pos]of Object.entries(p.positions)){const lots=p.lots.filter(l=>l.symbol===symbol);if(Math.abs(lots.reduce((s,l)=>s+l.quantity,0)-pos.quantity)>1e-7||lots.some(l=>Math.sign(l.quantity)!==Math.sign(pos.quantity)))throw new Error('Saved lot/position mismatch');}return p;
  }
}
/** A deliberately explicit queue model: starting queue-ahead must be supplied.
 * Only actual aggressor prints consume it. It does not assert exchange priority. */
export class LimitQueueModel {
  constructor(){this.orders=[];this.lastTime=-Infinity;this.seen=new Set();}
  add({id,side,price,quantity,ahead=0}){if(!id||this.orders.some(o=>o.id===id)||!['buy','sell'].includes(side)||!Number.isFinite(ahead)||ahead<0)throw new Error('Invalid queue order');positive(price,'Limit price');positive(quantity,'Quantity');ahead=Math.max(ahead,...this.orders.filter(o=>o.side===side&&o.price===price&&o.remaining).map(o=>o.ahead+o.remaining));const order={id,side,price,remaining:quantity,ahead,filled:0};this.orders.push(order);return order;}
  cancel(id){const i=this.orders.findIndex(o=>o.id===id);if(i<0)return false;const old=this.orders[i];for(const next of this.orders.slice(i+1))if(next.side===old.side&&next.price===old.price)next.ahead=Math.max(0,next.ahead-old.remaining);this.orders.splice(i,1);return true;}
  trade(raw){const[t]=validateTrades([raw]);if(t.t<this.lastTime)throw new Error('Queue clock cannot reverse');this.lastTime=t.t;if(t.id&&this.seen.has(t.id))return[];if(t.id){this.seen.add(t.id);if(this.seen.size>100000)this.seen.delete(this.seen.values().next().value);}let available=t.size;const fills=[],eligible=this.orders.filter(o=>o.remaining&&t.side!=='unknown'&&t.side!==o.side&&(o.side==='buy'?t.price<=o.price:t.price>=o.price)).sort((a,b)=>a.side==='buy'?b.price-a.price:a.price-b.price);
    for(let i=0;i<eligible.length;i++){const order=eligible[i];if(!available)break;const oldAvailable=available;if(t.price===order.price){const ahead=Math.min(order.ahead,available);order.ahead-=ahead;available-=ahead;}else order.ahead=0;const quantity=Math.min(order.remaining,available);if(quantity){order.remaining-=quantity;order.filled+=quantity;available-=quantity;fills.push({orderId:order.id,time:t.t,price:order.price,quantity});}const consumed=oldAvailable-available;for(const next of eligible.slice(i+1))if(next.price===order.price)next.ahead=Math.max(0,next.ahead-consumed);}
    return fills;
  }
}
export function marketImpactBps(quantity,volume,{coefficient=10,max=500}={}){if(!Number.isFinite(quantity)||quantity<0||!Number.isFinite(volume)||volume<=0||!Number.isFinite(coefficient)||coefficient<0||!Number.isFinite(max)||max<0)throw new Error('Invalid impact assumptions');return Math.min(max,coefficient*Math.sqrt(quantity/volume));}
export class MultiCurrencyCash {
  constructor(balances={}){this.balances={};this.events=[];for(const[k,v]of Object.entries(balances)){if(!/^[A-Z]{3,8}$/.test(k)||!Number.isFinite(v))throw new Error('Invalid currency balance');this.balances[k]=v;}}
  exchange(from,to,amount,quotes,options){positive(amount,'Exchange amount');if((this.balances[from]||0)<amount)throw new Error('Insufficient currency balance');const result=convertCurrency(amount,from,to,quotes,options);this.balances[from]-=amount;this.balances[to]=(this.balances[to]||0)+result.amount;this.events.push({from,to,amount,result:result.amount,path:result.path});return result;}
  value(base,quotes,options){return Object.entries(this.balances).reduce((sum,[currency,value])=>sum+convertCurrency(value,currency,base,quotes,options).amount,0);}
}
export function optionSettlement({right,strike,multiplier=100,quantity,style='cash',expiry,time,spot,underlyingShares=0,cash=0}){if(!['call','put'].includes(right)||!['cash','physical'].includes(style)||!Number.isFinite(quantity)||!quantity||!Number.isFinite(time)||time<expiry||!Number.isFinite(expiry)||![cash,underlyingShares].every(Number.isFinite))throw new Error('Invalid option settlement');positive(strike,'Strike');positive(multiplier,'Multiplier');positive(spot,'Observed settlement spot');const intrinsic=Math.max(0,(right==='call'?1:-1)*(spot-strike)),units=quantity*multiplier;if(!intrinsic)return{cash,underlyingShares,optionQuantity:0,cashFlow:0,sharesChange:0,exercised:false};const sharesChange=style==='physical'?(right==='call'?1:-1)*units:0,cashFlow=style==='cash'?intrinsic*units:-sharesChange*strike;return{cash:cash+cashFlow,underlyingShares:underlyingShares+sharesChange,optionQuantity:0,cashFlow,sharesChange,exercised:true};}
/** Confirmed-close strategy commands execute on the next source bar. Magnifier
 * mode requires supplied trade aggregates to reconcile every OHLCV bar. */
export function runPortfolioBacktest(bars,{commands=[],ticks=null,initial=100000,feeBps=10,slippageBps=5,allocation=.9,maxLeverage=1,pyramiding=1,stopPct=0,takePct=0,allowShort=true,start=0,end=bars.length}={}){
  if(!bars.length||!Number.isInteger(start)||!Number.isInteger(end)||start<0||end>bars.length||end<=start||!Number.isFinite(allocation)||allocation<=0||allocation>1||!Number.isFinite(stopPct)||stopPct<0||stopPct>=100||!Number.isFinite(takePct)||takePct<0||takePct>10000)throw new Error('Invalid strategy window/risk');let previous=-Infinity;for(const b of bars){validateCandle(b);if(b.synthetic||b.t<=previous)throw new Error('Execution requires ascending raw OHLCV');previous=b.t;}
  const trades=ticks?validateTrades(ticks):null,broker=new PortfolioBroker({initial,feeBps,slippageBps,maxLeverage,pyramiding,maintenance:Math.min(.2,.5/maxLeverage)}),symbol='BACKTEST',byIndex=new Map(),equity=[],markers=[];let cursor=0;
  for(const command of commands){if(!Number.isInteger(command.index)||command.index<0||command.index>=bars.length)throw new Error('Invalid command index');if(!byIndex.has(command.index))byIndex.set(command.index,[]);byIndex.get(command.index).push(command);}
  for(let i=start;i<end;i++){const bar=bars[i];if(bar.partial)break;const next=bars[i+1]?.t??bar.t+(i?bar.t-bars[i-1].t:60),events=[];
    if(trades){while(cursor<trades.length&&trades[cursor].t<bar.t)cursor++;while(cursor<trades.length&&trades[cursor].t<next)events.push(trades[cursor++]);if(!events.length)throw new Error('Bar magnifier has a trade-data gap');const prices=events.map(t=>t.price),volume=events.reduce((s,t)=>s+t.size,0),expected=[bar.o,bar.h,bar.l,bar.c,bar.v],actual=[prices[0],prices.reduce((a,b)=>Math.max(a,b),-Infinity),prices.reduce((a,b)=>Math.min(a,b),Infinity),prices.at(-1),volume];if(actual.some((x,j)=>Math.abs(x-expected[j])>1e-7*Math.max(1,Math.abs(expected[j]))))throw new Error('Actual trade data does not reconcile raw OHLCV; magnifier refused');}
    const first=events[0]||{t:bar.t,price:bar.o},tick=(event)=>broker.tick({symbol,time:event.t,price:event.price,liquidity:trades?event.size:Infinity});
    // Existing orders have priority. Consume one shared liquidity budget per print.
    let consumed=tick(first).reduce((s,f)=>s+f.quantity,0);
    if(i>start)for(const command of byIndex.get(i-1)||[]){const id=String(command.id||'entry'),direction=command.direction,position=broker.positions[symbol]?.quantity||0;
      if(command.action==='cancel'){for(const o of broker.orders)if(o.entryId===id)broker.cancel(o.id);continue;}if(command.action==='cancel_all'){broker.cancelAll();continue;}
      if(command.action==='close'||command.action==='close_all'){if(command.action==='close_all'||id==='all'){broker.cancelAll(symbol);if(position)broker.submit({symbol,side:position>0?'sell':'buy',quantity:Math.abs(position),reduceOnly:true},first.t);}else broker.closeEntry(symbol,id,first.t,{quantity:command.quantity??Infinity});continue;}
      if(command.action==='exit'){for(const o of broker.orders)if(o.symbol===symbol&&o.entryId===id&&o.reduceOnly)broker.cancel(o.id);const targets=command.fromEntry?[command.fromEntry]:[...new Set(broker.lots.map(l=>l.entryId))];for(const target of targets){const lots=broker.lots.filter(l=>l.entryId===target),quantity=Math.min(command.quantity??Infinity,lots.reduce((s,l)=>s+Math.abs(l.quantity),0));if(!quantity)continue;const group=uid(),side=lots[0].quantity>0?'sell':'buy';if(command.limit!=null)broker.submit({symbol,side,type:'limit',quantity,limit:command.limit,reduceOnly:true,targetEntry:target,group,entryId:id},first.t);if(command.stop!=null)broker.submit({symbol,side,type:'stop',quantity,stop:command.stop,reduceOnly:true,targetEntry:target,group,entryId:id},first.t);}continue;}
      if(command.action!=='entry'||![1,-1].includes(direction))throw new Error('Unsupported strategy command');if(direction<0&&!allowShort)continue;
      if(position&&Math.sign(position)!==direction){broker.cancelAll(symbol);broker.submit({symbol,side:position>0?'sell':'buy',quantity:Math.abs(position),reduceOnly:true},first.t);const fills=broker.tick({symbol,time:first.t,price:first.price,liquidity:trades?Math.max(0,first.size-consumed):Infinity});consumed+=fills.reduce((s,f)=>s+f.quantity,0);if(broker.positions[symbol]?.quantity)continue;}
      if(!command.quantity&&broker.lots.length>=pyramiding)continue;const quantity=command.quantity??broker.buyingPower()*allocation/(first.price*(1+(feeBps+slippageBps+broker.reserveBufferBps)/10000));if(!(quantity>0))continue;
      const bracket={};if(stopPct)bracket.stopLoss=first.price*(1-direction*stopPct/100);if(takePct)bracket.takeProfit=first.price*(1+direction*takePct/100);for(const price of Object.values(bracket))positive(price,'Protective price');
      broker.submit({symbol,side:direction>0?'buy':'sell',type:command.limit!=null&&command.stop!=null?'stop-limit':command.limit!=null?'limit':command.stop!=null?'stop':'market',quantity,limit:command.limit,stop:command.stop,entryId:id,referencePrice:first.price,bracket:Object.keys(bracket).length?bracket:null},first.t);
    }
    broker.tick({symbol,time:first.t,price:first.price,liquidity:trades?Math.max(0,first.size-consumed):Infinity});
    if(trades){for(const event of events.slice(1))tick(event);}else{const direction=Math.sign(broker.positions[symbol]?.quantity||1),dt=(next-bar.t)/4;for(const [j,price]of[direction>0?bar.l:bar.h,direction>0?bar.h:bar.l,bar.c].entries())tick({t:bar.t+(j+1)*dt,price});}
    equity.push({t:bar.t,value:broker.equity()});
  }
  const closed=broker.fills.filter(f=>f.closedQuantity>0).map(f=>({t:f.entryTime,exitTime:f.time,price:f.entryPrice,exitPrice:f.price,quantity:f.closedQuantity,pnl:f.realized,side:f.entrySide,entryId:f.targetEntry}));for(const fill of broker.fills)markers.push({t:fill.time,p:fill.price,side:fill.side});return{...strategyStatistics(equity,closed,initial,broker.totalFees),equity,trades:closed,markers,orders:broker.orders,lots:broker.lots,account:broker.snapshot(),assumptions:{intrabar:trades?'Supplied actual prints; raw OHLCV reconciliation required':'OHLC adverse-first approximation; no fabricated tick history',reservation:'Pending gross notional plus fee and buffer; not exchange margin',matching:'Netted positions; FIFO or target entry ID; finite shared print size in magnifier mode'}};
}
