import {normalizeCandles,validateWorkspace} from './core.js';
import {SessionCalendar} from './analytics.js';
import {STUDIES,studyParameters} from './studies.js';
import {SCRIPT_EXAMPLES} from './script.js';
export function defaultExtensions(){return{version:2,studies:[],studyTemplates:[],scripts:[{id:'trend',name:'Adaptive trend',source:SCRIPT_EXAMPLES.trend},{id:'strategy',name:'Dual EMA strategy',source:SCRIPT_EXAMPLES.strategy},{id:'oscillator',name:'RSI oscillator',source:SCRIPT_EXAMPLES.oscillator}],scriptId:'trend',scriptInputs:{},typeOptions:{},timezone:'UTC',layout:1,layoutItems:[],syncViews:true,syncCrosshair:true,layouts:[],watchlists:{Default:['BTC-USD','ETH-USD','SOL-USD','XRP-USD']},research:{version:1,source:'User-imported research',universe:[],events:[],fundamentals:[],news:[]},rules:[],profile:false,session:null};}
export function validateResearch(raw){if(!raw||raw.version!==1)throw new Error('Research schema requires version: 1.');const out={version:1,source:String(raw.source||'User import').slice(0,200),universe:[],events:[],fundamentals:[],news:[]};
  for(const key of['universe','events','fundamentals','news'])if(raw[key]!=null&&(!Array.isArray(raw[key])||raw[key].length>(key==='universe'?100:10000)))throw new Error('Invalid research '+key);
  let candleCount=0;for(const u of raw.universe||[]){if(typeof u.symbol!=='string'||!/^[A-Z0-9._/-]{1,40}$/.test(u.symbol)||!Number.isInteger(u.interval)||u.interval<1)throw new Error('Invalid universe metadata');const bars=normalizeCandles(u.bars);candleCount+=bars.length;if(candleCount>500000)throw new Error('Research candle limit is 500,000.');out.universe.push({symbol:u.symbol,interval:u.interval,source:String(u.source||out.source).slice(0,200),bars});}
  for(const e of raw.events||[]){if(!Number.isFinite(e.time)||e.time<0||typeof e.title!=='string')throw new Error('Invalid calendar event');out.events.push({id:String(e.id||e.time+e.title).slice(0,128),time:e.time,title:e.title.slice(0,300),kind:String(e.kind||'economic').slice(0,40),country:String(e.country||'').slice(0,30),symbol:String(e.symbol||'').slice(0,40),impact:['low','medium','high'].includes(e.impact)?e.impact:'low',actual:e.actual==null?null:String(e.actual).slice(0,100),forecast:e.forecast==null?null:String(e.forecast).slice(0,100),previous:e.previous==null?null:String(e.previous).slice(0,100)});}
  for(const f of raw.fundamentals||[]){if(typeof f.symbol!=='string'||typeof f.period!=='string'||!f.metrics||typeof f.metrics!=='object'||Array.isArray(f.metrics))throw new Error('Invalid fundamentals record');const metrics={};for(const[k,v]of Object.entries(f.metrics)){if(!/^[\w .%-]{1,64}$/.test(k)||!Number.isFinite(v))throw new Error('Fundamental metric must be finite');metrics[k]=v;}out.fundamentals.push({symbol:f.symbol.slice(0,40),period:f.period.slice(0,40),currency:String(f.currency||'USD').slice(0,8),metrics});}
  for(const n of raw.news||[]){if(typeof n.title!=='string'||!Number.isFinite(n.time))throw new Error('Invalid news item');out.news.push({title:n.title.slice(0,500),time:n.time,source:String(n.source||out.source).slice(0,100),summary:String(n.summary||'').slice(0,2000),url:String(n.url||'').slice(0,2000),symbols:Array.isArray(n.symbols)?n.symbols.map(String).slice(0,100):[]});}
  return out;
}
export function validateExtensions(raw,depth=0){const out=defaultExtensions();if(!raw||raw.version!==2)return out;
  out.studies=(Array.isArray(raw.studies)?raw.studies:[]).slice(0,32).map(s=>{if(!Object.hasOwn(STUDIES,s.type)||typeof s.id!=='string')throw new Error('Invalid saved study');return{id:s.id.slice(0,128),type:s.type,params:studyParameters(s.type,s.params),color:/^#[\da-f]{6}$/i.test(s.color||'')?s.color:'#578bfa',visible:s.visible!==false,overlay:s.overlay??!!STUDIES[s.type].overlay};});
  out.scripts=(Array.isArray(raw.scripts)?raw.scripts:out.scripts).slice(0,100).map(s=>{if(typeof s.source!=='string'||s.source.length>100000)throw new Error('Invalid saved script');return{id:String(s.id).slice(0,100),name:String(s.name).slice(0,100),source:s.source};});out.scriptId=out.scripts.some(s=>s.id===raw.scriptId)?raw.scriptId:out.scripts[0]?.id;
  for(const key of['box','baseline','lines','reversal'])if(raw.typeOptions?.[key]!=null){const v=raw.typeOptions[key];if(!Number.isFinite(v)||(key!=='baseline'&&v<=0))throw new Error('Invalid chart option');out.typeOptions[key]=v;}
  try{new Intl.DateTimeFormat('en',{timeZone:raw.timezone});out.timezone=raw.timezone||'UTC';}catch{}
  out.layout=[1,2,4,6,8].includes(raw.layout)?raw.layout:1;out.layoutItems=(Array.isArray(raw.layoutItems)?raw.layoutItems:[]).slice(0,7).map(x=>{if(!x||typeof x.symbol!=='string'||!/^[A-Z0-9._/-]{1,40}$/.test(x.symbol)||![60,300,900,3600,14400,21600,86400,604800].includes(x.interval))throw new Error('Invalid chart tile');return{symbol:x.symbol,interval:x.interval};});out.syncViews=raw.syncViews!==false;out.syncCrosshair=raw.syncCrosshair!==false;out.profile=!!raw.profile;
  out.studyTemplates=(Array.isArray(raw.studyTemplates)?raw.studyTemplates:[]).slice(0,100).map(t=>({id:String(t.id).slice(0,128),name:String(t.name).slice(0,100),studies:validateExtensions({version:2,studies:t.studies},1).studies,legacy:(Array.isArray(t.legacy)?t.legacy:[]).filter(x=>['ema','sma','bb','vwap','rsi','macd','atr','stoch','obv'].includes(x))}));
  out.layouts=depth?[]:(Array.isArray(raw.layouts)?raw.layouts:[]).slice(0,30).map(l=>{if(l?.payload?.application!=='Aureon Terminal')throw new Error('Invalid named layout');return{id:String(l.id).slice(0,128),name:String(l.name).slice(0,100),payload:{application:'Aureon Terminal',version:2,workspace:validateWorkspace(l.payload.workspace),extensions:validateExtensions({...l.payload.extensions,layouts:[]},1)}};});
  if(raw.watchlists&&typeof raw.watchlists==='object'&&!Array.isArray(raw.watchlists)){out.watchlists={};for(const[k,v]of Object.entries(raw.watchlists).slice(0,30))if(!['__proto__','constructor','prototype'].includes(k)&&Array.isArray(v))out.watchlists[k.slice(0,100)]=v.filter(x=>typeof x==='string'&&/^[A-Z0-9.-]+-USD$/.test(x)).slice(0,50);}
  out.scriptInputs={};if(raw.scriptInputs&&typeof raw.scriptInputs==='object'&&!Array.isArray(raw.scriptInputs))for(const[k,v]of Object.entries(raw.scriptInputs).slice(0,256)){if(!/^[\w .:-]{1,200}$/.test(k)||['__proto__','constructor','prototype'].includes(k)||!['string','number','boolean'].includes(typeof v)||(typeof v==='number'&&!Number.isFinite(v))||(typeof v==='string'&&v.length>2000))throw new Error('Invalid saved script input');out.scriptInputs[k]=v;}
  out.research=raw.research?validateResearch(raw.research):out.research;
  if(raw.session){const q=raw.session;if(!Array.isArray(q.weekdays)||q.weekdays.some(x=>!Number.isInteger(x)||x<0||x>6)||(q.holidays!=null&&(!Array.isArray(q.holidays)||q.holidays.length>10000||q.holidays.some(x=>!/^\d{4}-\d{2}-\d{2}$/.test(x)))))throw new Error('Invalid session calendar');new SessionCalendar(q);out.session={timezone:q.timezone||out.timezone,open:q.open,close:q.close,weekdays:[...new Set(q.weekdays)],holidays:q.holidays||[]};}
  if(new Set(out.studies.map(s=>s.id)).size!==out.studies.length||new Set(out.scripts.map(s=>s.id)).size!==out.scripts.length)throw new Error('Duplicate persistent identity');if(!out.scripts.length){out.scripts=defaultExtensions().scripts;out.scriptId=out.scripts[0].id;}return out;
}
